KhronosGroup/Vulkan-Loader

BUILD.md
loader/CMakeLists.txt

Updated the CMakeList.txt file to look in the Vulkan-Headers submodule for header files.
Updated the BUILD.md file to reflect the change in workflow required to build and test the Vulkan-Loader repository.

Add MacOS build capability

---

.travis.yml
README.md

This change adds a configuration to Travis that builds a Debug build with clang on MacOS. It also updates the table in the readme to show that MacOS is getting tested by Travis.

Add MacOS config to Travis CI

---

tests/CMakeLists.txt
tests/README.md
tests/layers/CMakeLists.txt
tests/layers/linux/VkLayer_meta.json
tests/layers/macos/VkLayer_meta.json
tests/layers/windows/VkLayer_meta.json
tests/loader_validation_tests.cpp
tests/run_loader_tests.sh
tests/vk_loader_validation_tests.vcxproj.user

This fixes #13 by using the existing test layers instead of validation layers in the tests. It also adds a metalayer for testing, and adds a brief readme to describe how to run the tests.

Remove test dependency on validation layers

---

.appveyor.yml
.gitmodules
.travis.yml
BUILD.md
CMakeLists.txt
loader/CMakeLists.txt
scripts/loader_genvk.py

This fixes #22. This PR removes the Vulkan-Headers submodule, and instead uses a CMake Fine Module. Building the repo now requires setting `-DVULKAN_HEADERS_INSTALL_DIR` so that the loader can find the headers and registry file from Vulkan-Headers.

Replace Vulkan-Headers submodule

---

.appveyor.yml
.gitignore
.gitmodules
.travis.yml
BUILD.md
CMakeLists.txt
external/CMakeLists.txt
external/README.md
tests/CMakeLists.txt

This changes removes the Google Test submodule and changes the build system to make Google Test optional. Tests will not be built when Google Test is not present, but cloning it into the "external" directory will cause tests to be built by default.
This PR also updates CI and documentation to match the build system changes.

Remove Google Test submodule

---

cmake/FindVulkanHeaders.cmake

Fixed findVulkanHeaders.cmake to find headers in CMAKE_PREFIX_PATH. The problem was is registry path not searchable and  potentially misaligned with headers.

make vulkan headers searchable with CMAKE_PREFIX_PATH

---

loader/loader.h
loader/vulkan-1.def
loader/wsi.c
loader/wsi.h
scripts/loader_extension_generator.py

The 1.0.76 header introduced a new instance extension, `VK_KHR_get_display_properties2`. Since this is an instance extension, it requires loader support to function properly. This PR adds that support. Note that this requires a 1.0.76 header to build.

Add loader support for VK_KHR_get_display_properties2

---

loader/CMakeLists.txt
tests/CMakeLists.txt

- Move the CMake code to copy the loader DLL from the loader target
definition to the test target definition.  The test should be
taking responsibility for copying this DLL and it avoids doing the
copy if BUILD_TESTS is on and gtest is not present.
- Use better CMake code to perform the copy.

cmake: Move loader copy to test dir

---

.appveyor.yml

- Get rid of TOP_DIR - it wasn't set to anything
- Remove unmeeded submodule update
- Build 2 jobs instead of 4
- Use -A CMake argument instead of creating a generator string
based on the worker image and architecture.  Instead, set the
architecture (platform Win32 or x64) with -A and take whatever
Visual Studio version is provided by the worker image.  The
worker image is specified by the "os" config property.

ci: Clean up AppVeyor config file

---

BUILD.md
CMakeLists.txt
external/CMakeLists.txt
tests/CMakeLists.txt

Behavior is largely unchanged except that specifying BUILD_TESTS=ON
with googletest not present no longer quietly skips building the tests.
- Make inclusion of external directory unconditional.  We may someday
put something there is not related to testing.
- Make default for BUILD_TEST dependent on googletest presence.
- Remove if() around entire contents of tests CMake file.
- Add CMake messaging to clarify googletest activity.
- Throw a CMake error if googletest not present and BUILD_TESTS=ON

build: Improve googletest handling

---

CMakeLists.txt
loader/loader.h
scripts/dispatch_table_helper_generator.py

This change removes the assumption that `vk_layer.h` will include `vk_layer_dispatch_table.h`, since that include should be removed in the near future. The change to remove the extra include is KhronosGroup/Vulkan-Headers#11.
This changes also fixes #43 (which is what motivated this change). The problem there is that `vk_layer_dispatch_table.h` was being installed, which it really shouldn't be. It was installed because `vk_layer.h` depends on it, but there's no good reason for that dependency to exist.

Rework include dependencies

---

loader/loader.c

The loader was not setting the device flag indicating that the
VK_EXT_debug_utils extension had been set in the instance unless
one or more device extensions had been added to the list.
This fixes the bug caught by nikitablack on StackOverflow internally known as issue #54.
Change-Id: I23c24ee059ab5a66b9dbfdb9fa9ddab009fb2118

loader: GH54: Fix setfault with VK_EXT_debug_utils

---

CMakeLists.txt
cmake/FindVulkanHeaders.cmake
loader/CMakeLists.txt
tests/layers/CMakeLists.txt

Update the FindVulkaHeaders.cmake file to determine the Vulkan
header latest Major/Minor/Patch version.
Now, when you use FindVulkanHeaders.cmake, it creates 3 new variables that it generates from the vulkan header file (either vulkan_core.h or vulkan.h):
* VulkanHeaders_VERSION_MAJOR
* VulkanHeaders_VERSION_MINOR
* VulkanHeaders_VERSION_PATCH
These are the latest API versions for the header and can be used anywhere we currently hard-code a version.
Change-Id: Ia2a2df56d6ca6687ccb904f6c286c82553586695

loader: Update FindVulkanHeaders CMake

---

.appveyor.yml
.gitignore
.travis.yml
scripts/known_good.json
scripts/update_deps.py

This PR adds the `update_deps.py` script from [Vulkan-ValidationLayers](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/update_deps.py) and also adds a known-good file to go with it. It also adjusts CI to use this script instead of cloning and installing the top of tree from Vulkan-Headers.

Add update_deps script and use it in CI jobs

---

.cmake-format.py
CMakeLists.txt
external/CMakeLists.txt
loader/CMakeLists.txt
tests/CMakeLists.txt
tests/layers/CMakeLists.txt

This is the first PR cleaning up CMake files in the Vulkan-Loader repo. It consists primarily of cleanup, dead code/variable removal, and simplification.
This PR (in its current form of many separate commits) meant to make it easier to review; it will be squashed to a single commit before pushing to VL master.

CMake cleanup, part 1

---

CMakeLists.txt
loader/CMakeLists.txt

Fix  #79
The ninja generator was passing flags from `(add|target)_compile_options` to MASM. This commit uses generator expressions to persuade all generators to only apply the options to C/CXX.
Change-Id: Ie15d8a47636d228732950fb5b3462a2819d5b2af

build: Fix ninja on windows build

---

loader/debug_utils.c

If the object count was 0, then no message was reported by the loader.
Change-Id: Ia809d193fb117e85742af0db9856f896be0b2ea3

loader: Fix vkSubmitDebugUtilsMessageEXT

---

loader/debug_utils.c

If an ICD also supported the VK_EXT_debug_utils extension, then
any call to vkSubmitDebutUtilsMessageEXT would get duplicated.
Change-Id: Ica3224ee598a99a925ec9343b6618d4d8ba190d0

loader: Fix multiple SubmitDebugUtils callbacks

---

scripts/helper_file_generator.py

The 1.1.90 header introduced the use of "\textrm" in `vk.xml`, requiring
changes to `scripts/helper_file_generator.py`

scripts: Extend scope of LaTeX handling

---

loader/debug_utils.c

Strict clang build breaks w/o explicitly casting VK_OBJECT_TYPE_UNKNOWN
to VkDebugReportObjectTypeEXT.

loader: Add explicit cast

---

scripts/loader_genvk.py

Python 3.8 will remove time.clock() and the warnings suggest that
time.process_time() or time.perf_counter() should be used instead.
So, move the script to using time.process_time().
@lenny-lunarg, I'm not entirely sure this is exactly what you want, but I think it will work.  Please look it over.
Change-Id: I982da1560adec4aab49f42936334e520456647c1

loader: Fix python3 warning

---

loader/trampoline.c
scripts/loader_extension_generator.py

Some of the commands aren't needed in the loader, but this would
cause command chains to crash when they hit the NULL.
Also, the ICDs expect the commands to come through vkGetInstantProcAddr
not vkGetDeviceProcAddr.  So, we need to redirect them when generating
the ICD dispatch table because the device commands in the instance
extension exist in the device dispatch table but need to call into
the ICD using the instance queries.
Change-Id: I24cd0ea4f3e5058b1137881452df75bf1ff7487a

loader: Fix VK_EXT_debug_utils termination

---

loader/LoaderAndLayerInterface.md

Although a ICD is a layer too, but I think in this context, use "ICD" is better than "layer".

loader:LoaderAndLayerInterface.md: Use "ICD" instead of "layer" in library_path's description for "ICD Manifest File Format"

---

tests/layers/vk_layer_logging.h

The `VkDebugUtilsObjectNameInfoEXT` member of the
`VkDebugUtilsMessengerCallbackDataEXT` struct was turned const in Vulkan
header 1.1.95 and modifications were required for compilation

tests: Modify `vk_layer_longging.h` for hdr 1.1.95

---

loader/CMakeLists.txt

Otherwise compilation would fail (at least on Linux with GCC) if the `LDFLAGS` environment variable, or `CMAKE_EXE_LINKER_FLAGS`, are set to any value that isn't supported by `ld` for ASM, which means most C/C++ linker flags.
It's not a pretty hack, but I couldn't find a better fix. If an experience CMake user has a better idea, I'm interested :) (I tried to set `CMAKE_FLAGS -DCMAKE_EXE_LINKER_FLAGS=""` in the `try_compile` call [as per the docs](https://cmake.org/cmake/help/latest/command/try_compile.html), but to no avail.)
-----
Context on why this fix is needed: on Linux distros like Fedora or Mageia (I'm packaging Vulkan-Loader for the latter), we set predefined linker flags in `LDFLAGS` when calling CMake, to prevent underlinking and various other things. On Mageia for example, the …

CMake: Unset linker flags before testing ASM compilation

---

loader/loader.c

I'm seeing an issue on multi-GPU systems where the same ICD, or implicit layer DLL, are being loaded more than once. This causes the loader to enumerate duplicate physical devices since it adds together the physical devices exposed by each ICD.
The reason this happens is because on multi-GPU systems there is a DriverStore entry for each adapter. The loader scans all the DriverStore locations and appends each VulkanDriverName entry to its internal list of json files to process. On these systems the VulkanDriverName for each adapter is going to point to the same json file and ICD.
The solution is to simply discard duplicate json entries when building the list of json files to scan.

Discard duplicate json files scanned by the loader

---

tests/layers/CMakeLists.txt
tests/layers/VkLayer_test.def
tests/layers/json/VkLayer_meta_rev.json.in
tests/layers/test.cpp
tests/layers/wrap_objects.cpp
tests/loader_validation_tests.cpp

The test layers were not able to handle vkCreate/DestroyDevice properly. I fixed them and extended the test case. I also extended the test case to have the two test layers tested in both orders.

Expand layer test

---

scripts/known_good.json

This commit consists of reverting known-good files to 'v1.1.97' tags due to a spec bug introduced in the 1.1.99 header and a Vulkan-Hpp failure with the 1.1.100 header.
Note - I ran this through Gerrit and it passed.

build: Revert known-good to 1.1.97 header

---

loader/LoaderAndLayerInterface.md

Adding Vulkan Logo for consistency across Vulkan SDK documentation.
Adding creative commons license (because there was no license on the documentation)

docs: Add Vulkan Logo

---

loader/debug_utils.c

When creating debug callbacks or messengers, each of them is added to a
linked list from the terminator, with the handle provided by the ICD.
When enabling some validation layers, this handle is renamed as part of
the chain and the application gets a different one.
In the removal process, the application usually receives one of these
function pointers using vkGetInstanceProcAddr:
- debug_utils_DestroyDebugReportCallbackEXT
- debug_utils_DestroyDebugUtilsMessengerEXT
Those trigger the chain calls but then try to remove the callback or
messenger from the linked list using the application-level handle, which
is not found because it doesn't match the one from the ICD.
The linked list should be accessed from the destruction terminators,
when the handle has already been unwrapped by the layers. …

loader: Destroy debug callbacks/messengers properly

---

loader/loader.c
loader/loader.h

This PR updates the override mechanics so that the component list is no longer the absolute list of enabled layers. Instead, the override provides a list of force-enabled layers and a list of force-disabled layers. Other layers will be enabled or disabled according to the usual mechanics.
This PR (along with another change I will make to vkconfig very shortly) fixes #112.

Update override layer mechanics

---

loader/loader.c
loader/loader.h
scripts/common_codegen.py
scripts/dispatch_table_helper_generator.py
scripts/helper_file_generator.py
scripts/known_good.json
scripts/loader_extension_generator.py
scripts/loader_genvk.py

Changes:
- Integrate upstream script changes: We have to plumb-through the new
conventions object to continue using the makeCParamDecl utility function
- Add GGP to available platforms
- Add handling for extension dependencies: Previously, the codegen for
loader trampolines could not handle an extension command that depends on
more than one extension being present. This removes that limitation
- Add checks for device extensions: This adds a check for two functions
at device creation time:
* VK_KHR_device_group
* VK_EXT_full_screen_exclusive
The loader needs to know about these extensions for proper handling
of the vkGetDeviceGroupSurfacePresentModes2EXT terminator
Updated:
- `loader/loader.c`
- `loader/loader.h`
- `scripts/common_codegen.py`
- `scripts/dispatch_table_helper_generator.py` …

scripts: Update known-good for 1.1.106 header

---

loader/LoaderAndLayerInterface.md

DispatchTable struct now has it's own file.  Updated references to the correct file.

Update Dispatch Table update to actual location

---

.gn
.travis.yml
BUILD.gn
build-gn/DEPS
build-gn/secondary/build_overrides/build.gni
build-gn/secondary/build_overrides/vulkan_loader.gni
build-gn/update_deps.sh
scripts/loader_genvk.py

Add support for GN, Google's meta-build system for Ninja: https://gn.googlesource.com/gn/
- Pull GN build into the repo to ease update process for consumers of Vulkan-Loader who use GN.
- Add a non-blocking Travis CI job to monitor for breakages

Port GN build from ANGLE and add CI

---

CMakeLists.txt

This reverts PR https://github.com/KhronosGroup/Vulkan-Loader/pull/184 and its commit 
124130ec3b181b2bb8a3c1cb0abe6d7259f995e2 which was push prematurely.

Revert "build: Update cmake_minimum_required(VERSION 3.11.3)"

---

loader/extension_manual.c
scripts/known_good.json
scripts/loader_extension_generator.py

Additionally, moved platform guards to surround
`GetPhysicalDeviceSurfacePresentModes2EXT`
Platform guards did not surround opening and closing curly braces in
`loader_extension_generator.py`

build: Update known-good for 1.1.108 header

---

loader/loader.c
loader/trampoline.c

At the moment for `pLayerName==NULL` in `vkEnumerateDeviceExtensionProperties` the loader calls down the layer chain to allow layers to optionally filter the results before it gets to the application. However this doesn't happen for other values of `pLayerName` and the loader looks up the JSON directly to return the results.
This PR changes that so that it always calls down the layer chain and does the JSON lookup logic in the terminator instead. That way layers are always included in the enumeration process and have the ability to filter extensions provided by layers.

loader: Call through layers for device extensions

---

CMakeLists.txt
tests/CMakeLists.txt

This CL adds the enable_testing() cmake call and registers
vk_loader_validation_tests as a test in cmake.
This allows the test to be run when `ctest` is executed.

Set enable_testing in cmake file.

---

loader/loader.c

Fix small bug in instance creation when extension
(VK_KHR_surface) does not exist. Layer names were
traversed incorrectly.

Bug when searching for missing extension

---

CMakeLists.txt

This option allows specifying an addinal search path when configuring with
CMake, which will be consulted after all other search paths.
We need this in the NixOS distribution to make programs look in the location where drivers are available (`/run/opengl-driver/share`, not `/etc`), and to avoid having to set system-wide environment variables.

Add SYSTEM_SEARCH_PATH option for an additional search path.

---

loader/CMakeLists.txt

e.g. FreeBSD does not use an extra library for dynamic loading, everything is in libc.
CMake provides the [CMAKE_DL_LIBS](https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html) variable to handle this. Use it.

build: use CMAKE_DL_LIBS instead of -ldl

---

.appveyor.yml
BUILD.md
CMakeLists.txt
cmake/FindWDK.cmake
loader/CMakeLists.txt
loader/loader.c
loader/vk_loader_platform.h

This PR adds a new mechanism for finding drivers on Windows. The loader will now try to enumerate adapters via the `D3DKMTEnumAdapters2` method, and then find the driver's JSON manifest through `D3DKMTQueryAdapterInfo` method.
Because those queries are defined in the Windows Driver Kit (WDK), this PR also adds a loader dependency on the WDK (for Windows builds, only). The current mechanism for finding the mechanism requires a developer command prompt to find the WDK automatically. I didn't see any mechanism to find the WDK (or Windows SDK) location without a developer command prompt, but if @jjulianoatnv or someone else knows of a better mechanism, please let me know.

Find ICDs via WDK queries

---

loader/extension_manual.c

Loader is exposing VK_KHR_surface_protected_capabilities instance
extension support if one of the ICDs supports it.
An ICD, not supporting this extension, will not know about
VkSurfaceProtectedCapabilitiesKHR being passed as additional structure
to VkPhysicalDeviceSurfaceInfo2KHR in vulkan API
vkGetPhysicalDeviceSurfaceCapabilities2KHR().
Reset VkSurfaceProtectedCapabilitiesKHR.supportsProtected to false
always before calling vkGetPhysicalDeviceSurfaceCapabilities2KHR(). If
a particular ICD supports protected surfaces then it will set it
true.
An application will always receive either 1/0 in supportsProtected as
expected.
The issue got exposed through below CTS test failure on a Optimus windows
system with different ICDs versions, one supporting this extension and
another not supporting …

loader: Fix VK_KHR_surface_protected_capabilities

---

loader/vk_loader_platform.h

This should fix compilation with MinGW compiler on Windows platform.
**The problem:**
- Original code use `__declspec(thread)` declaration for Thread Local variables on Windows platform
- MinGW compiler on Windows platform doesn't support  `__declspec(thread)` declaration. In worst case incorrect binary could be generated (warning emitted but compilation complete with no actual TLS support)
**Solution:**
- Detect MinGW compiler via predefined `__MINGW32__` preprocessor definition and use GCC specific `__thread` declaration instead of `__declspec(thread)`
**Note:**
- It is possible to detect virtually _any_ GCC or GCC-compatible compiler via `__GNUC__` preprocessor definition but I have tested only with MinGW, so decided to keep it clear at the moment and check explicitly for MinGW only.

Fix for MinGW compiler

---

loader/loader.c
loader/vk_loader_platform.h

MinGW-w64 ships all Windows SDK headers as lowercase, which prevents
cross-compiling this code from Linux.
Windows filesystems are case insensitive so it should work fine with
lowercase includes.
For the reference, I used this simple regex to find occurrences: `"#include [\"<].*[A-Z].*[\">]"`.
On my distro (Mageia 7), the headers are located and named as follows:
```
mingw32-headers:/usr/i686-w64-mingw32/sys-root/mingw/include/cfgmgr32.h
mingw32-headers:/usr/i686-w64-mingw32/sys-root/mingw/include/devpkey.h
mingw32-headers:/usr/i686-w64-mingw32/sys-root/mingw/include/winsock2.h
mingw64-headers:/usr/x86_64-w64-mingw32/sys-root/mingw/include/cfgmgr32.h
mingw64-headers:/usr/x86_64-w64-mingw32/sys-root/mingw/include/devpkey.h
mingw64-headers:/usr/x86_64-w64-mingw32/sys-root/mingw/include/winso …
```

Make includes from Windows SDK lowercase for MinGW compat

---

CMakeLists.txt

Solves ISSUE #210.
The problem lies in the desynchronization of property definitions between the IF-statement and the ELSE-statement branches:
when the IF-statement branch is taken infact `VulkanHeaders_INCLUDE_DIRS` might not be defined at all, while in the ELSE-statement branch it's  the `find_package(VulkanHeaders)` that takes care of defining it.
Check the diff to clearly understand the context.
This Pull Request aims to ensure that the `VulkanHeaders_INCLUDE_DIRS` property is defined regardless of which branch is taken.

Always define VulkanHeaders_INCLUDE_DIRS property under OSX

---

loader/loader.c

The loader previously reported only major/minor version in `vkEnumerateInstanceVersion`. This makes it report the patch version as well.

Make instance version report patch version

---

BUILD.gn
build-gn/secondary/build_overrides/vulkan_loader.gni

No longer needed with updated ANGLE/Chromium integration.
See http://anglebug.com/3320 for more context.
@tobine can you forward this to the right folks?

Remove extra defines from GN build.

---

loader/CMakeLists.txt

The current Unix configuration for the asm_offset program uses the
CMAKE_CURRENT_BINARY_DIR as the path prefix. This breaks if the loaders
are used in a third_party repository. This CL removes the path prefixes
from the asm_offset command, which makes it the same as how Windows is
configured.

Change CMake paths for asm_offset.

---

loader/CMakeLists.txt
loader/loader.c

Previously, ICDs located through the HKLM registry would be loaded all the time. This changes the loader to iterate DXGI adapters and only loader the driver is there is an adapter that it corresponds to. This is aimed at solving one of the crashes discussed in #182.

Match ICDs against DXGI adapters

---

loader/CMakeLists.txt
loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/loader.h
loader/wsi.c
loader/wsi.h
scripts/known_good.json
scripts/loader_extension_generator.py

This PR adds support for the `VK_EXT_metal_surface` extension. This extension is treated like the other WSI extensions in that surface create is handled by the loader unless a driver implements Loader/ICD interface version 3 or later, and the driver also implements the `vkCreateMetalSurfaceKHR` extension. In that situation, the driver will handle surface creation.
Note that this PR depends on a change in Vulkan-Headers (KhronosGroup/Vulkan-Headers#80). I put the WIP label in this PR's title to reference the fact that this should not be merged until the corresponding headers PR is merged.
This fixes #207.

Add support for VK_EXT_metal_surface

---

loader/loader.c

This PR fixes a small problem that can be caused when layers create their own `VkDevices`.
The problem occurs when using a layer that works as follows:
```
VkResult LAYER_CreateDevice(....){
// ...
VkResult ret = nextCreateDevice(...);
// ...
VkResult retNew = layerCreateDevice(...);
// ...
}
```
Where `LAYER_CreateDevice` is the layer's `CreateDevice` function, `nextCreateDevice` is the next layer's `CreateDevice` and `layerCreateDevice` is the `PFN_vkLayerCreateDevice` callback. The problem is, that the call to `layerCreateDevice` will cause a segfault.
A possible workaround is to swap the `layerCreateDevice` and `nextCreateDevice` calls.
The individual steps that lead to the segfault are:
* The application calls `vkCreateDevice` …

loader: allow concurrent layer device creation

---

loader/loader.c

When the override layer is present, it would append any layers
found as if they were implicit. This change prevents non-implicit
layers from being included in loaderScanForImplicitLayers when
the override layer is active.
Change-Id: I95a7555d68e72f3d801bb27e6cd0792611e4596f

loader: Override doesn't include explicit layers

---

loader/CMakeLists.txt
loader/asm_test.S

The syntax used in the offset asm file is more complicated then what is
in the asm_test file. This CL extends the asm_test file slightly to
catch more compilers which are unable to process the offset assembly.
The version of clang I have available gets tripped up on the
`(PHYS_DEV_OFFSET_INST_DISPATCH + (PTR_SIZE * 4))`. This adds that
construct into the test assembly file.

loader: move asm_test.S into file; Make more complicated

---

loader/loader.c

This fixes #266.
Currently, the loader will not read most envars when an application is run with administrator or root privileges. This is done for security purposes, so that an application run with elevated permissions will not run a library that did not require elevated permissions to be installed. This PR changes that behavior so that only environment variables that are used to locate layers or drivers are disabled in that case. It allows using environment variables to enabled/disable layers that are already installed.

Only use secure getenv for finding layers

---

scripts/known_good.json

An updated version of `vulkan.hpp` was added to the Vulkan-Headers
repository to address an issue discovered when building `cubepp` in the
Vulkan-Tools repository
Change-Id: I347ee871b596a1ba29e4190862c6b8e9aeb629f9

build: Update known-good for 126 header patch

---

BUILD.gn

MacOS was missing some defines in BUILD.gn. This ensures the same
behavior from BUILD.gn as CMakeLists.txt

build: BUILD.gn fix for MacOS

---

loader/loader.c

I encountered this situation from a user report where somehow the `(Default)` registry value had been set to the empty string, instead of being completely unset, but this could happen if a string value was added as well as long as it's less than 4 characters (which means value_size gets truncated).
To repro you can import this .reg (after backing up your own key):
```reg
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers]
"C:\\Program Files\\GPUOpen\\Radeon GPU Analyzer\\layer\\VK_LAYER_RGA_pipeline_extraction_win32.json"=dword:00000000
"C:\\Program Files (x86)\\Steam\\SteamOverlayVulkanLayer64.json"=dword:00000000
"C:\\Program Files (x86)\\Steam\\SteamFossilizeVulkanLayer64.json"=dword:00000000
@=""
"C:\\Program …
```

Reset value_size after each call to RegEnumValue

---

BUILD.gn

Recent changes to this repository have broken ANGLE builds.
Ideally there would be tooling to catch errors like this.

Fix build errors on Windows GN

---

BUILD.gn
loader/CMakeLists.txt
loader/loader.c

ANGLE is failing to locate validation layers on some platforms because
it cannot access VK_ICD_FILENAMES and VK_LAYER_PATH. This ensures that
these variables will always be picked up.

Use unsafe file search for GN builds.

---

cmake/FindVulkanHeaders.cmake

The logic used to find the location of the Vulkan headers and
registry used simple find_path() calls with HINTS. Unfortunately,
this doesn't work when using a custom toolchain file that sets
CMAKE_FIND_ROOT_PATH_INCLUDE to ONLY, which can happen when
cross-compiling with a custom sysroot.
This patch changes the logic so that:
- If VULKAN_HEADERS_INSTALL_DIR is specified on the command-line,
or if it is set in the environment, or if VULKAN_SDK is set in
the environment, the corresponding paths will be searched for
the Vulkan headers and register, ignoring the
CMAKE_FIND_ROOT_PATH. This does not affect other parts of the
build.
- Otherwise, use a regular find_path() call which may be restricted
to the CMAKE_FIND_ROOT_PATH depending on previous configuration
settings.
This should be …

build: Fix Vulkan headers detection with CMake.

---

CMakeLists.txt
loader/CMakeLists.txt
loader/loader.c
loader/loader.h
loader/vk_loader_platform.h
tests/CMakeLists.txt

In the past, we allowed people to build a static copy of the loader and link their applications to that loader. We have increasingly hid that option from people as shipping a custom loader causes far more problems than it solves. In particular, new driver don't support old loaders so getting a driver update can drivers to be dropped or crash with no warning. We've already removed the static loader from SDK releases and we've stopped it from being built in this repo by default. In my opinion, it's time to remove this option altogether, since applications should really be using the loader that drivers provide.

Remove option to build a static loader on Windows

---

BUILD.gn

Fixes #288 
Reproduced the issue with the GN standalone build on windows. Fixed by linking with Cfgmgr32.lib [like the CMake build already does](https://github.com/KhronosGroup/Vulkan-Loader/blob/08d344208e60e0bb8c8fbe25b9b1f2bf63801e2f/loader/CMakeLists.txt#L210)

Add Cfgmgr32.lib to GN build

---

BUILD.gn

Copied the vulkan-1.def file to libvulkan.def and updated
GN build to use that file so that functions are correclty
exported for GetProcAddress() lookup.
Fixes #292

build:Add def file for Windows GN build

---

loader/generated/vk_loader_extensions.c
scripts/loader_extension_generator.py

Since the tooling info extension is implemented in the layers, the loader can't blindly call down into the driver. Doing so will result in a crash.
@mark-lunarg, if you test this and it works right for you, I'll go ahead and merge it.

Fix crash in tooling info terminator

---

cmake/FindVulkanHeaders.cmake

Fix incomplete VULKAN_REGISTRY_PATH_HINT for the case where
VULKAN_HEADERS_INSTALL_DIR is not specified.  The hint extracted the
DIRECTORY of the include dir (e.g. "/usr"), but missed the rest of the
expected path for finding vk.xml (e.g. "/usr/share/vulkan/registry").
Tested with CMake 3.16.0.
Fixes: 18664450a ("build: Fix Vulkan headers detection with CMake.")

build: Fix Vulkan registry detection

---

loader/vk_loader_platform.h

The loader_platform_basename function is not being used anywhere
else and was last modified 4 years ago. Considering the amount of
TODO comments and mentions to replace this, there doesn't seem
like a pressing need to keep it.
modified:   loader/vk_loader_platform.h
Change-Id: Icd7a4d1104889e0519081831fbfaaaa46690438c

loader: Remove loader_platform_basename dead code

---

loader/generated/vk_loader_extensions.c
scripts/loader_extension_generator.py

Loader treated GIPA calls for promoted device extensions as if they had terminators -- fixed codegen to get the correct table pointers. 
Fixes #309.
This issue severely affects 1.0/1.1 contexts created on 1.0/1.1 drivers while using a 1.2 loader, and calling `GetInstanceProcAddr()` on an extension API that was promoted to core in Vulkan 1.2 (all of the 1.1 promoted extensions were instance extensions, all of the 1.2 promoted extensions are device extensions).

loader: Fix handling of promoted device extensions

---

loader/loader.c
loader/vk_loader_platform.h

Several comments and one error message contained spelling mistakes.
This commit fixes it.
modified:   loader/loader.c
modified:   loader/vk_loader_platform.h
Change-Id: Ida86de154b1c1e80c1d251ce71246a06ab038e2d

Fix spelling mistakes

---

loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/loader.c
loader/loader.h
scripts/loader_extension_generator.py

This fixes #116.
This PR addresses the bug where the loader returns an invalid function pointers when an application calls `vkGetInstanceProcAddr` on the methods from the `VK_EXT_debug_utils` extension. Previously, the function pointers would run fine, but they would never call into the driver. This makes them call into the driver.
I'd be lying if I said I was 100% happy with this change. I wound up adding terminators for each function in this extension because doing so allowed me to use the existing instance functionality for choosing which driver to call into. But I do think this should do the job. This is a very special case because debug utils is an instance extension that contains device level functions.

Debug utils terms

---

loader/loader.c
loader/loader.h

The loader will now make sure to check if utf8 is null before
validating the string, preventing needless segfaults.
Change-Id: I48139e56719e3c518b85f2ded1ca0b682447413f

loader: add null check to loaderValidateLayers

---

loader/loader.c

This fixes #315. I decided to solve this by changing to a for-loop as was suggested in the issue. Now it should be safe to do the continue statement in the affected loop.

Fix buffer size updates in registry search

---

loader/loader.c

Previously, the standard-validation meta layer would always be added
to the list in loaderScanForLayers. This results in erroneous reporting
of its existance when querying for layers. This code is no longer
needed as the std-val meta layer is a proper layer which is included
in the sdk.
modified:   loader/loader.c
Change-Id: Ib8dacf82db95cd50b02cb51b1ae688d2873cbbee

loader: don't unconditionally add std-val meta layer

---

loader/loader.c

There is no `vkNegotiateLayerInterfaceVersion` as far as I know.
The correct name is `vkNegotiateLoaderLayerInterfaceVersion`.

loader: correct the name of vkNegotiateLayerInterfaceVersion

---

loader/trampoline.c

If the error is not dealt with, we'll end up calling dlclose(NULL)
later.

loader: Deal with failure loading implicit layer libraries.

---

CMakeLists.txt
external/CMakeLists.txt
external/README.md

This CL updates the CMake files to allow Vulkan-Headers to be in the
external folder. If the external/Vulkan-Headers folder is present the
scripts will use that version of the headers.

Allow Vulkan-Headers to be in external.

---

loader/LoaderAndLayerInterface.md

Part of the deprecation.  Feel free to upgrade/change the example.

Remove standard_val refs from LoaderAndLayerInterface doc

---

loader/loader.c

There are 3 issues fixed with this PR.
* Segfault if a layer.json contained an array as the top most element
* If any layer.json wasn't a valid layer.json file (ie didn't contain what the loader expects) it would subsequently ignore all valid layer.json's
* If any layer.json was an empty string, loader_get_json would treat that as an Out-Of-Memory and also fail to load any subsequent layers.

loader: Fix incorrect layer json bugs

---

.travis.yml

GN build failures will now cause the travis builds to fail.

travis: Remove GN build failures from 'allowed' list

---

loader/loader.c

Previously, the logic to get the pProperyCount in
terminator_EnumerateDeviceExtensionProperties when pProperties is null did
not check for duplicates. This meant that the subsequent call to
vkEnumerateDeviceExtensionProperties could write fewer extensions out as
duplicates aren't allowed. This commit should make it so that two calls
to vkEnumerateDeviceExtensionProperties return the same pPropertyCount's
Fixes #348 
Change-Id: I5d5513673322c02ed78dff5bb85605334beb5c6c

loader: check for duplicates in device extension count

---

loader/generated/vk_dispatch_table_helper.h
scripts/dispatch_table_helper_generator.py

Generated functions stubs had either a return type of void or
VkResult. Recent vulkan extensions had functions which returned
uint32_t, uint64_t, and VkDeviceAddress. The
dispatch_table_helper_generator didn't account for this and GCC would
complain about mismatching types. While likely not an issue, it did
create very noisy builds.
Modified files:
loader/generated/vk_dispatch_table_helper.h
scripts/dispatch_table_helper_generator.py
Change-Id: Iba229093461b75fd6ccd195cf60e200a22b8678f

scripts: stubs in dispatch table lacked matching return types

---

loader/LoaderAndLayerInterface.md

The right type name of InterceptFunctionName's first argument
is VkEnumerateInstanceExtensionPropertiesChan instead of the
VkEnumerateInstanceExtensionProperties.
Signed-off-by: Wang YanQing <udknight@gmail.com>

docs: Fix wrong type name in InterceptFunctionName prototype

---

loader/trampoline.c

This somehow went under the radar for the spelling mistakes commit
previously.
Change-Id: I377e145d949b9e659dc89dc3bb912931eb9daca4

loader: fix mispelling of implement

---

loader/gpa_helper.h

Allow vkGetInstanceProcAddr to resolve itself with no instance

---

CMakeLists.txt
loader/CMakeLists.txt

This fixes #343. This adds an option to build a static loader. The option comes with a note that this is not supported, per the conversation in the linked issue.

Enable building static loader on MacOS

---

loader/LoaderAndLayerInterface.md

No place mentions the way that we could use environment 
variable to enable explicit layers,  so I think it is better to move
the notice in brackets to the more proper place.

docs: Correct one minor discrepancy in "Implicit vs Explicit Layers"

---

cmake/FindVulkanHeaders.cmake

The Vulkan Headers detection script was coded to look for the Vulkan
registry in ${VULKAN_REGISTRY_PATH_HINT}/share/vulkan/registry. When
using the Vulkan-Headers repo the registry is located in just
${VULKAN_REGISTRY_PATH_HINT}/registry. This fix should allow both uses.
PTAL
@tobine fyi.

Fix not finding registry path in some cases.

---

loader/loader.c
tests/run_loader_tests.sh

Fixes issue #124
Windows platforms remove duplicate search paths due to registry keys
that are not device-specific but need to be searched. For the most
part, mac and linux do not need to do that. But if duplicate paths
crop up on a posix platform, it can cause the same device showing up
twice in the vkEnumeratePhysicalDevices results. There may be other
places it causes unexpected results as well.
VkPhysicalDeviceIDProperties.deviceUUID can be used later to tell that
the two entries are actually the same device and not a multi-GPU
system, but finding the root cause at that point is going to be very
difficult.

loader: Remove duplicate search paths on posix

---

loader/loader.c

Both the loader and VK_EXT_debug_utils define four levels of severity, map them one to one.
Signed-off-by: Kévin Petit <kpet@free.fr>

Log debug messages with verbose severity instead of info

---

CMakeLists.txt
cmake/FindVulkanHeaders.cmake
external/CMakeLists.txt

This fixes #361. 
A previous change allowed finding vulkan headers in the external directory. This change modifies that to use the find_package() interface through CMake. This allows versioning to work properly and also allows `VULKAN_HEADERS_INSTALL_DIR` to override what's in the external directory.

build: Find headers package from external dir

---

loader/loader.c
loader/loader.h
loader/trampoline.c

The ideal of having the loader be stateless causes serious slowdowns
in application startup due to the need to load then unload ICD's
repeatedly while calling vkEnumerateInstanceExtensionProperties. By pre-
loading the ICD's which are found using loader_icd_scan, the
unecessary reloading of ICD's is avoided.
The preloaded ICD's will be unloaded with vkDestroyInstance. This
allows subsequent vkEnumerateInstanceExtensionProperties calls to use the 
most recent ICD on the system, preventing issue where a new driver was
installed but an application couldn't use it unless they unloaded the loader
library completely.
modified:   loader/loader.c
modified:   loader/loader.h
modified:   loader/trampoline.c
Change-Id: Id169f94bea15e569b75c3a663b25444cc6c52c40

loader: Preload ICD's to speed up vkEnumerateInstanceExtensionProperties

---

loader/trampoline.c

The call to `loader_unload_preloaded_icds()` in vkDestroyInstance happens before the
loader_lock mutex was released, causing a deadlock due to the mutex not allowing
self re-entrant locking.
The fix is simply unload the ICDs after this lock was released.
Resolves #372 
Change-Id: I3f5774463b9872127893ed00183693dcf17a35d1

loader: Fix deadlock introduced by preloading ICDs

---

BUILD.gn

On Linux the standard name to use the Vulkan loader is libvulkan.so.1,
so we add a copy step to the GN build that copies libvulkan.so to
libvulkan.so.1.
Also ran `gn format` on BUILD.gn

BUILD.gn: Generate libvulkan.so.1 on Linux

---

loader/trampoline.c

This fixes #384. Without a null check when creating a queue, it becomes impossible to test for the case where the provided queue is null. Normally I would prefer to check the return code, but these functions are void return.

Check for null when creating a queue

---

scripts/loader_genvk.py

A modification to one line of code was missed when updating the loader
genvk file for the 1.2.140 header update and when the change was
incorporated it exposed the newly added `logDiag` function which can be
found in `reflib.py` in Vulkan-Docs. Instead of adding another script to
the Loader repo, `write` functionality was reinstated in
`loader_genvk.py`.

build: Fix `loader_genvk.py` error logging

---

loader/loader.c
loader/loader.h

Previously, if a layer called a pre-instance function
while being initialized (inside vkCreateInstance) a deadlock
would occur because the preload icd call used the same mutex.
Fixes #400 
Change-Id: I085ecfbcab26d746d77ca8466b4f63a13f6bea10

loader: Preload ICD use its own mutex

---

loader/CMakeLists.txt
loader/loader.c
loader/loader.h
loader/vk_loader_platform.h

An array of strings was added to the override layer to provide
per-application overrides. The loader will now look for an override profile
which contains an app_keys list item that matches the path & name of the 
currently running executable. Previous behavior with a global override still 
works as intended.
This changes is in conjunction with the VkConfig rewrite to allow for more
than one override profile to be enabled.
modified:   loader/loader.c
modified:   loader/loader.h
modified:   loader/vk_loader_platform.h
modified:   loader/CMakeLists.txt
Change-Id: I9ddbc98a098d48064110db6c29998eddb336fcda

loader: add per-application override layer settings

---

scripts/dispatch_table_helper_generator.py
scripts/helper_file_generator.py
scripts/loader_extension_generator.py

When calling in the vulkan header python generator the options have
changed in 1.2.142 which causes the options passed by the loader to be
off by one. This ends up setting the emitExtensions to the value of the
sortProcedure and eventually causes the script to fail.
This CL updates the loader to used named parameters for the generator so
that the addition of the genpath does not throw off the parameter
positioning.

Use named parameters for generator options.

---

loader/trampoline.c

This fixes #416. See that issue for the details.

loader: Fix crash in vkGetDeviceQueue2

---

CMakeLists.txt

When `-I loader` is put after system headers not marked by `-isystem` the build may fail e.g.,
```c
$ pkg install vulkan-validation-layers
$ cmake -B _build -G Ninja
$ cmake --build _build
FAILED: loader/CMakeFiles/vulkan.dir/loader.c.o
/usr/bin/cc -DAPI_NAME=\"Vulkan\" -DEXTRASYSCONFDIR=\"/etc\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/usr/local/etc\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -Dvulkan_EXPORTS -I/usr/local/include -I../loader -I../loader/generated -Iloader -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -fvisibility=hidden -Wpointer-arith …
```

Unbreak build when Vulkan-ValidationLayers is installed

---

loader/loader.c

The trampoline vkEnumerateDeviceExtensionProperties locked/unlocked the
loader mutex, but the terminator function also unlocked, causeing a double
free. Removing the locking in the terminator fixes the problem.
Fixes #386 
Change-Id: I714b243f3410a7fdc371b740def5ab962ae74a6f

loader: fix TSAN warning

---

loader/loader.c

vkEnumerateInstanceExtensionProperties was returning VK_ERROR_INITIALIZATION_FAILED
when a single malformed manifest file was found. This was due to the way
`loader_scan_icd` returns an error if it found an invalid ICD's but no valid ones.
Fixes #421 
Change-Id: I84b39774b766d20d607c990bddc921b1c2a4297a

loader: fix wrongly returned error code

---

BUILD.gn

GN recently added support for Apple frameworks to link, rather than
overloading the libs lists. This pulls .frameworks out of the libs
lists, so that GN can stop supporting .frameworks in libs in the
future.
Bug: chromium:1052560

Convert GN libs lists to frameworks

---

loader/vk_loader_platform.h

Some Vulkan implementations may rely on external libraries.
One example is mesa driver, that uses libLLVM.so. If user
application also links with LLVM, some clashes may take place.
This patch ensures that library's own symbols are looked up
before any other symbols in current process.

loader: Fix symbol lookup order

---

scripts/common_codegen.py

'directfb' : 'VK_USE_PLATFORM_DIRECTFB_EXT' was duplicated in scripts/common_codegen.py during merge.
Nicolas Caramelli

Remove duplicate key / value in scripts/common_codegen.py

---

loader/LoaderAndLayerInterface.md

This fixes #442.
This fixes some documentation that incorrectly showed passing a NULL instance when getting function pointers from vkGetInstanceProcAddr.

Pass instance handles when getting function pointers in documentation

---

loader/loader.c
loader/loader.h

This fixes #440. See that issue for motivation.
A couple of notes on this:
- The loader already logged a message when someone used standard validation incorrectly, but it was logged as a warning and it didn't stop the application from continuing.
- This change makes that warning into an error message and it uses a special error message that tells you to use khronos validation
- This change also will cause `vkCreateInstance` to fail with the error code `VK_ERROR_LAYER_NOT_PRESENT` when the old standard validation is used illegally.
- If the standard validation is actually present on a system (which would occur if an old copy of the layers is present) then no error will happen. This only happens when the standard validation layer is enabled and not found.
If people would verify that all …

Make invalid standard validation layer an error

---

loader/loader.c

Fixed crash in device enumeration when there are adapters which do not support Vulkan.
Fixed incorrect error code returned from device enumeration.
Necessary to fix dEQP test cases:
dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail
dEQP-VK.api.object_management.max_concurrent.device_group
dEQP-VK.compute.device_group.dispatch_base
dEQP-VK.device_group.afr_sys
dEQP-VK.device_group.afr
dEQP-VK.device_group.sfr_sys
Based on sdk-1.2.148 because I do not see adapter sorting code in master.

loader, critical fixes for SDK-1.2.148

---

loader/loader.c

Adds a missing NULL assignment. This problem surfaced when using the
Vulkan configurator.
Fixes #452
PTAL. @lenny-lunarg and @tobine fyi

Fix double delete in loaderScanForImplicitLayers.

---

README.md

The COPYRIGHT.txt file itself was removed in https://github.com/KhronosGroup/Vulkan-Loader/commit/d7452989ff0cfbaeaecfb63d8516cab63cf41bee.

docs: Remove mentions of COPYRIGHT.txt from the readme

---

loader/loader.c
tests/loader_validation_tests.cpp
tests/test_common.h

changes:
* loader/loader.c: cast dxgi_factory to void** type
* tests/loader_validation_tests.cpp: check if __STDC_FORMAT_MACROS is already defined
* tests/test_common.h: check if NOMINMAX is already defined
* tests/test_common.h: check _MSC_VER instead of WIN32 before pragma warning directive

fix some non-msvc compiler warnings

---

loader/trampoline.c

This fixes a bug where an unsuccessful allocation could cause the loader to store an invalid ICD. This invalid ICD caused a few problems, but the one we were seeing was a circular list of ICDs which caused an application to hang.

Fix invalid cleanup on allocation error

---

loader/loader.c

This prevents unused variable warnings/errors on non-Windows
platforms.
Fixes #459

Move variables into scope they are referenced within

---

BUILD.gn

These headers were detected as missing by an ANGLE tool. Adding them
should fix some edge cases with incremental builds.

GN: Add missing header dependencies.

---

loader/LoaderAndLayerInterface.md

The LoaderAndLayerInterface.md contained references to layers that
are no longer exist. This commit cleans that up.
Fixes #394 
Change-Id: I09a78513ba6f56cad6b6e9f2432242b86a291e93

docs: Remove mention of old layers

---

loader/loader.c

Loader will now fail vkCreateInstance with VK_ERROR_LAYER_NOT_PRESENT
if the layer's library failed to load. Previously, it would log the
error but continue, leading to false positives since it would return
VK_SUCCESS. No additional error reporting should be necessary since `loaderOpenLayerFile`
reports errors already.
Fixes #18
Change-Id: I00804b6f02cc6e927ac0219b4cb0c2361d6561fe

loader: Return error if layer loading failed

---

loader/loader.c

Previously the loader would return a different count in the call to
vkEnumeratePhysicalDeviceExtensionProperties if any implicit layers contained extensions
that a driver also happened to support, thus causing a duplicate entry to the count, but
was later resolved in the second call to that function. This commit de-duplicates the
extensions when getting the count, preventing such an issue from occuring.
Change-Id: I3b3c0b8871e412d26dda916ed1e1e3fe3299491e

loader: Make device extensions return same count

---

.travis.yml

Ubuntu bionic comes with cmake 3.10.2. We could get rid of the custom cmake installation step.

Update Linux distro used in Travis pipeline

---

loader/LoaderAndLayerInterface.md

Brief documentation that the override layer exists and the two special keys that it uses.
Change-Id: I7fab8f7ff25a7f3ffd00a88da82daeac69e4e83c

docs: Add info on override layer

---

loader/loader.c

This reverts commit 49648d8fb398ac7d3d8e159939de060b8e759ecf.
Many layers were relying on silently failing to allow 32/64 bit versions
to work on linux. A later commit will properly check for failing layers.

Revert "loader: Return error if layer loading failed"

---

loader/LoaderAndLayerInterface.md

When static linking was removed as a build option, the documentation
for it was not ammended. This commit changes the text to describe that
it used to be supported, is no longer supported, and why the feature
was removed.
Change-Id: I8da0c1c811be7e9dc5119c4c27c34a5cbb30edf8

docs: Update static linking info

---

BUILD.md
CMakeLists.txt

macOS is the only supported platform for a static loader.
Changes the build.md and CMakeList.txt to correctly specify
the option and warning message.
Change-Id: Iaf00e65e60ce5833516b7fe290eed7198436b48b

docs: Update build.md for static build changes

---

loader/loader.c

1) Fix a memory leak with sorted_array[].physical_devices when EnumerateAdapterPhysicalDevices  returns an error. This fixes a failure with the "dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail" Vulkan CTS test.
2) Fix an issue with vkEnumeratePhysicalDeviceGroups() when fpCreateDXGIFactory1() fails, which will happen with Windows versions before version 10.

Fix some issues when EnumerateAdapterPhysicalDevices is available

---

loader/loader.c

When custom allocator is used, and is requested to allocate
zero size allocation, it can return NULL, which is then
interpreted as VK_ERROR_OUT_OF_HOST_MEMORY.
When such allocator was used, override layer was not loaded.
fix #485

loader: Override layer load when custom allocator used.

---

loader/vulkan.pc.in

Fixes #489.
Supersedes #214.
Those `CMAKE_INSTALL_FULL_*` defines depend on `GNUInstallDirs`, which is included in `CMakeLists.txt`.

CMake: Fix libdir in pkg-config file, dehardcode includedir

---

loader/CMakeLists.txt

On MinGW from Linux this fails because cfgmgr32 is lowercase. This will still work on win32.

Fix vulkan link to cfgmgr32 on case-sensitive fs

---

BUILD.gn

This is the Linux way.  Previously, a copy step was added to copy
libvulkan.so to libvulkan.so.1.  However, that only runs if everything
is built and not when a specific target is built.
There is no need for libvulkan.so on Linux, so this change makes the
libvulkan target directly generate libvulkan.so.1 and removes the copy
step.

Generate libvulkan.so.1 on Linux instead of libvulkan.so

---

BUILD.gn

Chromium now uses VK_KHR_xcb_surface instead of VK_KHR_xlib_surface, so
it's able to use the gn build of Vulkan-Loader.

Reland "Generate libvulkan.so.1 on Linux instead of libvulkan.so"

---

loader/loader.c

The status message for the loader not searching environment
variables when running with elevated permissions didn't properly
check on Linux. This commit adds in proper guards to make sure the status
message only prints when running with elevated permissions.
Change-Id: I993bb08de21bb0e338852368c24fe615d0d1f9b9

loader: Properly check for elevated permissions

---

loader/loader.c

This fixes #488.
By using fread instead of fseek(file, 0, SEEK_END), this method should be more portable if we use an implementation in the future that doesn't support SEEK_END.

loader: Remove SEEK_END usage

---

loader/CMakeLists.txt

we want the dll to be named vulkan-1.dll and not libvulkan-1.dll
as it is the default on mingw (for drop-in replacement)

cmake: remove mingw lib prefix

---

loader/loader.c

fixes #533 
fread returns the count of values returned but was being ignored.
This commit makes sure to use that value when determining whether to
continue seeking to the end of the file.
Change-Id: Idb818cb3cda0cdde81aba1e5a4dd639c4814a923

loader: silence fread unused result

---

loader/loader.c

Linux can support multiple ABIs, but Vulkan Layer manifest does not
allow to specify different library paths, based on the ABI.
As a solution, for ICDs, we can simply create multiple manifests, one
per ABI, and the Loader will try them one by one until it finds the
library that is compatible with the executable class.
Instead, for Vulkan Layers, this method doesn't work because the Loader
will discard the manifests that have a duplicated layer name.
To add support for multiple ABIs to Vulkan Layers, and to make the
behavior similar to the ICDs, with this commit we remove the duplicated
layer name check.
Fixes: #155
---
Please check @smcv's comment for more information about this issue and the possible solutions https://github.com/KhronosGroup/Vulkan-Loader/issues/155#issuecomment-736630098 …

loader: Do not remove duplicated layers

---

loader/debug_utils.c

The messenger passed to vkDestroyDebugUtilsMessengerEXT can be NULL handle

Fix crash with NULL messenger

---

loader/CMakeLists.txt

The Android NDK doesn't provide a separate libpthread. Don't
explicitly link it in when builing for Android.
Signed-off-by: Kévin Petit <kevin.petit@arm.com>

loader: Fix AArch64 Android build

---

loader/loader.c
loader/trampoline.c

An application program that overrides malloc with an implementation that
returns NULL for a zero-sized allocation will cause some loader and
trampoline functions to incorrectly return VK_ERROR_OUT_OF_HOST_MEMORY
if there are no layers on the system. This patch prevents these errors
by also checking the layer count.
Fixes: https://github.com/KhronosGroup/Vulkan-Loader/issues/543

loader: Do not return OOM when layer count is 0

---

BUILD.gn
cmake/FindVulkanHeaders.cmake
loader/generated/vk_dispatch_table_helper.h
loader/generated/vk_layer_dispatch_table.h
loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/generated/vk_object_types.h
scripts/known_good.json

- Fix version parsing in FindVulkanHeaders.cmake (squashed from #565)
- Add VK_ENABLE_BETA_EXTENSIONS to GN build to pick up beta
VkObjectType values
Fixes #568

build: Update to header 1.2.176

---

build-qnx/Makefile
build-qnx/common.mk

Hi,
I forgot to force addition of Makefile in the build-qnx folder. Also enable Beta extensions by default, because generated files are using beta extensions.
Thanks.

Add missing root Makefile for build-qnx folder

---

loader/LoaderAndLayerInterface.md

The change to allow layers to intercept enumerateInstanceVersion happened in
2018 but the documentation was not updated to reflect that.
Fixes #564 
Change-Id: I238aec5c3606af4d39bff5c50bbe75e909cd3224

docs: Add enum-inst-version to pre-instance-functions documentation

---

loader/loader.c

This change only prevents the loader from warning on the new version.
Set as a draft as this may not be necessary depending on whether there will be a version bump or not.
Change-Id: If8c0aedb2e0052d5b6eb6f72fc4e7ad70b58d8a7

loader: Accept layer manifest version 1.2.0

---

loader/loader.c

`char *out;` produced an unused variable warning on apple platforms. Moving the variable declaration into the macro guarded section for linux solves the issue.

loader: Fix unused variable warning on Apple

---

scripts/update_deps.py

distutils.dir_util.mkpath will not re-create a directory if it has been removed with shutil.rmtree because it caches the filesystem under the hood. This was causing the clone retry to fail on the second iteration every time it got there.
Switch to using os.makedirs for equivalent functionality without the cache.
More context from Vulkan-Loader CI build 400:
```
Checking out Vulkan-Headers in C:\j\w3\32-bit\Release\Vulkan-Loader\Vulkan-ValidationLayers\external\Vulkan-Headers
Cloning Vulkan-Headers into C:\j\w3\32-bit\Release\Vulkan-Loader\Vulkan-ValidationLayers\external\Vulkan-Headers
*** Error ***
stderr contents:
b"Cloning into '.'...\nfatal: unable to access 'https://github.com/KhronosGroup/Vulkan-Headers.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 …
```

scripts: Switch from mkpath to makedirs

---

loader/trampoline.c

Hey @lenny-lunarg ... so I think we never actually solved #384 wrong (and it took my almost a year to finally remember to get back to this :disappointed: )
So looking at [InvalidGetDeviceQueue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6eaf131c0cd70cc6e7808a5358bf2c90ae4e171d/tests/vklayertests_others.cpp#L9938-L9947)
These tests still segfault. The issue is we did it wrong in #385 
but since then I see the code in `vkGetDeviceQueue2` is now
```
if (pQueue != NULL && *pQueue != NULL) {
```
Which I agree is the correct code, now this PR is just to add it to `vkGetDeviceQueue` which now having the `InvalidGetDeviceQueue` tests, I can verify that it doesn't crash with this PR
cc @ncesario-lunarg

Match null queue check for vkGetDeviceQueue

---

build-qnx/common.mk

This is a small fix for QNX build which adds external folder for Vulkan headers prior to the system headers.

QNX build: Use headers in the external folder prior to the system Vulkan headers

---

loader/loader.c

Loader previously emitted WARN level log messages for unknown
function names. This isn't wrong behavior and is mainly useful to
loader developers. Many layers and applications try to load all
function pointers they know about, so this code path is well
traveled.
Fixes #583 
Change-Id: Ia3e4b47eddb36bd02bcbab8452e5a96d03f75bd3

loader: Emit DEBUG for unknown function names

---

.github/workflows/build.yml
CMakeLists.txt
external/CMakeLists.txt
external/README.md
loader/CMakeLists.txt
loader/adapters.h
loader/loader.c
tests/CMakeLists.txt
tests/framework/CMakeLists.txt
tests/framework/README.md
tests/framework/framework_config.h.in
tests/framework/icd/CMakeLists.txt
tests/framework/icd/physical_device.h
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/framework/layer/CMakeLists.txt
tests/framework/layer/layer_util.h
tests/framework/shim/CMakeLists.txt
tests/framework/shim/linux_shim.cpp
tests/framework/shim/shim.h
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_regression_tests.cpp
tests/loader_testing_main.cpp
tests/loader_validation_tests.cpp
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

This PR is a draft: It is meant to gather feedback on the various designs, features, and limitations this test framework offers.
The test framework adds the necessary infrastructure to enable broad testing of the Vulkan-Loader codebase by allowing control over many of the system wide inputs that the loader uses, such as implicit layers and system wide driver lookup. Existing tests were inadequate due to their limited options for  controlling how the loader operates. 
Majority of changes are in `tests/framework` with some notable exceptions:
* loader/loader.c - Addition of crtdbg.h headers in debug mode to disable assert popups
* loader/CMakeLists.txt - Fix Debug mode using mixed CRT's, necessary to disable assert popups
* external/* - Added Detours library on Windows only when testing is …

Loader Test Framework

---

loader/loader.c

When the override layer or an implicit meta layer is detected, the loader will
go and find all of the explicit layers because the override/meta layer might
require them. During that process `loaderAddLayerProperties` is called. It was
accidentally called with `is_implicit = true`, which causes the loader to interpret the manifest files as if they were implicit, generating
many erroneous warnings.
Fixes #582
Change-Id: I8bc6bfa0d2a81159ebc33406e18ebf2099355768

loader: Silence erroneous implicit layer warning

---

BUILD.gn

This allows for projects like ANGLE that build the loader to prevent
conflicts with the system.
PTAL

GN: Support custom library name.

---

.github/workflows/build.yml
tests/CMakeLists.txt
tests/framework/icd/CMakeLists.txt
tests/framework/icd/export_definitions/test_icd_0.def
tests/framework/icd/export_definitions/test_icd_2.def
tests/framework/icd/export_definitions/test_icd_2_enum_adapter.def
tests/framework/icd/export_definitions/test_icd_2_gpdpa.def
tests/framework/icd/export_definitions/test_icd_gipa.def
tests/framework/icd/export_definitions/test_icd_negotiate_version.def
tests/framework/icd/physical_device.h
tests/framework/shim/shim.h
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_version_tests.cpp

In addition to enabling regressions test in Github Actions, this PR fixes several aspects of the test framework that either did not work or due to how github actions runs, failed there. 
Such as:
* 32 bit MSVC mangling names even with `extern "C"` - solution is using .def files for the TestICD DLL's.
* CI runs jobs with elevated permissions, thus disabling env-var's being used (known loader behavior for security reasons). Fix is to shim the elevated permissions check and force it to what the test requires.
* Missing _stdcalll in ShimEnumAdapters2
* Cleanup of copied files wasn't happening, nor were the folders being deleted. Leaving state around like this causes hard to track down bugs.
Additionally more error handling logic was added to various shim functionality as the current level …

Enable Windows CI regression tests

---

loader/loader.c
loader/trampoline.c

ReadDataFilesInRegistry would return VK_ERROR_INITIALIZATION_FAILED in several cases
which could cause the loader to short cirtuit and return that value when no drivers were
found in the registry. This is inconsistent with the later check of the size of the list
of manifest, which if it is 0 returns VK_ERROR_INCOMPATABLE_DRIVER. This commit changes
the instances of INIT_FAILED into INCOMPATABLE_DRIVER where relevant.
The addition of `AddManifestFile` (and change of `AddIfManifestFile`) are used in an upcoming PR which only needs the adding logic and not the json checking, thus I pulled out the common bits into a new function.

Change no driver result error

---

loader/LoaderAndLayerInterface.md

Documentation update to include layer manifest version 1.2.0 new features.
I am not sure if this is done the way to expect it. Let me know if there are errors, things you want differently or whatever.

Add layer manifest version 1.2.0 to history

---

.github/workflows/build.yml
tests/framework/CMakeLists.txt
tests/framework/shim/CMakeLists.txt
tests/framework/shim/shim.h
tests/framework/shim/unix_shim.cpp
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_util.cpp

Makes the necessary fixes to get regression tests running on MacOS. Since MacOS shares many many things with Linux, it didn't take a significant amount of effort.
There is also a commit to silence "C linkage errors" which appear harmless but where none the less annoying to see in the build output.

Enable macos ci regression tests

---

.github/workflows/build.yml
BUILD.md
tests/CMakeLists.txt
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_testing_main.cpp

* Update googletest to 1.10.0
* Add revamped Allocation tests (porting over original allocation tests to mock framework)
* Delete folders from previous run at startup - Mainly for developer builds which crash leaving stale state.

Test framework improvements

---

loader/CMakeLists.txt

#595 restores the default lib prefix for mingw (libvulkan-1.dll instead of vulkan-1.dl) and basically reverts #523
but it changes the import lib name (libvulkan.dll.a instead of libvulkan-1.dll.a) and  breaks cmake detection in FindVulkan
(find_library looks for libvulkan-1.dll.a under mingw)
now we go back to using the default cmake prefix which is equivalent to the #595 prefix prior to #523
without the broken import lib name
cc @Biswa96

Loader shared lib: back to default cmake prefix

---

loader/cJSON.c
loader/cJSON.h
loader/murmurhash.c

During SDK testing we identified that the runtime copyrights
were out-of-date.  The loader runtime includes two separate
MIT copyrights, each attributed to a pair of source files,
one initiated by Dave Gamble and one by joseph werle.
I examined these files to discover that the last LunarG change to
three out of the four was actually in 2017, not 2016.  This
date should be attributed to Khronos, Valve, and LunarG.
By updating the copyright notice in these files, we ensure that
the license registry remains up-to-date.
Note that no real content changed (which is why the copyrights are not
being updated to 2021).

copyrights: updated copyrights on MIT files

---

loader/trampoline.c

We've encountered situations where a layer removes physical devices
from the list which can cause issues on some systems if it's done
incorrectly.  For now, simply throw a warning if the loader determines
that a layer has removed devices.
NOTE: In the long-run, I think we should define a policy which states
that layers can re-order devices, but not add or remove.  If a layer
wants to add, it should become an ICD.

Report a warning if the number of GPUs doesn't match

---

loader/loader.rc

The date, specified in loader/loader.rc, was incorrectly set to 2020.

windows: update the loader copyright date

---

loader/loader.c

Win7 does not support D3DKMTEnumAdapters2, as such when the loader goes to
query it, it gets NULL back. Except, instead of just erroring out, it would
return VK_ERROR_OUT_OF_HOST_MEMORY. Problem was that change
73296a04678a07fc4fb1eef50cf4fe2778f059f8
starts checking for OOM, and finding one when running in Win7. This change
alters that behavior so that it doesn't report an OOM when one hasn't occurred.
Fixes #621

loader: Dont return OOM on function load failure

---

BUILD.gn

This flag was recently enabled by default in Chrome and ANGLE
and other projects inherit these build settings. Explicitly
dsiable this warning until it is enabled in the non-GN build.
Change-Id: I8f353f8abc3f7857481ff9cc774aff3618eaf35a
@charles-lunarg @MarkY-LunarG PTAL

loader: Disable -Wimplicit-fallthrough in GN.

---

loader/LoaderAndLayerInterface.md

The loader debug environment variable (VK_LOADER_DEBUG) is not inclusive
of higher importance messages, it is exclusive to the types specifically
enabled.

Fix loader debug documentation

---

loader/loader.c

Vulkan Loader loads the meta layer list and filters the ones that are not valid. During filter it deallocates the attributes of the loaded
meta layer but does not deallocate the associated extension list.

Deallocate the extension lists when deleting an item from layer list

---

tests/CMakeLists.txt
tests/framework/shim/shim.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_layer_tests.cpp

Create a new file which should host all the layer specific tests.
The first test in it only tests for a single case of invalid meta layers. But several fixes in various parts of the framework were needed to allow this test, thus proving its worth.
Also was able to reproduce issue #635 with this test, and showed that #636 successfully fixes it.

Add `loader_layer_tests.cpp`

---

loader/LoaderAndLayerInterface.md
loader/asm_offset.c
loader/extension_manual.c
loader/generated/vk_loader_extensions.c
loader/loader.c
loader/loader.h
loader/trampoline.c
loader/unknown_ext_chain.c
loader/unknown_ext_chain_masm.asm
loader/wsi.c
scripts/loader_extension_generator.py

This PR is actually 2 commits:
1) This first includes a change that "fixes" what enum is used for the loader_log messages.
2) The second change is focused on adding layer and implementation debug messages to the log.

Add layer debugging

---

loader/loader.c

It was looking for a specific output for the manifest file search string.
Re-add that string for now.

Fix environment test failure.

---

loader/adapters.h
loader/asm_offset.c
loader/cJSON.c
loader/cJSON.h
loader/debug_utils.c
loader/extension_manual.c
loader/extension_manual.h
loader/loader.c
loader/trampoline.c
loader/vk_loader_layer.h
loader/vk_loader_platform.h
loader/wsi.c
loader/wsi.h

Previously, clang-format was required for all new commits but the codebase
itself wasn't conformant. This commit formats the source files in the loader
folder.

loader: Reformated loader source code

---

.gitattributes
loader/CMakeLists.txt
loader/generated/loader_generated_header_version.cmake
scripts/generate_source.py
scripts/loader_generated_header_version_generator.py
scripts/loader_genvk.py

This changes the loader to always set the version to the one which was used when
generating the source files that are checked into the repo, instead of using the
version gotten from the Vulkan-Headers as it might be out of sync.
Fixes #141
Change-Id: Id0955ddfd10e35e0f358f5a77799d8baa4992b04

loader: Make use of a generated header version

---

loader/loader.c

To duplicate the bug, run the Vulkan CTS testcase:
```
./deqp-vk -n dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail
```
Root cause: when running the 64bit test, `loader_scanned_icd_add()` returns `VK_SUCCESS` for 32bit icd, but `icd_tramp_list.count` still equals to 0, then `num_good_icds` will be added to 1 in `loader_icd_scan()`, next is the 64bit icd, because the memory allocation is limited in the special case, exception happens after `loader_get_json()` but before `loader_scanned_icd_add()`, for example: memory allocation fails while printing "file_format_version" item, loader exists with `res = VK_SUCCESS` but `icd_tramp_list.count = 0`, which would cause unexpected error: `VK_ERROR_INCOMPATIBLE_DRIVER`
Fix: `loader_scanned_icd_add()` should return an error …

Fix Vulkan CTS testcase bug: "create_instance_device_intentional_alloc_fail"

---

loader/loader.c

When a dll/so of the wrong architecture is found, the loader would
return ERROR_INCOMPATIBLE_DRIVER from `loader_scanned_icd_add`.
Previously it would return VK_SUCCESS, but that caused the logic to
not skip over the ICD. This commit fixes the issue where the error
code would be propagated out of the function, which shouldn't happen
since there may be other drivers which do successfully load.

loader: Fix accidental error propagation

---

tests/framework/test_environment.cpp
tests/loader_alloc_callback_tests.cpp

This test tries to recreate an out of memory condition which causes
a binary of the wrong type to be confused with a valid binary, which
causes VK_ERROR_INCOMPATIBLE_DRIVER to be returned instead of VK_SUCCESS
(Or OOM if the case may be)

test: Add test for PR #639

---

loader/generated/vk_loader_extensions.h
scripts/loader_extension_generator.py

Seems to be a copy-paste error that makes the function declaration appear twice.

scripts: Remove loader_icd_init_entries duplicate

---

loader/LoaderAndLayerInterface.md
loader/loader.c
tests/framework/shim/shim.h
tests/run_loader_tests.sh

Issue #245 was created because we were not properly using the XDG
paths.
This change updates the path search order to be more correct.
While an argument could be made that the loader really should only
be looking in the DATA folders, we already are looking in the
CONFIG folders.  Therefore, just correct the order and also make
sure the proper _HOME variable for CONFIG and DATA is searched
first (but only in non-superuser mode).

Update XDG paths

---

loader/debug_utils.c
loader/loader.c
loader/trampoline.c
loader/wsi.c

This change allows the loader to know extensions enabled in the layers
as well as extensions enabled but handled by layers.
This should fix several issues where the enabled extensions is not
known soon enough for layers to use.

Fix loader not knowing about extensions enabled in layers

---

loader/loader.c
loader/loader.h
loader/trampoline.c

Before it was a mix of camelCase, PascalCase, and snake_case.
"Vulkan" functions, like terminator_GetPhysicalDeviceProperties, remain in camelCase.
This way it looks visually similar with the actual vulkan functions they correspond to.

loader: Make all loader functions use snake_case

---

loader/loader.c
loader/loader.h
tests/framework/test_util.cpp
tests/loader_layer_tests.cpp

Existing logic for freeing layers was scattered across loader.c. This PR moves it to a single function and adds a test for Override Meta Layers.
Fixes #671

Loader layer free logic cleanup

---

loader/allocation.c
loader/extension_manual.c
loader/loader.c
loader/wsi.c
tests/loader_alloc_callback_tests.cpp

Fixes include:
* Explicitly calling abort or assert instead of crashing when the loader intends to crash, documenting desired behavior
* Assert against `malloc`'s of size 0, as that is undefined behavior
* Remove redundant stores - several places where assignment was not doing anything
* Guard against passing `NULL` into `strcmp`
* Assert `instance != NULL` at the beginning of functions to remove multiple individual checks.

Many small fixes that clang-tidy detected

---

loader/CMakeLists.txt
loader/generated/loader_generated_header_version.cmake
scripts/loader_generated_header_version_generator.py

The previous commit that added a generated header version didn't apply
it to mac or linux specific versioning. This commit fixes that.

build: Use generated source everywhere

---

loader/loader.c

The function `loader_read_layer_json` does not modify the
disable_environment parameter that is passed in. It can safely be made
a variable local to the function.
Change-Id: I25ef3f3e5f008082dc9514be8f607d2acbf212a1

loader: Move disable_environment into function body

---

loader/loader.h
loader/loader_common.h

Not all structs declarations in loader.h were moved to loader_common.h. This
caused compilation errors due to not having the struct declaration available
in the headers it was needed.
Fixes #677

loader: Move struct decls to loader_common.h

---

BUILD.gn

This omission was causing the build dll to be missing version info.
PTAL

loader: Add loader.rc to Windows GN build

---

loader/cJSON.c

Prefixing to avoid conflicts in our downstream build with a duplicate function in the global namespace.

loader: Add cJSON prefix to update function

---

CMakeLists.txt

CMake 3.19 disallowed VS 2015 builds from selecting an SDK higher than
10.0.14393. Unfortunately, the loader requires SDK version 10.0.17763 or
higher. This commit uses the 3.19 capability to disable that limit set in
place by CMake so that we can use an SDK that suits our needs.

build: Fix using wrong Windows SDK for VS 2015

---

tests/loader_testing_main.cpp

Previously if any of the env-vars the loader looks for were set on the
system, the loader would find and use them, leading to highly confusing
logs. Removing them preemptively at tests start make this a non-issue.
Fixes #695

test: Isolate Env-Vars from test framework

---

loader/get_environment.c
loader/loader.c
tests/loader_regression_tests.cpp

Move the include of `loader_cmake_config.h` to be in the appropriate file, get_environment.c.
This header include was needed for `secure_getenv`/`__secure_getenv` but mistakenly not moved over.

Use CMake to define SECURE_GETENV variables

---

BUILD.md
CMakeLists.txt
loader/CMakeLists.txt

This CMake option controls the information put in the loader.rc file,
specifically the "Dev Build" string in the version info.

build: Add RELEASE_BUILD option for Windows SDK builds

---

loader/loader.c

This header should only be included on windows platforms, since non-windows platforms
may not know that the header should be present (which is the case for GN builds).
Fixes #704

loader: Only include loader_windows.h on windows

---

BUILD.md
loader/CMakeLists.txt
loader/loader.rc

This allows gn build to use the most recently generated loader.rc file
without generating it themselves.
fixes #704

build: Checkin loader.rc

---

loader/trampoline.c
tests/CMakeLists.txt
tests/loader_get_proc_addr_tests.cpp

`vkGetInstanceProcAddr` should only return the pre-instance, aka global
functions, when the VkInstance handle is NULL. This brings the desktop
vulkan loader into alignment on the spec and with the android loader. See:
https://github.com/KhronosGroup/Vulkan-Docs/issues/1605
This repo previously did follow the rule, but was changed in the
1.0.42 header version timeframe for unknown reasons.
Fixes #692

Only return pre-instance functions when instance is NULL

---

docs/LoaderApplicationInterface.md
docs/LoaderInterfaceArchitecture.md
docs/LoaderLayerInterface.md

Add a section warning about possible issues with bundling the
Khronos loader with an application/engine.
Also, rename "desktop loader" to "Khronos loader" since it is now
used for more than the original desktop targets.

Add bundling section and rename "desktop loader"

---

tests/framework/icd/test_icd.cpp
tests/framework/layer/layer_util.h
tests/framework/shim/shim.h
tests/framework/shim/windows_shim.cpp
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_regression_tests.cpp
tests/loader_threading_tests.cpp
tests/loader_version_tests.cpp

Various C string handling functions are considered unsafe. Best to use
proper alternatives.
Warnings/fixes include:
* strcpy/strncpy/wstrcpy
* Dropping static on inline functions
* Use localtime_s
* Name shadowing
* Use wcstombs_s

test: Fix compiler warnings in MSVC

---

.github/workflows/build.yml
BUILD.md
CMakeLists.txt
scripts/known_good.json

Gcc 11.2 build was failing to build with the GoogleTest version
that was being built.  So bump to next version of GoogleTest with
fixes (GoogleTest release-1.11.0), but that also required changing
the build directory to build GoogleTest in so update our Makefiles
to build in the new folder as well.

Fix GCC 11.2 build

---

tests/CMakeLists.txt
tests/framework/icd/physical_device.h
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/framework/test_util.h
tests/loader_unknown_ext_tests.cpp

Requires adding support in the ICD for unknown instance and physical device
functions separately.

Add test for unknown physical device functions

---

loader/extension_manual.c
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/loader_regression_tests.cpp

Add support for vkGetPhysicalDeviceToolProperties to call into the driver if the entrypoint is exposed.
Added a basic test to ensure the trampoline/terminator works.
Fixed #733

Make GetPhysDevToolProps call into drivers

---

loader/extension_manual.c
loader/generated/vk_dispatch_table_helper.h
loader/generated/vk_layer_dispatch_table.h
loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/loader.c
loader/loader.h
loader/loader_common.h
loader/trampoline.c
loader/vulkan-1.def
loader/wsi.c
scripts/dispatch_table_helper_generator.py
scripts/helper_file_generator.py
scripts/loader_extension_generator.py
tests/CMakeLists.txt
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_handle_validation_tests.cpp

Validate the Vulkan dispatchable handles (VkInstance, VkPhysicalDevice, etc) for
any trampoline functions the loader uses to query the dispatch table from.
This is so we can at least report errors before something bad happens.
Fixes GH Issue #64.

Update loader to include handle validation

---

loader/trampoline.c

Some tests were failing in the validation layer tests because it expected
the validation layers to catch certain issues and return specific messages.
The loader had been modified to include catching those tests and failing
early, but this change undoes those checks as it wasn't really part
of handle validation.

Fix validation_layer_test failures from handle validation change

---

loader/vulkan.pc.in

- pkg-config variable ${prefix} is required for adjusting sysroot
Signed-off-by: Joel Winarske <joel.winarske@gmail.com>

vulkan.pc cross-compile fix

---

tests/loader_handle_validation_tests.cpp

Instances were being created but not destroyed. Switch all tests to using
the InstWrapper to automate this cleanup.

Fix memory leaks in Handle Validation Tests

---

loader/CMakeLists.txt

The readlink function required _GNU_SOURCE to be a compiler definition but
wasn't added since it was in a different executable than the main vulkan
loader. Adding it to the asm_offset target fixes the error.

Fix readlink error in asm_offset on linux

---

.github/workflows/build.yml

The Windows-2016 environment is being removed March 15 2022. In preparation
of this, the loader will only use windows-latest and remove the workarounds
that were in place to run on the Windows-2016 environment.
Additionally, redundant manual downloading of detours was removed.

Use windows-latest in github actions

---

tests/framework/CMakeLists.txt
tests/framework/test_util.cpp

Need to use target_compile_definitions instead of target_compile_options.
Also appears that generator expressions do not play nicely, so best to revert
to classic if-else chains.

Fix per-platform defines in test framework not showing up

---

loader/debug_utils.c
loader/trampoline.c
loader/wsi.c
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/framework/layer/wrap_objects.cpp
tests/framework/test_util.h
tests/loader_handle_validation_tests.cpp

Some handle wrapping use with debug utils exposed a bug in the loader
introduced during the handle validation changes.

Fix handle validation crash when using debug utils

---

tests/framework/shim/shim.h
tests/framework/shim/shim_common.cpp
tests/framework/test_environment.cpp
tests/loader_testing_main.cpp

Previously, Death tests would unknowningly create multiple registry overrides
and subsequently leak them when the death test dies. This is fixed by only
calling override once in main and setting an environment variable to prevent
subprocesses (death tests) from calling override again.
This change also moves the override setup from the shim setup to main, since
it had no depencies on the shim library itself.

Fix test framework leaking registry entries

---

loader/loader.c
tests/loader_regression_tests.cpp

Passing in a VkInstanceCreateInfo where the layer count or extension count was non zero but
their respective pointers were NULL caused a nullptr dereference. The loader now checks for
this condition in the layer and instance extension validation functions and returns
VK_ERROR_LAYER|EXTENSION_NOT_PRESENT.

Fix crash from Null instance layer or extension ptr

---

tests/framework/icd/physical_device.h
tests/framework/icd/test_icd.h
tests/framework/layer/layer_util.h
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/framework/shim/shim_common.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_get_proc_addr_tests.cpp
tests/loader_handle_validation_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_testing_main.cpp
tests/loader_threading_tests.cpp
tests/loader_unknown_ext_tests.cpp
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

Added builders to a majority of the test framework, fixes bugs causing inconsistent results due to old tests not being cleaned up properly, and fixed InstWrapper not asserting if the result didn't match.

Improve test framework

---

loader/unknown_ext_chain_gas_aarch64.S

This is my attempt at fixing #773 I've run it past someone on irc, who said it seems fine, but I'd appreciate someone else validating it as well.

loader/aarch64: attempt to avoid text relocations in the unknown code

---

loader/terminator.c
tests/framework/icd/test_icd.cpp
tests/loader_phys_dev_inst_ext_tests.cpp

The functions added from VK_KHR_get_physical_device_properties2 were made core, but a
recent loader change meant that an application which was trying to use the extension may
use the fallback version (which ignores the pNext chain) by accident. This breaks existing
applications and thus needs to be rectified. This commit makes it so that if the core
GetPhysicalDeviceXXX functions aren't available and the extension is supported & enabled,
the extension version is used instead.
Fixes #785

Fallback to 2KHR terminators if available

---

BUILD.gn
docs/LoaderApplicationInterface.md
docs/LoaderInterfaceArchitecture.md
loader/CMakeLists.txt
loader/loader.c
loader/loader_common.h
loader/loader_linux.c
loader/loader_linux.h
tests/framework/icd/physical_device.h
tests/framework/icd/test_icd.cpp
tests/loader_handle_validation_tests.cpp
tests/loader_regression_tests.cpp

The loader ICD ordering could be random on Linux based on using readdir
to find ICD manifest files.  This can result in random behaviors as
applications that select only the first device can switch which device is
used.  To resolve this, we now sort based on device type and then
internally to the types based on PCI bus information.
This also introduces a VK_LOADER_DEFAULT_DEVICE environment variable
that can be used to force a specific PCI device.  This environment variable
is actually a duplicate of the MESA_VK_DEVICE_SELECT variable, which is
also looked for if the loader environment variable is not found.
Note, that at least one ICD must support it for the extension to be used at all.
So we only do the sorting if one ICD supports it.
Fixes part of #657

Consistent loader device ordering

---

loader/loader.c
tests/loader_layer_tests.cpp

Fixed several bugs and added 4 tests.
Bugs:
* Layers not in the active meta layer would be removed erroneously, due to very faulty logic in that function. Was cleaned up.
* Logging messages for incorrect meta layers were dropped during pre-instance functions
* If an implicit layer was added by the application manually, this created duplicates in the activated_layer_list
* Layer manifest version check was incorrect (wasn't updated for the newer 1.2 manifest version) - only affected whether a log message was emitted.
Tests:
* OlderMetaLayerWithNewerInstanceVersion - Checks for interaction between app's
instance version and the meta layer version
* NewerComponentLayerInMetaLayer - When a component layer has an API version
newer than the meta layer, the meta layer is disabled.
* …

Small revision of layer loading logic

---

loader/murmurhash.c

In Vulkan loader `GetProcAddr` handlers, for functions that are not specified in the Vulkan registry, the loader will try loading the name from ICDs or layers, and store the function entry into a hashtable. The hashtable uses `murmurhash()` function to hash Vulkan function names.
`murmurhash` handles data as 4-byte chunks and read one chunk at a time; and it simply converts `uint8_t` pointers to `uint32_t` pointers while loading data. However, the address of function name might not be 32-bit aligned and this will cause an undefined behavior in C99 / C11.
This change fixes the `murmurhash()` behavior so that it only does pointer type casting when the memory address is 32-bit aligned, otherwise it will load data bytewise. Note that we also handle different endianness in `fetch_four_bytes`, …

murmurhash: Fix an undefined behavior when hashing function names

---

tests/README.md
tests/framework/test_util.cpp

The environment variable VK_LOADER_TEST_LOADER_PATH allows running of tests
using a different binary than the one built by the repo. This is extremely
useful for checking that a test exercises a bugfix, by quickly allowing the
running of the same test on the current 'fixed' loader and an older 'broken'
loader.

Add VK_LOADER_TEST_LOADER_PATH env-var for tests

---

loader/loader.c
loader/trampoline.c

Policy statements are introduced but there are many cases where they will be emitting an error which some apps may confuse as being more important than in actuality.

Downgrade all policy messages from ERROR to WARN

---

loader/loader_linux.c

The loader assumed if Vulkan 1.1 is supported, then the PCI bus extension
must automatically be supported.  This was a mistake as that extension is
not part of core.

Fix issue #802

---

loader/loader.c

VK_KHR_get_physical_device_properties2 is added to an extension list on Linux targets, but the index used for setting the extension string in that list is wrong, leaving a NULL pointer where the extension name should be.

Fix writing to filtered extension list

---

docs/LoaderLayerInterface.md
loader/loader.c
tests/README.md
tests/framework/icd/test_icd.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_layer_tests.cpp
tests/loader_regression_tests.cpp

Loader changes include:
* The Loader makes sure all component layers in a meta layer are found. It would then do this check
immediately afterwards. This is redundant and can be removed.
* The loader_read_layer_json function wasn't decrementing the count of layers in the
list if it failed to load, leading to inconsistent results. Several places were removing layers in a layer list
manually when the functions loader_remove_layer_in_list exists. They also weren't modifying their loop counters
when it was necessary.
Small cleanup of FolderManager code.
Add tests for:
ExplicitMetaLayer - meta layer found in explicit paths
MetaLayerNameInComponentLayers - meta layer contains itself
MetaLayerWhichAddsmetaLayer - when a meta layer enables another meta layer
InstanceExtensionInComponentLayer - …

Add more layer tests and fix layer removal logic bugs

---

loader/loader_common.h
loader/wsi.c
loader/wsi.h

This PR implements the required boilerplate code to support the WSI extension VK_NN_vi_surface in loader_common.h, wsi.h, and wsi.c.

VK_NN_vi_surface WSI implementation

---

loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
scripts/loader_extension_generator.py

This PR adds the WSI extension VK_NN_vi_surface to the WSI_EXT_NAMES array in loader_extension_generator.py so that vk_loader_extensions.c/.h are no longer generated with incorrect code for this extension.

Add VK_NN_vi_surface to WSI extension names array

---

tests/loader_regression_tests.cpp

Add a test to make sure that the physical device handles don't change
between calls to vkEnumeratePhysicalDevices

Test EnumPhysDev to make sure handles don't change

---

loader/loader.c
loader/loader_common.h
loader/terminator.c
loader/trampoline.c
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/framework/layer/layer_util.h
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_layer_tests.cpp
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

The 1.2.175 header release saw the addition of API Variants. For the purposes 
of the loader, this should always be set to 0, for applications, layers and drivers.
The loader will warn an application if the variant of the apiVersion provided in VkApplicationInfo
is non zero. It will also skip over any ICD's found which have a non-zero variant version. And
any implicit layers found which do not have a zero for their variant will be not be loaded.
Fixes #799

Handle Vulkan variant's correctly

---

loader/loader.c

Mistakenly used DRIVER instead of LAYER logging level.

Fix warning for using wrong variant layers

---

tests/framework/layer/wrap_objects.cpp
tests/loader_layer_tests.cpp

We had tests that verified that instance and device extensions defined
in a layer had the non-null pointers returned from the corresponding
vkGetXXXProcAddr functions, but we weren't verifying that the functions
actually got called.

Add tests to validate layer extensions

---

loader/loader.c

If any ICD failed to enumerate device groups here, we would fail the call entirely, which means a broken driver for device A could prevent you from using device B. Just skip over the failing ICD instead.

loader: Try to handle ICD failure in vkEnumeratePhysicalDevices

---

loader/loader.c

Seems to have been a copy paste error that meant the group's icd_term was assigned
to the incorrect group.

Fix incorrect indexing of local_phys_dev_groups

---

tests/loader_get_proc_addr_tests.cpp
tests/loader_layer_tests.cpp

Verify that using vkGetInstanceProcAddr to get an entrypoint to a device
extension works when the extension is enabled, and crashes when the
extension isn't enabled.
Also, update a copyright notice date for my last commit.

Verify GIPA on device extensions

---

loader/trampoline.c

We discovered a crash in a layer (https://github.com/LunarG/gfxreconstruct/issues/642), and then in debugging discovered the layer's EnumeratePhysicalDeviceGroups was being called in the two-call idiom from `setupLoaderTrampPhysDevGroups` in the loader with two different VkInstance values.  I think the instance parameter to the second call to `fpEnumeratePhysicalDeviceGroups` is supposed to be `inst->instance`, otherwise the layer is getting the loader's instance wrapper.

Use the correct instance in setupLoaderTrampPhysDevGroups fixing a crash in a layer

---

loader/gpa_helper.c
loader/trampoline.c
tests/loader_get_proc_addr_tests.cpp

There was a regression with 1.3 that meant vkGetInstanceProcAddr wouldn't be
able to query itself if instance was set for 1.3. This commit makes it possible
to query for vkGetInstanceProcAddr with itself no matter the value of instance.
@zaiste-linganer Can you review and make sure it works as you expect?

Make vkGetInstanceProcAddr able to get itself

---

loader/loader.c

While the DEBUG level of logging is meant for verbose output, the actual extensions
enumerated rarely are useful for the purposes of debugging the loaders behavior.
With this in mind, the loader will now no longer print all the extensions found.

Remove Instance and Device extension logging

---

loader/extension_manual.c
loader/generated/vk_layer_dispatch_table.h
loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/log.c
loader/log.h
loader/trampoline.c
loader/wsi.c
scripts/loader_extension_generator.py
tests/CMakeLists.txt
tests/loader_debug_ext_tests.cpp

Add tests to validate loader handling of debug report and debug utils messengers.  Also updates all loader VUID logging output to go to not only the GENERAL message path but also the VALIDATION message path.

Add debug extension tests

---

loader/loader.c
tests/loader_regression_tests.cpp

Previously the logic of loader_add_device_extensions could return an error from
enumerating device extensions. This was because the code would return immediately
if either an error was returned from the driver or the count was zero. Now the
logic will return an error only if the driver returned an error. Zero device
extensions won't be treated as an error and will simply return VK_SUCCESS.

Loader handle zero phys devs & add tests for it

---

loader/loader.c

Produced spurious warnings for versions that are correct.

MetaLayer version checking had paren in wrong place

---

docs/LoaderLayerInterface.md
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/loader_layer_tests.cpp
tests/loader_regression_tests.cpp

If a meta layer which contains `override_paths` is active, all of the paths in
VK_LAYER_PATH are ignored when searchign for explicit layers. This may be changed
changed in the future but for now is better tested and documented.

Clarify behavior of override_paths + VK_LAYER_PATH

---

loader/loader.c
tests/framework/layer/export_definitions/test_layer_1.def
tests/framework/layer/export_definitions/test_layer_2.def
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_layer_tests.cpp

Add tests to verify that the 3 pre-instance functions are properly
intercepted by the layer when everything is well-defined.
Also include two fixes:
1) Disable environment variable value of 0 should be treated the same as not present
2) The vkEnumerateInstanceVersion override path was broken, missing a NULL check

Test layer pre-instance functions

---

tests/framework/test_environment.h
tests/loader_layer_tests.cpp
tests/loader_version_tests.cpp

Since device layers are pretty much ignored, make sure that they don't
change any behavior.
Also add a few "load" entrypoint helper routines based on what was already
done elsewhere in the test system.

Add a few device layer tests

---

loader/loader.c

Add debug messages to the loader so we can identify when an unknown
physical device extension's entrypoints are queried.

Add debug messages for unknown physical device extensions

---

docs/LoaderDriverInterface.md

The language was not normative and also made clearer.

Fix vk_icdGetPhysicalDeviceProcAddr docs

---

tests/loader_regression_tests.cpp

Cleans up the loader_regression_tests compiler warnings while were at it.

Add consecutive create tests

---

loader/loader.c
tests/framework/shim/CMakeLists.txt
tests/framework/shim/unix_shim.cpp
tests/loader_regression_tests.cpp

Angle drops the security enforcement of the loader on environment
variables and the additional "is_high_integrity" checks on my
previous loader change caused failures in the Angle run.
Revert the high-integrity checks and update the layer test to
work properly.

Resolve Angle failure because it works around secure_getenv

---

loader/wsi.c

Was searching `wayland` in loader and noticed 2 odd spots in my grep results... trivial QoL fix

loader: Fix wayland copy paste error

---

docs/LoaderDriverInterface.md
docs/LoaderLayerInterface.md
loader/loader.c

Modify the loader to only use VK_ADD_DRIVER_FILES if
VK_DRIVER_FILES or VK_ICD_FILENAMES is not used.
This could have caused weird issues with systems where VK_DRIVER_FILES
was used to force drivers in a specific order/location for testing.
Fixes #871

Modify loader VK_ADD_DRIVER_FILES behavior

---

loader/loader.c
loader/wsi.c
tests/framework/icd/test_icd.cpp
tests/loader_phys_dev_inst_ext_tests.cpp
tests/loader_wsi_tests.cpp

The physical device terminator was missing the ICD index in the
non-sorted path.  This caused crashes in Angle before it was realized
that the sorting code was unintentionally disabled in that build
path.
Also, add tests to catch this case in the future.
Fixes #863 for non-sorting paths

Fix non-sorted surface indexing

---

docs/LoaderDriverInterface.md
loader/loader.c

The cause for this policy was due to dynamic linker behavior which could have
resulted in the wrong symbols being used. However, this didn't occur in
practical usage of the dynamic linker. Also drivers exporting Vulkan
entrypoints was a useful behavior to enable testing and more flexible usage
that this policy actively interfered with.
Resolves #797

Remove LDP_DRIVER_6

---

loader/loader.c
loader/loader_linux.c
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/loader_regression_tests.cpp

The sorting algorithm needed to take into account both the application
API version as well as the driver API version.
This required additional changes to the sorting algorithm for the fallback
since even if the instance supports the extension or Vulkan 1.1, the individual
drivers may not.
Also, add supporting tests which would catch these cases in the future.
In the process, I realized we assumed that the presence of an extension in the
test_icd indicated "enablement" which was incorrect.  So I separated out
that into a set of "enabled instance extensions"

Fix #888 crash in Lutris with Linux sorting

---

CMakeLists.txt
loader/cJSON.c
loader/extension_manual.c
loader/generated/vk_dispatch_table_helper.h
loader/generated/vk_loader_extensions.h
loader/loader.c
loader/loader_common.h
loader/loader_windows.c
loader/vk_loader_platform.h
loader/wsi.c
scripts/dispatch_table_helper_generator.py
scripts/loader_extension_generator.py
tests/framework/CMakeLists.txt
tests/framework/icd/test_icd.cpp
tests/framework/layer/wrap_objects.cpp
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_envvar_tests.cpp
tests/loader_handle_validation_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_phys_dev_inst_ext_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_threading_tests.cpp
tests/loader_unknown_ext_tests.cpp
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

Test fixturing (TEST_F) is useful when there is a lot of common code that needs
to be run for a suite of tests. However, the FrameworkEnvironment encapsulates
almost all of the setup work all tests needs, and so doesn't need to be in a
fixture. Making the add_icd call inside the tests makes it clear which binary
is being used.
This PR also uses the corrent signed/unsigned constants in tests, as was
warned by compilers when enhanced warnings were enabled (/W4 in msvc).
Refactor the CMakeLists.txt to allow for compiling with clang-cl. This required
figuring out that -Wall -Wextra mangle the set of warnings used. The solution
is to use /W4 instead when compiling with clang-cl on Windows.
Fixes #896

Enable w4 warnings and make clang-cl compiler possible

---

CMakeLists.txt

This adds a choice for the user whether to treat warnings as errors.
The remaining compiler options are moved where it was before.

cmake: Add ENABLE_WERROR option

---

loader/loader.c
loader/loader_linux.c
loader/loader_linux.h
loader/loader_windows.c
loader/loader_windows.h
tests/framework/icd/test_icd.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_debug_ext_tests.cpp
tests/loader_envvar_tests.cpp
tests/loader_get_proc_addr_tests.cpp
tests/loader_handle_validation_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_phys_dev_inst_ext_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_threading_tests.cpp
tests/loader_unknown_ext_tests.cpp
tests/loader_version_tests.cpp

The previous logic would cause any non-sorted physical devices to be missed
when aggregating the final list. This caused crashes due to the phys_dev
value not being initialized. The fix is to make sure both sorted and non
sorted physical devices are included in the final output of
setup_loader_term_phys_devs().
This PR should replace #868

Fix missed Physical Devices in Windows + test improvements

---

loader/unknown_ext_chain_gas_x86.S
loader/wsi.c

Building and running the regression tests reveals that the 32 bit unknown function
handling on linux is broken. It required the same fixes as did windows 32 bit, since
the code is almost identical.
wsi.c also would not compile in 32 bit linux due to the warnings-as-errors being enabled,
which has also been fixed.
Fixes #877

Fix 32 bit linux unknown function handling

---

loader/loader.c
loader/loader.h
loader/loader_common.h
loader/loader_linux.c
loader/terminator.c
loader/trampoline.c
loader/vk_loader_platform.h
tests/loader_layer_tests.cpp

Refactor the version selection logic by utilizing `loader_api_version`.
Relaxes the requirement that all components layers have the exact same API version as the meta layer, to just requiring that their version is greater than or equal to the meta layer API version.
Fixes #796

Cleanup version checks and allow newer component layers in meta layers

---

loader/unknown_ext_chain_gas_x86.S

Fix breaking of builds due to the dropping of GOT addressing mode.
Fixes #909

Revert 32bit linux unknown ext chain change

---

loader/loader.c
loader/loader_common.h
loader/trampoline.c
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_layer_tests.cpp
tests/loader_regression_tests.cpp

Log an error if an application creates a VkDevice from a physical device which
was enumerated from a driver that is a portability driver but the application
didn't correctly enable the portability enumeration flag & extension.

Warn if portability_enumeration extension should be enabled

---

loader/loader.c
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/loader_unknown_ext_tests.cpp

Make it possible for layers to declare that they support unknown functions
and set up the layer dispatch table appropriately. A very niche use case
but helpful when developing validation for functions not yet out in the
public headers.
Fixes #893

Implement unknown function intercept in layers

---

CMakeLists.txt
loader/loader.c

The ${CMAKE_SOURCE_DIR} uses the wrong directory when the loader is included as a
subproject. By using ${CMAKE_CURRENT_LIST_DIR}, the CMake code to find the git
commit and branch name will use the correct directory.
Additionally, the logic was ammended to curtail this issue in the future. Quotes are
included in the string to allow it to be used as a string literal, instead of
needing a const char[] variable and macros. Also, the CMake code was restructured
to always define GIT_BRANCH_NAME and GIT_TAG_INFO.
Fixes #919

Fix CMake code for getting Git Version information

---

loader/loader.c
loader/loader.h
loader/loader_common.h
loader/trampoline.c
tests/loader_regression_tests.cpp

Unless the portability enumeration extension is enabled and the create instance flags
contain VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR, do not enumerate drivers that
contain `is_portability_driver` in their JSON Manifest. This is phase 2 of the release
for the VK_KHR_portability_enumeration extension.
An error message will be printed when no drivers were reported but there was a
portability driver which was skipped over.

Make portability drivers not load by default

---

docs/LoaderLayerInterface.md

Some fields specific to manifest files were missing.  Also updated
file to clearly indicate where fields are valid and usable.

Update layer manifest file

---

loader/loader.c

Output a layer message if the override layer is present and the
app name is not in the app_keys list.
Fixes issue #917.

Output message if override app_keys mismatch on app name

---

loader/loader.c
tests/loader_regression_tests.cpp

When checking for the portability driver field of driver manifests,
the loader did not check if inst was NULL first. Since this function
is called in pre-instance functions, this crashes the loader.

Fix a NULL inst crashing during loader_icd_scan

---

docs/LoaderDriverInterface.md
docs/LoaderLayerInterface.md

Clarify what is indicated by the "api_version" field in both
layer and driver manifest files.
Fixes issue #336.

Clarify JSON Manifest "api_version"

---

docs/LoaderInterfaceArchitecture.md

Split up into two tables:
- Active
- Deprecated
Clean up restrictions into their own column for easier viewing.
Made text slightly smaller to fit more in a smaller space.

Clean up environment var docs

---

docs/LoaderInterfaceArchitecture.md

Introduced a typo in my last commit in the table regarding the
disabling of instance extensions.  This is not a Linux only env
var.

Fix typo in env var table

---

loader/loader.c

This prevents bugs where uninitialized memory is treated as a real path. It
should fix an issue where sometimes CI would fail due to what appears to be a
spurious path with junk characters.

Use calloc to allocate memory for the search path

---

loader/debug_utils.c
loader/debug_utils.h
loader/gpa_helper.c
loader/loader.c
loader/loader_common.h
loader/trampoline.c
tests/loader_debug_ext_tests.cpp

Previously the loader would destroy any debug callbacks created during instance creation
to later create new ones during instance destruction. This required a memory allocation
to occur inside vkDestroyInstance, which can cause leaks if an OOM occurs during
instance destruction.
This commit simplifies the logic by keeping around the allocations made during instance
creation by moving them into their own debug node chain. Then during instance destruction
moves them back.
Also renames several functions to better describe their intended purpose.
Fixes #936

Keep allocated debug callbacks until destroy instance

---

loader/loader.c
loader/loader.h
loader/trampoline.c
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/loader_alloc_callback_tests.cpp

Various situations could cause an OOM to turn into a hard crash due to double freeing
of memory that was improperly cleaned up. Also fixed memory leaks when layers would
report OOM.
Fixes #938 #339

Fix crashes from OOM in vkDestroyInstance

---

loader/unknown_function_handling.c
tests/framework/layer/test_layer.cpp

When checking for unknown physical device functions, check the first layer that supports
vk_layerGetPhysicalDeviceProcAddr in the chain starting with the layer closest to the
application. This prevents unecessary work being done, and if any layer wraps VkInstance
will properly call through the wrapping layer first without calling into any other layer.

Only check first GPDPA in the layer chain.

---

loader/CMakeLists.txt

The loader options dummy targets were being linked into the public
interface of the loader, meaning that they were also set in projects the
include the loader as a sub-project. These override the containing
projects settings and can break things. There don't seem to be any
interface requirements in these settings, so include them as PRIVATE, so
that they stay local to the loader.
Fixes #961.

Prevent loader config from overriding project config

---

loader/loader.c

Occurs after file_vers is freed and when the layer manifest has a layers field
but has a version of 1.0.0.

Fix use-after-free in loader_add_layer_properties

---

docs/LoaderDriverInterface.md
docs/LoaderLayerInterface.md
loader/loader.c
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_regression_tests.cpp

Allows drivers and layers to specify if they are 32 bit or 64 bit in the
manifest file. This makes the loader able to prune manifests without
loading the library and finding that it failed to load.

Add 32 & 64 bit field to json manifests

---

loader/allocation.h
loader/get_environment.c
loader/loader.c
loader/loader_windows.c
loader/stack_allocation.h
loader/vk_loader_platform.h
tests/framework/framework_config.h.in
tests/framework/icd/CMakeLists.txt
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_envvar_tests.cpp

Vulkan-Loader cannot load SwiftShader via VK_ICD_FILENAMES if there are unicode characters in the path.

loader: Add unicode support

---

loader/loader.c

AMD driver has the ability to create both physical and virtual devices. Virtual devices have adapterID = 0.
Recent change in Loader 1.3.211.0 made EnumeratePhysicalDevices obsolete, in favour of EnumerateAdapterPhysicalDevices. Virtual devices are reported for each physical adapterID, which makes duplicates in ptr_instance->phys_devs_term array.
The function that deletes this array tries to delete each element one by one, but if there are duplicate pointers present, it crashes on trying to delete the same element twice.
The easiest fix is to remove the duplicates before deleting the array.

loader: device array dealloc fix

---

tests/framework/shim/shim.h
tests/framework/shim/shim_common.cpp
tests/framework/shim/unix_shim.cpp
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_envvar_tests.cpp
tests/loader_layer_tests.cpp

Use the order defined the FolderManager's to define the order readdir
uses, rather than leaving it undetermined. This makes tests more consistent
by forcing layers and drivers to always be found in the same order on all
systems.
Note: MacOS doesn't currently have consistent ordering due to a crash with
ASAN. But even if ASAN isn't running, the dirent structure is being filled
out incorrectly, causing further test failures. While not ideal to disable
consistent ordering on MacOS, it is needed for linux and thus the issue
isn't high enough priority to resolve.

Make tests get files in a consistent order

---

loader/loader.c
tests/loader_regression_tests.cpp

When creating a device, the loader looks for the VkDeviceGroupCreateInfo
structure and replaces it with its own. This allows the loader to edit the
struct. However, to do this required editing the pNext chain. Because the
edited chain contained pointers to structures whose lifetimes end when the
vkCreateDevice function returns, the pNext chain is now corrupted.
This commit fixes that by storing a pointer to the user's
VkDeviceGroupCreateInfo and fixing up the pNext chain to use that instead.
Fixes #643 (well not really but does fix a potential crash)

Fix corrupted pNext chain in vkCreateDevice

---

loader/loader.c
loader/loader_windows.c
loader/loader_windows.h

Chromium still supports building for Win7, as such the newly added support for
VulkanOn12/Dozen needs to be excluded from said build. This is achieved by using
the SDK version macros defined in <sdkddkver>

Disable VulkanOn12/Dozen in Windows 7

---

loader/loader.c
loader/loader_windows.c
loader/loader_windows.h

Allow loader to run on Windows 7 by dynamically loading function pointers for Windows 8 and above APIs.

loader: Dynamically load Win8+ functions

---

loader/loader.c

Replace memcpy with memmove in terminator_CreateInstance to prevent possible issues
with the same memory being the source of the copy and the dest, as there is a for
loop which makes it possible for that to happen.
Fixes #988

Use memmove for copying pApplicationInfo

---

loader/CMakeLists.txt
loader/stack_allocation.h

Check for the existence of the alloca.h header and only use it it exists,
otherwise fallback to stdlib.h. Some OS's like macOS and QNX have both
headers and can use either (stdlib.h includes alloca.h), some OS's like
OpenBSD / FreeBSD / NetBSD do not have the alloca.h header and require
the stdlib.h header.

loader: Only use alloca.h if it exists otherwise fallback to stdlib.h

---

docs/LoaderLayerInterface.md
loader/loader.c
tests/loader_layer_tests.cpp

This change makes the loader conform to the latests specification update, 1.3.227, which removes the requirement that implicit layers API version is at least as high as the application provided API version.
This change reduces friction for layer developers and API users.

Allow implicit layers for all API versions

---

loader/loader.c

The previous message incorrectly labled all layes as Explicit layers and didn't indicate what the 'warning' was about very well.

Make old layer with new app API version warning clearer

---

loader/loader.c

These libraries will always be loaded in vkCreateInstance, so we don't need to load them again in vkCreateDevice. This has the added benefit of not printing 'unloading library X' twice in the log.

Don't load layer libraries in vkCreateDevice

---

tests/CMakeLists.txt

gtest_discover_tests() doesn't work in cross compilation environments, so if that is happening fall back to gtest_add_tests().

Enable cross compile test discovery

---

loader/wsi.c
tests/loader_wsi_tests.cpp

Instance extensions are aggregated, therefore an application has no way of knowing whether an ICD supports a WSI function or not. This necessitates returning instead of aborting from WSI functions, as well as writing 0, NULL, or returning false as needed for each function. This also needs additional NULL checks before calling down into the driver.
Fixes #4

WIP: Don't abort when drivers don't support WSI calls

---

tests/loader_wsi_tests.cpp

Was a basic case of googletest not allowing implicit conversion between types.

Fix issue with MSVC 15 failing to compile test code

---

.github/workflows/build.yml
BUILD.md
CMakeLists.txt

- This approach matches what our SDK release process expect
- Since setting CMAKE_MACOS_DEPLOYMENT_TARGET ignores env variable which SDK release process uses, which could will cause issues in the future, if the version is changed
- CMAKE_MACOS_DEPLOYMENT_TARGET doesn't propogate to dependencies via update_deps.py

ci: Use MACOS_DEPLOYMENT_TARGET

---

loader/CMakeLists.txt
loader/asm_offset.c
scripts/parse_asm_values.py
tests/framework/CMakeLists.txt

This allows cross compilation to enable unkonwn function handling as gen_defines.asm will be generated without needing to run code meant for the target platform. Previously, asm_offset.c wrote the gen_defines.asm file by being run. Now, compilers emit their intermediate assembly output that the parse_asm_values.py script knows how to find the relevant information from.
Additionally set the test framework `framework_config` build option to always copy, instead of copy_if_different. This is needed since cmake wouldn't update this file when changing from/to debug & release mode.
Fixes #249 
Fixes #881

Write gen_defines.asm using a python script

---

loader/loader_windows.c
tests/loader_regression_tests.cpp

Code which was originally meant to deduplicate drivers that moved from the old registry HKEY_LOCAL_MACHINE/SOFTWARE/Khronos/Vulkan/Drivers to PnP locations was incorrectly applied to layers as well. The issue is that multiple layers can share the same json file name but not actually contain the same manifest. Worse, the first layer found would be assumed to be correct, even the file had been deleted from the file system.
Fixes #750

Only deduplicate driver manifests

---

loader/debug_utils.c

loader_calloc_with_instance_fallback is used in places where a user can supply their own allocator, but should default to the allocator used with the instance otherwise. The issue was that loader_free was being used with objects created with the instance allocator, but loader_free only takes the user provided one, leading to leaks.
Fixes #1040

Use correct allocator in debug_utils.c

---

BUILD.md
loader/CMakeLists.txt
loader/asm_offset.c

The cross compiling workaround for asm_offset requires python, but this meant
that all builds required python. This commit re-adds the removed asm_offset
logic and then only requires python during cross compilation.

Re-add asm offset execution & Update BUILD.md

---

loader/generated/vk_loader_extensions.c
loader/loader.c

My electron app crashed on vulkan.dll, then I found the dev pointer may be null but still be read.
From the call stack, we can see that it's calling `loader_get_icd_and_device`  to get `dev`, and the dev may be null
```
VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL loader_gpa_device_terminator(VkDevice device, const char *pName) {
struct loader_device *dev;
struct loader_icd_term *icd_term = loader_get_icd_and_device(device, &dev, NULL);
...
PFN_vkVoidFunction addr = get_extension_device_proc_terminator(dev, pName);
if (NULL != addr) {
return addr;
}
return icd_term->dispatch.GetDeviceProcAddr(device, pName);
}
PFN_vkVoidFunction get_extension_device_proc_terminator(struct loader_device *dev, const char *pName) {
PFN_vkVoidFunction addr = NULL;
// ---- VK_KHR_swapchain extension commands
if …
```

fix: add dev pointer checking before using

---

loader/CMakeLists.txt
loader/log.c
loader/log.h
loader/unknown_ext_chain.c
loader/unknown_ext_chain_gas_aarch64.S
loader/unknown_ext_chain_gas_x86.S
loader/unknown_ext_chain_masm.asm
scripts/parse_asm_values.py
tests/loader_unknown_ext_tests.cpp

The issue was that passing a string to loader_log wouldn't work, likely due to relocation issues. Workaround is to create a bespoke function that contained the format string embedded in it.
Also rename the error to note that its a function which isn't supported, not an extension.
@sl1pkn07 - can you confirm this solves your issue? From what I can tell, the 32 bit unknown function handling worked except in the error handling path. This resolves that last issue.
Fixes #877

Fix linux 32 bit unknown function error handling

---

.github/workflows/build.yml
loader/extension_manual.c
loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/loader.c
loader/loader_common.h
loader/unknown_function_handling.c
loader/wsi.c
scripts/loader_extension_generator.py
tests/framework/icd/test_icd.cpp
tests/framework/layer/wrap_objects.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_handle_validation_tests.cpp
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

There are numerous terminators to device level functions that the loader must insert in the call chain. However, the Device Dispatch Tables contain pointers to these terminators rather than the driver's function. This was worked around by storing the driver's functions in the ICD dispatch table and calling those. This leads to rather confusing code where the application is querying for the ICD dispatch table inside a device level function.
The solution is to create a bespoke dispatch table for device level functions that require a terminator, and use that table when required.
This PR also adds limited Swapchain testing, as previously there were no tests which created, used, and destroyed a swapchain, all functions that definitely should have tests for. It also refactors the setup_WSI() …

Remove Device functions from ICD Dispatch table, replace it with a bespoke table.

---

loader/loader.c
loader/loader_common.h

This was an undocumented feature of the override manifest layer. Since vkconfig is the primary user of the override layer, and vkconfig makes no effort to include expiration support, this feature is not being used. Thus, it is best to remove it entirely.
@christophe-lunarg This is a feature that just isn't very useful. I would like to remove it from the loader, but would like your approval, as if you would like to see this feature stay I should know before removing it, not after. 
The gist of the feature is an automatic 'time out' where a layer with an expiration date that has elapsed will no longer be loaded.

Remove override layer expiration

---

loader/generated/vk_loader_extensions.c
scripts/loader_extension_generator.py

A recent change made it so that when either vkDebugMarkerSetObjectTagEXT, vkDebugMarkerSetObjectNameEXT, vkSetDebugUtilsObjectNameEXT, or vkSetDebugUtilsObjectTagEXT is called, if a driver doesn't support any of those functions the loader would abort. This is incorrect because drivers may not support the debug utils extension while the loader & layers might. Now the loader only aborts if the Device handle is invalid, and simply returns VK_SUCCESS if a driver doesn't support those functions.
Fixes #1052

Dont abort when driver doesn't support debug utils

---

BUILD.md
CMakeLists.txt

The way to use ccache has changed since this documentation & build option were added. Update the docs with the new way to enable ccache and remove the build option.

Remove USE_CCACHE build option

---

.github/workflows/build.yml

Re-enables using the macOS-latest github actions runner now that the loader has been fixed for newer macOS versions.

Add macOS-latest CI action

---

loader/trampoline.c

loader_make_version recently was changed to zero out the patch version, explicitly doing it is no longer necessary.
Even though the change was small I did run the tests and everything passed, I'm not sure if there's any way to attach that.

Remove redundant code

---

loader/loader.c
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/loader_phys_dev_inst_ext_tests.cpp

Layers are liable of changing the API version during the call down vkCreateInstance. Certain layers use the guarantees of 1.1 to allow using VK_KHR_get_physical_device_properties2 functionality. This commit checks and assignes a new API version if it was modified.
Add tests for when the application forgets to enable 1.1 and when a layer enabled 1.1 on behalf of the application.
Fixes #1055

Recheck API version in terminator_CreateInstance

---

loader/loader.c
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_envvar_tests.cpp
tests/loader_regression_tests.cpp

If loader_get_json fails, it returns VK_ERROR_INITIALIZATION_FAILED which loader_parse_icd_manifest passed upwards. Since the caller of loader_parse_icd_manifest wasn't expecting that error code, it didn't skip the ICD, causing an infinite recusion in EnumInstExtProps due to the call to dlsym(NULL, "vkEnumerateInstanceExtensionProperties"); resolving to the loader's copy of it.

Handle invalid files & symlinks in the loader properly

---

loader/loader.c
tests/loader_alloc_callback_tests.cpp

goto's were replaced by returns erroneously. This caused unfreed memory in certain OOM scenarios, caught by CTS. The reason the loader tests didn't catch this was because the fake drivers did not report any extensions, thus no memory was allocated (which would later be leaked). This commit addressess this deficiency in the tests as well, which included correctly incrementing the MemoryTracker's allocation count during realloc.

Fix cases where OOM was handled wrong

---

loader/loader.c
tests/framework/data/VkLayer_complex_file.json
tests/framework/framework_config.h.in
tests/loader_alloc_callback_tests.cpp

There was a few places where an out of memory error could be generated
by parsing json but were not passed on upwards, causing CTS tests to fail.

Propagate OOHM error from json parsing 

---

loader/loader.c
loader/loader.h
loader/loader_environment.c
tests/loader_alloc_callback_tests.cpp

There were more cases where OOM wasn't being propagated correctly, or even caught in the first place. This change makes all of those paths report OOM to the application as is expected. One case was due to linux sorting erroring out but then leaking memory, which wasn't caught because the tests didn't create devices that supported PhysDevProps2.
Lastly, since the Allocation tests were taking much longer due to making many more allocations, the MemoryTracker was rewritten to use std::unordered_map to speed up insertion and lookup of allocations made.

Add more OOM handling paths and refactor OOM tests

---

loader/loader_environment.c

Previously it used integrity_level > MEDIUM, which causes issues since occasionally windows elevates certain regular user mode processes to be MEDIUM + 0x100 or similar, causing the `is_high_integrity()` to return true even though it isn't an admin level process.
Fixes #814

Use integrity_level >= HIGH for is_high_integrity

---

loader/unknown_ext_chain_gas_aarch64.S
loader/unknown_ext_chain_gas_x86.S

These don't need to be exported from the shared library, as they're just internal implementation details.
Closes #1079

loader: Mark unknown_ext_chain symbols as hidden

---

docs/LoaderApplicationInterface.md
docs/LoaderDebugging.md
docs/LoaderInterfaceArchitecture.md
loader/loader.c
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/loader_layer_tests.cpp

Added a new field `is_dir` to the `TestLayerDetails` to allow for the test suite to set either directories or files on the VK_LAYER_PATH environment variable. Added tests to verify that the layers actually get loaded by calling `vkEnumerateDeviceLayerProperties`

Layers: add tests to verify VK_LAYER_PATH supports both directories and files 

---

docs/LoaderLayerInterface.md

> If `VK_LAYER_PATH` is present, then `VK_ADD_LAYER_PATH` will not be
used by the loader and any values will be ignored.
This was present for the Windows documentation but not for linux and company.

Document interaction of layer env-vars for linux

---

loader/loader.c

There is an optimization bug in XCode 14.1 that is causing vulkaninfo to crash on valid code. We've come up with some awkward work arounds, but the sanest approach is to turn off optimization just for the function loader_create_device_chain (and only on Apple devices).

Fix for Apple compiler bug

---

loader/CMakeLists.txt

The revertion of gen_defines.asm generation during cross compilation changed the form of add_custom_command used, which inadvertently relied on CMake 3.16 support.
Fixes #1095 
From the CMake Docs:
DEPENDS:
...
A target-level dependency is added if any dependency is a byproduct of a target or any of its build events in the same directory to ensure the byproducts will be available before this target is built.

Revert asm_offset CMake code to work with 3.10

---

CMakeLists.txt
scripts/known_good.json

Vulkan::Registry was deprecated by Vulkan-Headers
Use 'VULKAN_HEADERS_REGISTRY_DIRECTORY' instead.

cmake: Fix usage of Vulkan::Registry

---

CMakeLists.txt

In CMakeLists.txt, I've added an option to enable or disable build vulkan loader as submodule, by default, is false, not changing the default behavior

Added build as submodule option

---

loader/loader.c
loader/loader_common.h

If there is an error loading a dynamic library, check to see if it is the result of an OOM condition. Then return the appropriate OOM error code up the callchain. This commit is the result of an OOM condition when trying to load the validation layers, which resulted in the return code VK_ERROR_LAYER_NOT_PRESENT. This is very misleading. If the loader can catch then report more accurate information, then it should.
Fixes #1088

Try to catch OOM errors when loading binaries

---

loader/generated/vk_layer_dispatch_table.h
scripts/loader_extension_generator.py

vk_layer_dispatch_table.h may be included after vk_icd.h and may cause multiple definitions. This commit adds a macro guard on whether the type is defined just in case.

Add guard for GetPhysDevProcAddr typedef

---

CMakeLists.txt
tests/framework/test_util.h

> VS2015 is no longer supported
Here is my source in case someone needs it:
https://www.lunarg.com/wp-content/uploads/2023/01/Progress-Report-DEC2021-Vulkan-Ecosystem-Survey-Public-Report.pdf
> Deprecate Visual Studio 2015 - Completed
a. SDK and several repositories will no longer build, test, and support VS2015

build: Remove VS2015 support

---

docs/LoaderDriverInterface.md
docs/LoaderInterfaceArchitecture.md
loader/loader.c
tests/framework/framework_config.h.in
tests/framework/icd/CMakeLists.txt
tests/framework/icd/export_definitions/test_icd_7.def
tests/framework/icd/export_definitions/test_icd_7_with_exports.def
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

The changes made by ICD Interface Version 7 are as follows. If an ICD supports any of the following functions from the Loader-ICD interface, they must be queryable with vk_icdGetInstanceProcAddr:
* vk_icdNegotiateLoaderICDInterfaceVersion
* vk_icdGetPhysicalDeviceProcAddr
* vk_icdEnumerateAdapterPhysicalDevices (Windows only) In addition, these function no longer need to be exported by the driver.

Add Vulkan Loader-ICD Interface Version 7

---

README.md

I'll also update https://github.com/KhronosGroup/Vulkan-Loader/issues/1107 with the impending date
Note: This date matches VVL's date which would make life simpler:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5130

docs: Notify users about upcoming master to main change

---

loader/loader.c
tests/loader_layer_tests.cpp

The current design of the loader make the Override Layer, with its override paths, take priority over VK_LAYER_PATH. This is fine, but if the override layer accidentally was left around, it can cause confusion as VK_LAYER_PATH suddenly stops working for no apparent reason. This commit adds a log message to indicate that it is being ignored.

Log when VK_LAYER_PATH is ignored

---

loader/loader.c
loader/loader_windows.c
loader/wsi.c

The loader_log() function adds a new line at the end of every log message. Having the string contain an extra new line is redundant and makes the output inconsistent due to having random blank lines.

Remove newlines in log messages

---

CMakeLists.txt
docs/LoaderApplicationInterface.md
docs/LoaderDebugging.md
docs/LoaderDriverInterface.md
docs/LoaderInterfaceArchitecture.md
docs/LoaderLayerInterface.md
loader/loader.c
loader/loader.h
loader/trampoline.c
tests/framework/README.md
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_envvar_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_testing_main.cpp
tests/loader_version_tests.cpp

VK_LUNARG_direct_driver_loading is an instance extension which allows applictations to include drivers directly to the loader, instead of relying on system installed drivers or environment variables specifying where the desired driver is located. This allows applications to 'ship' a driver with themselves and easily provide it to the system loader.
Changes related to direct driver loading:
* Source implementation
* Documentation of new extension, interactions with existing driver discovery mechanism, and issues with implicit layers
* Extensive tests covering many feature combinations.
Changes also made in this commit:
* Add EnvVarWrapper which more cleanly handles setting, modifying, and removing Environment Variables. This has the effect of allowing all tests to run from the test …

Implement VK_LUNARG_direct_driver_loading

---

loader/generated/vk_loader_extensions.c
scripts/loader_extension_generator.py
tests/framework/icd/test_icd.cpp
tests/framework/test_environment.cpp
tests/loader_debug_ext_tests.cpp
tests/loader_version_tests.cpp

Certain functions, like vkSetDebugUtilsObjectNameEXT can take a physical device as a parameter. When this function is queried through vkGetInstanceProcAddr, the trampoline is returned, whereas when queried through vkGetDeviceProcAddr, the trampoline wasn't returned, allowing the physical device parameter to not get unwrapped before calling down the chain, causing a crash.
This commit modifies the codegen to always use the trampoline for these functions, and adds tests for them. These changes require the the loader check that the appropriate extensions are enabled during the application's call to vkGetDeviceProcAddr, since it otherwise always return a non-null function pointer.
Fixes #1109

Ensure VkPhysicalDevice unwrapping in Device functions

---

docs/LoaderInterfaceArchitecture.md
tests/loader_envvar_tests.cpp

In the documentation examples, if we set
`VK_LOADER_DRIVERS_SELECT=nvidia`, we are saying to the loader to select only the driver whose JSON manifest is called exactly `nvidia`.
This is likely not what we want, because the Nvidia drivers are usually called something like `nvidia_icd.json`, and not just `nvidia` without a file extension.
In the "Behavior" column it already states that:
"Since drivers don’t have a name like layers, this glob is used to compare against the manifest filename."
So, to avoid confusion, we just need to change the example to reflect how the loader glob works.
This commit also adds an additional automated test to ensure that this full-name string glob actually works as described in the documentation.

Clarify the VK_LOADER_DRIVERS_SELECT example

---

loader/loader.c
loader/loader_common.h
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/loader_regression_tests.cpp

The device layer fields in VkDeviceCreateInfo are deprecated and have been for years. Users should not be adding anything to them (and if they do, it should match the layers added in VkInstanceCreateInfo).
This would be a warning that 'device layers are deprecated, they do nothing' in case a user is trying to enable validation layers using them. Charles has seen multiple users not knowing that they are deprecated and get burned by the API due to not having validation layers enabled.
Since there may be applications in the wild which currently do provide a list of layers to device create info, this warning should only be issued if the list differs from instance creation. That way no spurious warnings are created.

Warn user when using device layers field #1086

---

docs/LoaderDriverInterface.md

`vk_icdNegotiateLoaderICDInterfaceVersion` was intended but due to a copy paste error `vk_icdGetInstanceProcAddr` was used instead.

Fix documentation to use the correct function name

---

loader/loader.c
loader/trampoline.c

If CreateInstance successfully calls terminator_CreateInstance but subsequently fails on the way back up the chain, the loader should call DestroyInstance on each driver to give them a chance to clean up. This path is possible during CTS OOM tests which cause VVL to fail which then causes leaks to occur.
Additionally, the layer name allocations needed to be cleaned up in this error path as well, since there is no chance for vkDestroyInstance to run.

Call DestroyInstance on each driver in error path

---

.github/workflows/build.yml

Because the loader only uses github actions to perform CI runs, it is good to set the 'read-all' only, helping harden the github actions runners from potentially compromised access.
For more context
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
Fixes #1148

Set github actions to only have read only permissions

---

loader/loader.rc
scripts/generate_source.py

FILVERSION is supposed to be a 4 component field. The previous commit to make loader.rc be generated did not account for that and so requires this fix to make sure it has four components. Thankfully, this issue is not present in SDK released loaders thanks to the SDK specifying its own version string that has 4 components.
Fixes #1164

Add 4th component to version in loader.rc

---

loader/loader.c
loader/loader.h
loader/loader_environment.c
loader/trampoline.c
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_layer_tests.cpp
tests/loader_testing_main.cpp

When there are multiple versions of the same layer found through environment variables or from implicit layer locations, the loader would use the *last* one that appeared rather than the first, causing surprising behavior. This commit fixes that by checking to make sure that layers do not already exist in the list of layers to be enabled before adding a layer to the list, preventing duplicates from appearing in the list.
Fixes #1153

Make correct layer be used when duplicates are present

---

loader/loader.c
loader/loader_environment.c
loader/loader_environment.h
tests/framework/shim/shim.h
tests/framework/shim/shim_common.cpp
tests/framework/shim/unix_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/loader_layer_tests.cpp
tests/loader_regression_tests.cpp

The commit to add VK_LOADER_LAYERS_ENABLE/DISABLE inadvertently broke the ordering guarantees of VK_INSTANCE_LAYERS. This commit restores that order. If both VK_INSTANCE_LAYERS and VK_LOADER_LAYERS_ENABLE add layers, the order will be VK_INSTANCE_LAYERS enabled layers, in the order specified by the env-var, followed by any layers enabled by VK_LOADER_LAYERS_ENABLED enabled in the order they are found on the system.
In addition to this, the test framework receieved two changes:
* Make env-var folders report their contents in a deterministic order (aka the order the items were added to the framework). This mirrors existing behavior for redirected folders.
* Make platform shim resilient to shutdown ordering issues. Namely, set a flag during shutdown so that any interception functions go …

Fix ordering regression for VK_INSTANCE_LAYERS

---

scripts/dispatch_table_helper_generator.py
scripts/generate_source.py
tests/framework/layer/test_layer.cpp
tests/framework/layer/vk_dispatch_table_helper.h
tests/framework/layer/wrap_objects.cpp

vk_dispatch_table_helper.h will no longer be generated for every new header version because it is not used in the loader source. Rather, it was only being used for the tests. This commit moves it to tests/framework/layer where it is being used. While the python generation code could have been updated to write it into a different folder, due to the difficulty of that change, it is simpler to just move the file and stop autogenerating it. The code to generate it is left as is in case there is a need to update it in the future.

Move vk_dispatch_table_helper.h to tests

---

loader/debug_utils.c
loader/loader.c
loader/loader_linux.c
loader/loader_windows.c
loader/wsi.c
tests/framework/layer/wrap_objects.cpp
tests/framework/shim/unix_shim.cpp
tests/framework/test_util.h
tests/loader_debug_ext_tests.cpp
tests/loader_handle_validation_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_phys_dev_inst_ext_tests.cpp
tests/loader_regression_tests.cpp

The `static` specifier is used inconsistently throughout the codebase. This commit removes it from most places where it is unnecessary. Static's purpose is to make any function defined inside of a translation unit unuseable from other translation units. But because we use header files to define which functions are exposed, we can simply omit static for functions private in a translation unit.
This commit also removes static in a couple of places where it isn't needed, such as local variables that do not act as storage beyond the scope of the function, and for global variables defined inside of implenetation files.
Uses of static in header files, such as vk_loader_platform.h, is left as is because those functions need static to prevent multiple definition errors.
Resolves #1158

Remove unnecessary static in source

---

loader/loader.c
tests/framework/icd/test_icd.cpp
tests/loader_debug_ext_tests.cpp

This commit fixes the loader to check for the debug_utils extension being enabled before returning functions, fixes the tests to properly check for the functions when using both Get*ProcAddrs, and enhances the test framework to support querying for the debug marker extensions.
The debug_utils functions are special because they are from an instance level function. That means it is always possible to check if the extension that makes them available is enabled from both vkGetInstanceProcAddr and vkGetDeviceProcAddr. The loader was previously always returning valid functions for some of the debug_utils functions when the extension was not enabled, and this commit fixes that.
The debug_marker extension is a bit different, since it is a device level extension. Thus, querying the functions from …

Fix debug extension function loading

---

.github/workflows/build.yml
loader/CMakeLists.txt
loader/vk_loader_platform.h

Fixes this error:
```
CMake Error at loader/CMakeLists.txt:263 (target_compile_definitions):
Cannot specify compile definitions for target "vulkan" which is not built
by this project.
```

cmake: Fix LOADER_DISABLE_DYNAMIC_LIBRARY_UNLOADING

---

.github/workflows/build.yml

Fixes github actions for 32 bit builds, which reported that libgcc-s1:i386 was required but not going to be installed.
Also split out the setup commands into separate run statements rather than have them string together.

Added libgcc-s1:i386 to linux-32 Github actions

---

BUILD.gn
loader/vk_loader_platform.h

If the loader is linked statically, there is no need to export all vulkan functions from the linking application. This issue showed up in ANGLE which would export all GLES and Vulkan functions on Mac.

Don't export Vulkan functions when building the loader statically

---

loader/generated/vk_loader_extensions.c
loader/loader.c
scripts/loader_extension_generator.py
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/loader_regression_tests.cpp

The magic value for the device dispatch table was being set after calling down the layer chain rather than before. This is wrong because of the situation when layers create devices from different physical devices, the magic value using the default value of zero means that loader_get_icd_and_device will return the wrong loader_icd_term, leading to crashes elsewhere.
The fix is to set the magic value right after the dispatch table is allocated.
This commit adds tests for both drivers being created from the same physical device and from different physical devices.
Fixes #1198

Fix crash from layers creating devices on different physical devices

---

.github/workflows/build.yml
BUILD.gn
BUILD.md
loader/CMakeLists.txt
loader/loader.c
loader/loader_environment.c
tests/loader_envvar_tests.cpp

Make LOADER_USE_UNSAFE_FILE_SEARCH a CMake option.
Allows validation layers to disable safe search to work around permissions issues on Github Actions.

LOADER_USE_UNSAFE_FILE_SEARCH

---

BUILD.md
CMakeLists.txt
loader/CMakeLists.txt
scripts/generate_source.py

There are a couple things at play here.
Only enable codegen helper target for users who request it. Avoids issues with package managers.
Also avoid usage of `find_package(PythonInterp 3)` which has been deprecated since 3.12

LOADER_CODEGEN

---

loader/loader.c

read_data_files_in_search_paths' `relative_path` is only used on unix platforms but is defined for all platforms. This causes clang-cl to warn about it, and causes the build to fail when ENABLE_WERROR is on.
The fix is to *not* define the offending variable on windows. Makes the code more annoying to read due to the excessive #if #else macros, but that is the simplest change.

Remove unused variable for clang-cl on windows

---

loader/loader.c

UBSan was detecting a function type mismatch for these module ctor/dtors since libc expects the function type to be void (*)(void) rather than just void (*)().

loader: Add void to function arguments

---

loader/vk_loader_platform.h

The header is unused and causes compilation issues due to the header needing to be included before windows.h

Remove inclusion of winsock2.h

---

.github/workflows/build.yml
loader/CMakeLists.txt
loader/dev_ext_trampoline.c
loader/loader_windows.c
loader/log.h
loader/phys_dev_ext.c

The build logic for enabling the unknown function support when ASM code doesn't
work or is disabled was broken. This fixes it by consolidating the various code
paths as well as making sure it is enabled when it should be.
This also fixes the fallback path for macOS by making sure to only modify the
names of functions if and only if the corresponding assembly code is active.

Fix fallback unknown function build logic & add no-asm CI runs

---

loader/loader_windows.h
loader/settings.c
loader/vk_loader_platform.h
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/loader_settings_tests.cpp

Move the settings registry to "LoaderSettings" and the unix location to "loader_settings.d".
The  validation layers looks for the settings file on windows in "SOFTWARE/Khronos/Vulkan/Settings" but doesn't check the file name. To maintain compatibility, the loader's settings file needs to be in a different location.
Fixes #1219

Change settings file location

---

.github/workflows/build.yml

The windows_vs-no-asm was incorrectly setup, causing the assembler to be found when it should have used the fallback path.

Fix USE_MASM=OFF in github actions

---

loader/loader.c
loader/loader_environment.c
loader/vk_loader_platform.h
tests/framework/test_util.h
tests/loader_testing_main.cpp
tests/loader_version_tests.cpp

strtok is not threadsafe, which was previously not a problem thanks to the
'read json' mutex. But since that was removed, it left strtok potentially
corrupting data as multiple threads try to use it. While there are
platform specific versions of strtok that are thread safe, the parsing
logic is simple enough that replacement functions were devised for the
handful of places it was used.
Fixes #1224 
Looking at the fixes I have here, I am not sold on replacing the code with bespoke functions when strtok_r/strtok_s exists. It makes the changes simpler and doesn't introduce new one-off code that is potentially full of bugs.

Replace strok with threadsafe functions

---

loader/vk_loader_platform.h

Because the function definition lives in a header, it needs to be marked inline to prevent compiler warnings stating that "thread_safe_strtok is unused".
Fixes #1232

Mark thread_safe_strtok as inline

---

.github/workflows/build.yml
CMakeLists.txt
loader/cJSON.c
loader/cJSON.h
loader/loader.c
loader/loader.h
loader/loader_environment.c
loader/loader_environment.h
loader/loader_windows.c
loader/log.c
loader/settings.c
loader/terminator.c
loader/vk_loader_platform.h
scripts/dispatch_table_helper_generator.py
tests/framework/icd/test_icd.cpp
tests/framework/json_writer.h
tests/framework/layer/test_layer.cpp
tests/framework/layer/vk_dispatch_table_helper.h
tests/framework/layer/wrap_objects.cpp
tests/framework/shim/shim_common.cpp
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_debug_ext_tests.cpp
tests/loader_settings_tests.cpp
tests/loader_threading_tests.cpp
tests/loader_unknown_ext_tests.cpp
tests/loader_version_tests.cpp

These warnings were disabled, and this commit enables them. It also fixes the many warnings that were present but were silenced. This includes many unused parameters that could be safely removed. But it also required marking some parameters as `(void)param;` to indicate to the compiler that the parameter is infact required. If a function is a stub function, then instead all of the names of the parameters were removed.
The biggest change is for vk_dispatch_table_helper.h which had stubs for every device function. Rather than try to mark every parameter as unused it was simpler to remove all stub functions, which aren't useful for testing anyhow. Tests should crash rather than silently continue anyhow.

Add & fix warnings for unused functions and parameters

---

loader/vk_loader_platform.h
tests/framework/framework_config.h.in
tests/framework/shim/shim.h
tests/framework/shim/unix_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_util.h
tests/loader_envvar_tests.cpp
tests/loader_regression_tests.cpp

* add the Hurd to `COMMON_UNIX_PLATFORMS`, as it is a POSIX OS
* use the Linux paths for getting the executable path (i.e. using `/proc/self/exe`): the Linux procfs provides both `self` and `<pid>/exe`
* follow the Linux behaviour in tests w.r.t. the platform shim behaviour, the test dummy binaries, and few more other bits
It builds fine, and almost the tests pass with the exception of `ImplicitLayers.DuplicateLayers`, which I have not figured out yet (`env.GetLayerProperties(2)` finds only 1 property and not 2 as expected).
In case of doubts: yes, `__GNU__` the official define for GNU/Hurd, see https://github.com/cpredef/predef/blob/master/OperatingSystems.md#gnu-aka-gnuhurd.

loader: add support for GNU/Hurd

---

loader/loader.c

The condition statement will never check *override_paths statement, and lead CTS test to segfault.

Fix Condition Statement Error

---

.github/workflows/build.yml
loader/loader.c
tests/framework/test_environment.h
tests/loader_layer_tests.cpp
tests/loader_testing_main.cpp

get_override_layer_override_paths logs the path used, but during the refactor it
failed to dereference the double pointer properly, leading to the loader_log
message reading garbage. This was not caught on x64 address sanitizer builds, but
was on the 32 bit build.

Fix wrong pointer usage & Fix tests not using SYSCONFDIR

---

loader/loader_common.h
loader/trampoline.c
tests/loader_regression_tests.cpp

There are three different ways for applications to fail to enumerate portability drivers, not enabling the flag bit, not enabling the extension, and both. These were all reported as the same error, which isn't as helpful as it printing a separate message for each case.
This also makes it possible to emit a VUID for the case of setting the flag bit but not the extension.
Fixes #1254

Enhance warning messages for portability enumeration

---

loader/loader.c
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/framework/layer/test_layer.cpp
tests/loader_alloc_callback_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_phys_dev_inst_ext_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

The apiVersion of a VkPhysicalDevice is not guaranteed to be identical to the
api_version specified by the ICD Manifest JSON file. While there is nothing
inherently wrong with a different version, it is unusual for these versions
to not match, and so this commit adds logic to check & emit a warning whenever
these versions are different.
This warning is in response to a real issue due to behavioral differences in
the loader between 1.0 and 1.1 drivers, as the manifest file reported 1.1
while the VkPhysicalDeviceProperties::apiVersion reported 1.0.
This PR also cleans up tests a fair bit - including setting the API version in a lot of places where they may be relevant.
Fixes #1242

Warn when ICD Manifest version differs from VkPhysicalDevice

---

loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/gpa_helper.c
loader/gpa_helper.h
loader/loader_common.h
loader/trampoline.c
scripts/loader_extension_generator.py
tests/loader_get_proc_addr_tests.cpp

Note: This behavior is not enabled at this time. Future work is needed to determine when to enable the behavior described below
Device commands from versions newer than the apiVersion should not be used, since the app did not enable support for them. But querying for the functions ignored the API version. This commit makes the loader check the apiVersion before deciding whether to return a valid function pointer or NULL.
Tests were added for verifying each behavior, however the tests are skipped as there is no mechanism to enable the behavior at the current time.

Check api version when querying device commands - unused at the current time

---

loader/extension_manual.c
loader/generated/vk_loader_extensions.c
loader/log.c
loader/log.h
loader/trampoline.c
loader/wsi.c
scripts/loader_extension_generator.py

When the loader is about to call abort(), it calls loader_log to tell the user why the loader is crashing. Unfortunately, unless the user set VK_LOADER_DEBUG before starting the loader, they will not see this message. This commits adds a new debug flag to signal to loader_log() that this message should be written to stderr no matter what. This commit also changes all current loader_log call sites that subsequently call abort() to use this flag.

Make fatal log messages be written to stderr

---

tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_regression_tests.cpp

Makes sure the loader test framework can create relative paths in the library_path fields. Adds a test to insure those paths still work.
Since the contents of "library_path" is mututally exclusive with the existing use_dynamic_library_default_search_paths, a new enum was added to allow tests to choose which of the three content types a given ICD or Layer manifest should use.

Add relative path support to test harness

---

loader/log.c
loader/log.h

0x160 is *not* the next highest power of two in hex after 0x80, it is in fact 0x100.
This error caused the log function to always log every message, rather than just fatal ones and whatever messages match the VK_LOADER_LOG environment variable.

Fixed the value of the FATAL_ERROR bit

---

loader/generated/vk_loader_extensions.c
scripts/loader_extension_generator.py
tests/framework/layer/wrap_objects.cpp
tests/loader_debug_ext_tests.cpp

It is possible for a layer to wrap the instance handle, and when the various Set Name/Tag debug functions are called, the passed structure may contain an instance handle which was previously not being unwrapped before calling down the chain. This caused renderdoc to crash, as the instance handle was not known to it.
Fixes #1266

Unwrap VkInstance in set name/tag debug functions

---

loader/generated/vk_loader_extensions.c
loader/loader.c
loader/loader_common.h
loader/trampoline.c
scripts/loader_extension_generator.py
tests/loader_get_proc_addr_tests.cpp

The extension changes the behavior of vkGetDeviceProcAddr to no longer allow querying of core functions beyond the version specified in VkApplicationInfo. Thus, a check is needed to ensure that if the extension is enabled, the apiVersion is sufficient for the function to be returned.

Enable VK_KHR_maintenance_5 support

---

loader/loader.c
tests/loader_get_proc_addr_tests.cpp

The maintenance 5 behavior should only apply when the feature is enabled in addition to the extension being enabled.

Make maintenance 5 require the feature to be enabled

---

loader/CMakeLists.txt
loader/asm_offset.c
loader/cJSON.c
loader/dirent_on_windows.c
loader/loader.c
loader/loader.h
loader/loader_environment.c
loader/loader_windows.c
loader/log.c
loader/settings.c
loader/unknown_function_handling.c
loader/vk_loader_platform.h

CRT_SECURE_NO_WARNINGS disables warnings from using strcpy & strcat as well as strncpy and strncat. This isn't likely a huge concern, but the more warnings the better typically. 
This commit introduces loader_strncpy and loader_strncat which are platform generic versions. C11 added strncpy_s and strncat_s which are analogs to the win32 functions. But because this is a C99 project, these functions are not used.

Enable CRT Warnings and fix them

---

docs/LoaderDriverInterface.md
docs/LoaderInterfaceArchitecture.md
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/loader_envvar_tests.cpp

Orinigally VK_ICD_FILENAMES was documented to only be able to use full paths to ICD Manifest files. This is untrue, as VK_ICD_FILENAMES, and its replacement VK_DRIVER_FILES is able to find drivers using full paths as well as paths to folders containing manifest files. This commit amends the documentation to reflect that capability as well as adding a test for that use case.
Fixes #613

Document VK_DRIVER_FILES ability to look in folders

---

CMakeLists.txt
loader/CMakeLists.txt
scripts/parse_asm_values.py
tests/framework/icd/test_icd.cpp
tests/framework/shim/unix_shim.cpp

Compiling for iOS on an intel mac failed due to not handling the locations of gen_defines.asm and asm_offset.s when running under AppleClang. This solution works for the toolchain file used during development but may not work in other situations.
iOS does not support secure_getenv, which is fine, except that the cmake code check_function_exists seems to think it is supported, causing compilation to fail. Just hardcoding secure_getenv to not be supported is enough for the unix shim logic to compile.
The compilation revelaed a few issues in the test code, like not using [[maybe_unused]] and a signed/unsigned comparison.
Fixes #1275

Add support for AppleClang and iOS cross compilation

---

build-qnx/common.mk
loader/loader.c
loader/vk_loader_platform.h
tests/framework/test_util.h

1. Update build-qnx content to make it buildable again.
2. Switch __QNXNTO__ macro check to __QNX__
During last 23 years the QNX Neutrino microkernel was active, __QNXNTO__ macro belongs to it. Now QNX Muon microkernel is under development, so __QNX__ macro covers both versions: Neutrino and Muon.
First public announce of QNX Muon was here: https://blogs.blackberry.com/en/2023/04/get-in-the-sdv-podcast-from-blackberry-season-2-episode-3

Update QNX build environment to make it buildable again.

---

loader/generated/vk_loader_extensions.c
loader/loader.c
loader/loader_common.h
scripts/loader_extension_generator.py
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/loader_debug_ext_tests.cpp

The implementation for VK_KHR_maintenance_5 exposed a bug in how the function
for debug_marker functions were gotten. The bug was to only check if a
driver supports a physical device when querying for device function pointers,
which ignores the possibility of a layer supporting a device extension. This
is an issue for VK_EXT_debug_marker, which requires trampoline functions to
properly unwrap data passed in, resulting in the various debug marker functions
returning NULL instead of a valid function pointer.

Fix incorrect handling of Debug Marker functions

---

docs/LoaderLayerInterface.md
loader/generated/vk_loader_extensions.c
loader/loader.c
loader/trampoline.c
scripts/loader_extension_generator.py
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/loader_regression_tests.cpp

The device dispatch table has a magic value to ensure consistency, but there was no message logged in case the magic value was corrupted. This commit adds that check, fixes the message being printed for the instance magic value check, and adds tests to ensure they are contining to be checked in the future.
Fixes #1277

Add device dispatch table magic value check

---

loader/CMakeLists.txt

Reverts KhronosGroup/Vulkan-Loader/pull/670 which produces an invalid .pc file
closes #1278

cmake: Fix MinGW vulkan.pc

---

loader/CMakeLists.txt

Now CMake config files are installed.
```
PS D:\projects\loader> cmake --install .\build\ --prefix .\build\install
-- Install configuration: "Debug"
-- Up-to-date: D:/projects/loader/.\build\install/lib/vulkan-1.lib
-- Up-to-date: D:/projects/loader/.\build\install/bin/vulkan-1.dll
-- Up-to-date: D:/projects/loader/.\build\install/lib/cmake/VulkanLoader/VulkanLoaderConfig.cmake
-- Up-to-date: D:/projects/loader/.\build\install/lib/cmake/VulkanLoader/VulkanLoaderConfig-debug.cmake
```
This allows find_package to work.
```
find_package(VulkanLoader)
target_link_libraries(foobar PRIVATE Vulkan::Loader)
```

cmake: Add find_package support

---

loader/loader.c
tests/loader_regression_tests.cpp

The check for a correct magic value in the device dispatch table used LOADER_MAGIC_NUMBER instead of DEVICE_DISP_TABLE_MAGIC_NUMBER. This causes every device creation to emit the 'invalid magic value' message, which is wrong. This commit fixes that, as well as adds the expected value to the log message.

Check correct magic value in device dispatch table

---

docs/LoaderDebugging.md

Surrounding text with ~ causes markdown to format the text with strike through, which is not intended. Surrounding the ~ with backticks instead of single quotes fixes it.

Use backtick instead of single quote in Loader Debugging

---

loader/loader.c

The warning message about the binary having the wrong bitness for ICD's was wrongly stating it was about layers having the wrong bitness.

Fix warning message refering to layers instead of ICDs

---

loader/vk_loader_platform.h

This should have been in the last update for iOS. The latest XCode flags an unused parameter as a warning, and warnings are treated as errors causes a failure in vk_loader_platform.h

XCode fix - warnings as errors and unused parameter triggers it

---

.github/workflows/codeql.yml

Closes #1300 
I've configured it to run on c files and python. 
For C, I've configured manually the build using as example the build.yml workflow. Let me know if I missed anything. There were only 10 findings on the codeql run.
As you said, I focused on the C build and just kept the python part because the autobuild was working well for it. Let me know if it would be better to drop it.

Enable CodeQL as SAST Tool

---

loader/cJSON.c
loader/cJSON.h
loader/loader.c
loader/settings.c

Prefixes the symbols that are used outside the file with `loader_` to match the others. Marks symbols that are not used outside as static.
Removes the symbols that are not used at all.
Prevents conflicts with other libraries that might also use cjson.
This may cause issues if the internal checkout of cJSON is updated, in that case, it may be simpler to just prefix all of cJSON's symbols with `loader_cJSON_`.
Please let me know if the suggested alternative of prefixing all the symbols instead if preferable or not.

loader/cJSON: Prefix/mark static/remove symbols

---

loader/cJSON.c
loader/loader.c
loader/settings.c
loader/settings.h

3 types of issues were found:
* Incorrect format specifiers
* Not providing required format specifies
* Using alloca in a loop
There are multiple instances of alloca in loops, but to fix them would require significant refactoring. This commit includes 1 move of alloca inside a for loop to the outside, but this is because the logic was redoing work in a for loop that could have been done once at the start of the function.

Fix problems detected by CodeQL static analysis

---

loader/CMakeLists.txt
loader/vulkan.pc.in

Currently this just will default to `include` IE it will default to system includes.
Which gcc already searches for:
https://stackoverflow.com/a/19839946/19739129
Now vulkan.pc will more closely match VulkanLoaderConfig.cmake

cmake: Remove CMAKE_INSTALL_INCLUDEDIR_PC

---

BUILD.gn

asm_offset.c only makes sense for an executable

gn: asm_offset.c shouldn't be compiled

---

.github/workflows/build.yml
loader/CMakeLists.txt

CMake's detection of MASM is very broken, especially if not using MSVC. This adds a check to see if MASM is working, and if not, disables it, going back to the fallback path, as intended.
@sfan5 can you check if this branch causes issues for you? I have tried with having uasm installed and not installed
Related to https://github.com/KhronosGroup/Vulkan-Loader/pull/1306

loader: Add check for working MASM compiler

---

CMakeLists.txt

The /sdl compiler option enables additional security checks that were previously not enabled.

Enable additional security checks for MSVC

---

loader/cJSON.c
tests/loader_alloc_callback_tests.cpp
tests/loader_regression_tests.cpp

Whenever an invalid JSON file was encoutered, the loader would return VK_ERROR_OUT_OF_HOST_MEMORY because it couldn't distinguish an invalid JSON file from the inability to allocate memory while parsing JSON. This commit adds the necessary logic to be able to tell the two conditions apart as well as adding rudimentary testing of it.
Fixes #1324

Distinguish OOM from json parsing errors

---

.github/workflows/build.yml
loader/CMakeLists.txt

Sets the patch version to 0 to avoid the linker warning
Enable warnings as errors on CI to prevent regression
closes #1332

apple: Fix incorrect version linker warning

---

.github/workflows/build.yml

Causes pushes to branches on forks to no longer trigger Github Actions.

Revert "ci: Prevent duplicate CI runs when pushing to repo"

---

.github/workflows/build.yml
BUILD.md

We only support the 2 latest MacOS releases similar to Ubuntu. Which CI is already doing.

ci: Remove MacOSX Deployment Target

---

loader/trampoline.c

The loader_init_dispatch first checks if the dispatchable handle has the ICD_MAGIC_VALUE before setting the handle to the correct dispatch pointer. This is useful to check that driver's are correctly creating the handle using VK_LOADER_DATA.
Because layers are capable of wrapping handles, the loader_init_dispatch function should only be called in terminators which run before any layers have a chance to modify the ICD_MAGIC_VALUE. Otherwise the assert fails.
vkGetDeviceQueue & vkGetDeviceQueue2 uses loader_set_dispatch, which does the same code as loader_init_dispatch but without the assert.
This commit changes vkAllocateCommandBuffers to use loader_set_dispatch.

Dont assert in vkAllocateCommandBuffers

---

loader/trampoline.c

pCreateInfo must not be NULL, but the loader was dereferencing the pointer before checking if it is NULL. Moving the dereference below the check for NULL ensures no nullptr dereferencing occurs.

Check for nullptr in vkCreateInstance trampoline

---

CMakeLists.txt
loader/CMakeLists.txt

WIN32/Apple doesn't support these functions

cmake: Fixing unsecure environment warnings for MinGW/Apple

---

loader/loader.c

The fixed issue can cause vkCreateInstance to return `VK_SUCCESS` even when it failed which has all sorts of catastrophic consequences.
In particular, the VVL test case `NegativeInstanceless.InstanceExtensionDependencies` can enter a deadlock as a result of some side effects of the issue.

Fix instance create swallowing error

---

loader/CMakeLists.txt

cmake: Fix x86 / x64 check

---

loader/debug_utils.c
loader/loader.c
loader/loader_common.h
loader/loader_linux.c
loader/log.c
loader/log.h
loader/trampoline.c

After a layer calls down to vkCreateInstance, it may need to create a DebugUtils Messenger (or Report object) for capturing debug information. With the old design, it would get handled as a "during vkCreateInstance" debug utils messenger object because the loader trampoline was still in the middle of "vkCreateInstance".  However, treat it separately if it was created with a call to vkCreateDebugUtilsMessenger and that allows it to capture info all the way until the instance is destroyed.

Fix Debug callbacks in layers in vkCreateInstance

---

loader/CMakeLists.txt

My earlier error checking was too agressive and doesn't allow for building a universal binary at all.
Move the error check inside of USE_GAS so it's clear to the user what to do (IE disable GAS if building a univeral binary)

Allow building a universal binary

---

docs/LoaderDriverInterface.md

Linux drivers use the ".so" extension, not ".dylib"

Fix typo in LoaderDriverInterface.md

---

loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/loader.c
loader/log.c
scripts/loader_extension_generator.py
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/loader_get_proc_addr_tests.cpp

The logic of the function indicates that at a previous time, the functions being loaded used dlsym/GetProcAddress to query functions. Whenever that was changed to vkGetInstanceProcAddr, the error logging wasn't updated to remove loader_platform_get_proc_address_error. Trying to call dlerror() when no error has occured will return NULL, which was dutifully passed onto loader_log, causing crashes.
The cleanup removes usage of that, as well as making the loading logic uses 2 macros, one for required & one for non-required function pointers.

Cleanup loader_icd_init_entries

---

loader/loader.c

Old messages were clunky and lacked helpful info like which driver failed and the error code returned by the driver.

Improve warning message from terminator_CreateInstance

---

loader/settings.c
tests/framework/data/fuzzer_output.json
tests/framework/framework_config.h.in
tests/loader_settings_tests.cpp

A few error conditions weren't properly handled whenever the settings file is invalid. Added the exact json file which caused the errors, then fixed issues with releasing memory properly.

Fix settings file crash found through fuzzers

---

loader/generated/vk_loader_extensions.c
scripts/loader_extension_generator.py
tests/loader_phys_dev_inst_ext_tests.cpp

This is makes the code gen for VK_EXT_acquire_drm_display be in line with the wsi code whenever calls to drivers are made which do not support the given extension.

Instance extensions unsupported by physical devices now return ERROR_EXTENSION_NOT_PRESENT

---

loader/loader.c

Makes it clear which layer type is being searched for in any given set of paths.

Specify which layer type is being searched in log

---

CMakeLists.txt
tests/framework/shim/windows_shim.cpp

By using CMAKE_CXX_COMPILER_FRONTEND_VARIANT, CMake will now distinguish clang from clang-cl, allowing the correct command line argument formats to be used.
Making tests work required fixing up windows_shim.cpp's usage of wcscpy since that was triggering deprecation warnings. A simple for loop was used instead.
Fixes #1402

Support Clang with GNU interface on Windows

---

loader/cJSON.c
loader/cJSON.h
loader/loader.c
loader/loader.h
loader/loader_common.h
loader/loader_windows.c
loader/settings.c
loader/settings.h
loader/trampoline.c
loader/vk_loader_platform.h
tests/live_verification/CMakeLists.txt
tests/live_verification/time_dynamic_loading.cpp
tests/loader_regression_tests.cpp

The loader did not unload any ICD's which contained zero physical devices, which
could cause premature exhaustion of memory in some circumstances, like 32 bit
applications. While the policy of the loader has been to keep things open for
the duration of the instance, these ICD's don't meaningfully participate in
anything due to the lack of VkPhysicalDevices.
This change adds a check after vkEnumeratePhysicalDevices where pPhysicalDevices
is not NULL such that all loader_icd_terms which reported zero physical devices
have its vkDestroyInstance called, and removed from the loader_instance's
icd_term linked list.
Fixes #1338

Unload drivers which report 0 physical devices

---

.github/workflows/build.yml
loader/CMakeLists.txt

Currently libvulkan.1.3.0.dylib gets installed instead of libvulkan.1.3.273.dylib
This fixes that while keeping the fix for the linker warning.

Fix version installation of vulkan-loader

---

loader/extension_manual.c

The bad pattern was detected using clang/gcc but only on linux, so the win32 code path never saw the fix.

Fix wrong pointer casts in win32 surface code

---

.github/workflows/build.yml
tests/CMakeLists.txt
tests/integration/CMakeLists.txt

Test find_package(VulkanLoader CONFIG)
Minimal vulkan.pc testing is also added.

Add integration testing

---

CMakeLists.txt
loader/CMakeLists.txt
scripts/generate_source.py
tests/CMakeLists.txt
tests/framework/CMakeLists.txt
tests/framework/shim/CMakeLists.txt
tests/live_verification/CMakeLists.txt
tests/live_verification/dynamic_loader_behavior/CMakeLists.txt

By default the loader only requires the C compiler.
But by default the C and CXX compilers are enabled.
Only enable the C compiler. Move corresponding C++ code into tests directory.

Only require C compiler

---

.github/workflows/build.yml
.github/workflows/codeql.yml
BUILD.md
CMakeLists.txt

Consistent naming with other repos we maintain.
OFF by default to avoid issues with newer compilers, specific generators (Xcode), etc.

BUILD_WERROR OFF by default

---

CMakeLists.txt
loader/CMakeLists.txt
loader/generated/vk_layer_dispatch_table.h
loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/loader.c
loader/terminator.c
loader/trampoline.c
loader/vk_loader_platform.h
scripts/CMakeLists.txt
scripts/generate_source.py
scripts/known_good.json
scripts/loader_extension_generator.py
scripts/loader_genvk.py
tests/framework/icd/test_icd.cpp
tests/framework/shim/shim.h
tests/framework/shim/windows_shim.cpp
tests/loader_handle_validation_tests.cpp
tests/loader_regression_tests.cpp

API variant parameterization changes to the loader analogously to other Vulkan ecosystem components.

build: API parameterization changes

---

loader/vk_loader_platform.h
tests/framework/framework_config.h.in
tests/framework/shim/shim.h
tests/framework/shim/unix_shim.cpp
tests/framework/test_util.h
tests/loader_envvar_tests.cpp
tests/loader_regression_tests.cpp

These changes fix the following:
- Adds `__ppc64__` and  `__aarch64__` to 64-bit specific code paths that didn't include it before
- Adds `__QNX__` to POSIX specific code paths that didn't include it before
- Other miscellaneous QNX build issues caused by preprocessor redefinitions, non-existent variables being referenced, and incorrect types being used
In general, all these changes target fixing QNX and 64-bit ARM builds.
@mgorchak-blackberry, FYI.

loader: Miscellaneous platform-specific fixes

---

loader/CMakeLists.txt

Ubuntu 20.04 saw a regression that caused the pthread library to no longer be a part of libvulkan.so's linked libraries. This didn't cause the loader to fail to load, rather any library that used pthread functions without linking to pthreads themselves would fail to run, for example the Vulkan-ValidationLayers (VVL). While it is currently unclear why VVL were trying to link to these symbols, this would make loading validation layers impossible.
The issue turns out to be this line of CMake
`set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)`. Specifically, that line of code appearing *before* `find_package(Threads REQUIRED)` causes CMake to 'find' CMAKE_HAVE_LIBC_PTHREAD successfully, whereas previously it would fail. Since this variable indicates that linking to libc is enough to get …

Fix lack of pthread linking in ubuntu 20.04

---

loader/trampoline.c

When running CTS test `dEQP-VK.api.device_init.create_instance_name_version.basic` the loader would complain about the `apiVersion` being 0 when that's a valid value

loader: Check apiVersion is not 0 for VUID-VkApplicationInfo-apiVersion

---

loader/loader_windows.c

By removing the current directory from the search paths for dlls, the loader is less vulnerable.

Remove current directory from DLL searching

---

docs/LoaderDriverInterface.md
docs/LoaderLayerInterface.md
loader/loader.c
loader/loader_windows.c
tests/framework/test_environment.cpp
tests/loader_regression_tests.cpp

Expand Windows system search path for layers to include AppX/MSIX
packages currently scanned only for ICD manifests.

Add app package to layers search path

---

loader/CMakeLists.txt

Disabled by default, user must explicitly with `-DUSE_GAS`. Also fixed build error with Clang+LTO+GAS.

loader: allow GAS on MinGW

---

loader/CMakeLists.txt
scripts/known_good.json

Given the MASM present does not compile on Windows ARM64, we need to fall back to using the GAS .S files for the unknown ext chain.
Sadly this restricts us from using MSVC as the compiler, but clang-cl is perfectly happy to compile the GAS assembly, which gives us a working binary with all tests passing on ARM64 devices, that is compatible with MSVC.
This was tested on a windows ARM64 device in a vcvarsall window, with clang-cl on the path, with the following command line:
```
mkdir build
cd build
cmake .. -G"Ninja" -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DUSE_GAS=ON -DUPDATE_DEPS=ON -DBUILD_TESTS=ON
cmake --build .
ctest
```
A small note though, I did have to update `detours` to the latest commit on master, which contains fixes for a few ARM64 bugs - I did not have …

loader: Enable building of GAS .S files on Windows ARM64

---

tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_get_proc_addr_tests.cpp
tests/loader_phys_dev_inst_ext_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_unknown_ext_tests.cpp

Fixed a few bugs resulting in some tests not running everything they were intended to, remove dead code, simplify codepaths, etc.
This was done using code coverage to find test code which wasn't being executed.

Cleanup tests

---

loader/loader.c
loader/loader_windows.c
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/loader_regression_tests.cpp

If any driver returned non-VK_SUCCESS values (except for OOHM) when the loader calls vkEnumeratePhysicalDevices, it would give up and return immediately. This could result in perfectly functional drivers being ignored.
The solution is to just skip over drivers that return non-VK_SUCCESS.

Gracefully handle error results from vkEnumeratePhysicalDevices

---

loader/generated/vk_loader_extensions.h
loader/loader.c
loader/trampoline.c
scripts/loader_extension_generator.py
tests/framework/layer/test_layer.cpp
tests/framework/layer/test_layer.h
tests/loader_layer_tests.cpp

Layers that want to call other global functions during vkCreateInstance couldn't due to loader_gpa_instance_terminator missing the necessary logic. Because those global functions have a different signature, it was decided to update the terminator_<function> signatures to match the Vulkan API, and make dedicated pre-instance intercetpion functions with the appropriate Chain object as the first parameter.
Now during the call down to vkCreateInstance a layer can query for pre-instance functions with vkGetInstanceProcAddr and is able to call them using the Vulkan API function signature.

Allow layers to call global functions in vkCreateInstance

---

tests/framework/CMakeLists.txt
tests/framework/test_util.h

When using multi-config build systems such as MSVC, it was possible for the framework_config.h to not be updated properly, resulting in the wrong binaries being used during testing. By ditching the common header file and directly specifying the header file to use through a compiler definition, the code is now shorter and more reliable.

Fix tests framework_config.h to work all the time

---

tests/framework/README.md
tests/framework/icd/test_icd.h
tests/framework/layer/test_layer.h
tests/framework/shim/shim.h
tests/framework/shim/shim_common.cpp
tests/framework/shim/unix_shim.cpp
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_environment.h
tests/framework/test_util.cpp
tests/framework/test_util.h
tests/loader_alloc_callback_tests.cpp
tests/loader_envvar_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_settings_tests.cpp
tests/loader_testing_main.cpp
tests/loader_version_tests.cpp

Removes code and makes the codebase more understandable (by not introducing weird behavior unique to fs::path).
Replaces a lot of the bespoke logic to handle string<->wstring due to using std::filesystem::path.

Use std::filesystem instead of custom fs::path

---

loader/loader.c
tests/loader_regression_tests.cpp

strcmp has undefined behavior if either parameter is NULL. Due to clearing out unloaded entries, this would cause unload_drivers_without_physical_devices to try to compare against already unloaded entries.
This commit also condenses the preloaded_icds list so that it doesn't contain gaps.

Check for NULL in unloading of preloaded-icd's

---

loader/CMakeLists.txt

loader-unknown-chain is now a STATIC library instead of an OBJECT library. Object libraries have limitations compared to 'normal' libraries, and this simplifies the CMake usage present.
This change includes a fix for building using Ninja, as there is a bug in cmake related to static libraries that contain assembly code that affect builds using MSVC and clang-cl.

Change loader-unknown-chain into a STATIC library

---

BUILD.gn

The phys_dev_ext.c and dev_ext_trampoline.c are only needed when compiling assembly support for unknown functions in, which is not the case for the GN builds. Doing that causes linker failues which are resolved with this fix.

Fix GN build by removing unnecessary files

---

loader/loader.c

During unloading of unused drivers, the loader checks for the driver in its list of preloaded ICD's, and removes it if it is in it. If the user provided a custom callback during instance creation, this was being used during this unloading, which is wrong because preloaded icd's weren't allocated with the custom allocator in the first place.

Fix preloaded icd's being freed with custom allocators

---

.github/workflows/build.yml

This reverts commit 1bae807cd919890f7174fa14228b6e672e8d296e.
Images appear to be fixed upstream

Revert "ci: Disable GHA windows build until image is fixed"

---

.github/workflows/build.yml

macOS 11 is being removed from github actions.

Update CI to macOS 12

---

.gitignore
BUILD.md
loader/CMakeLists.txt
loader/asm_offset.c
loader/asm_test_aarch32.S
loader/loader.c
loader/unknown_ext_chain_gas_aarch.S
scripts/parse_asm_values.py

This allows linux loaders built for armhf architectures to support unknown
physical device and device functions. The previous fallback path could have
worked for armhf (using the appropriate compiler flags) so as to not disrupt
users, the aarch64 assembly code for unknown functions was ported to armhf.
Since CI support is limited, this was manually built & tested using on a
raspberry pi 4B.

Add unknown functions assembly code for linux-armhf 

---

loader/loader_windows.c
tests/framework/shim/windows_shim.cpp

While the application still can run, RegCloseKey will throw an error when key is double-closed. This was caused by the test framework not catching when the double-close occurs.

Fix RegCloseKey exeption when double-closing hKeys

---

loader/loader.c

The notice that renaming vkGetInstanceProcAddr and vkGetDeviceProcAddr functions in the layer manifest is deprecated will now only be printed if the layer does not also rename the vkNegotiateLoaderLayerInterfaceVersion function.

Make layer interface deprecation notice conditional

---

loader/loader_windows.c

The removal of the current directory from windows Dll searching then using the default search paths caused a crash in a shipping application. This requires removal of the offending calls while a better solution for making LoadLibrary not use the current directory is developed.

Remove SetDllDirectory as it caused crashes

---

loader/loader_windows.c

LoadLibraryEx allows specifying where to search for dll's, including system only paths which is useful for guaranteeing the authenticity of a loaded dll, which is gdi32.dll in our case.

Only search system32 for gdi32.dll

---

loader/unknown_ext_chain_gas_aarch.S

Enable Pointer Authentication Codes (PAC) and Branch Target Identification (BTI) support for ARM 64 targets.
PAC works by signing the LR with either an A key or B key and verifying the return address. Since the assembly code does not push and pop the link register to the stack, and it remains in the register file, their is no need to sign the LR, so PAC is essentially just adding it to the GNU notes section for auditing purposes.
BTI works by marking all call and jump positions with bti c and bti j instructions. If execution control transfers via an indirect branch or call to an instruction other than a BTI instruction, the execution is killed via SIGILL.
For BTI to work, all object files linked for a unit of execution, whether an executable or a library must have the GNU Notes section of …

aarch64: enable PAC/BTI

---

BUILD.gn
loader/unknown_ext_chain_gas_aarch.S
loader/unknown_ext_chain_gas_x86.S
scripts/gn/secondary/build_overrides/vulkan_loader.gni
scripts/parse_asm_values.py

The GN build doesn't currently support unknown function trampolines. To fix that, we can use the assembly trampolines. To generate the asm_offset assembly file, we can build it in a static library and pass -S to it; that causes the assembly file to be copied into the .a file. The python script can then extract it. This requires access to the "ar" executable, so this mechanism is only used if a path to ar is specified in //build_overrides/vulkan_loader.gni.
To fix incremental builds, "gen_defines.asm" must be included using "#include", not ".include", since .include isn't a preprocessor directive and isn't picked up by clang's depfile creation.

Use ASM unknown function trampolines on GN

---

CMakeLists.txt
loader/generated/vk_loader_extensions.c
loader/loader.c
loader/loader.rc
loader/loader_common.h
scripts/known_good.json
scripts/loader_extension_generator.py

loader_extension_generator.py needed a tweak to handle boolean logic in the vk.xml extension dependency attributes

build: Update to header 1.3.293

---

loader/wsi.c
tests/framework/icd/test_icd.cpp
tests/loader_get_proc_addr_tests.cpp

The loader would unwrap the first surface and use that for all created swapchains rather than unwrap each surface handle individually for each VkSwapchainCreateInfoKHR struct.

Fix vkCreateSharedSwapchainsKHR not unwrapping handles correctly

---

docs/LoaderLayerInterface.md
loader/loader.c

The vkGetInstanceProcAddr function was ammended in header version 1.2.193 to require global functions be queried with NULL instance parameters, including vkCreateInstance. Layers written before that time may not expect the instance parameter to be NULL, so in order to maintain compatibility, the loader code (which itself dates to before Vulkan's public release) is left unmodified.
Instead, code comments were left to indicate the non-spec compliant implementation as well as documentation in the LoaderLayerInterface mentioning how layers should handle the now invalid API usage.
In the future, the loader could be modified to correctly follow the spec, but a survey of existing and previous layer implementations would need to be done to determine the impact of the change.

Document layer requirements for querying vkCreateInstance from GIPA

---

loader/wsi.c
loader/wsi.h

All of the VkIcdSurface<API> members, as well as the *_size & offset members are unused by the codebase. And drivers do not have access to this struct, as it is internal to the loader - no common definition exists elsewhere for drivers to use either.

Remove unused VkIcdSurface struct members

---

docs/LoaderInterfaceArchitecture.md

The original text was caused by a mistake during rebase which wasn't caught. This commit take the original non-mistake text and cleans that up further.

Fixup note for VK_DRIVER_FILES env-var

---

CMakeLists.txt
loader/dirent_on_windows.c
loader/loader.c
tests/framework/icd/CMakeLists.txt
tests/framework/icd/export_definitions/🌋.def
tests/framework/shim/unix_shim.cpp

Certain file systems (such as bcachefs) use 64 bit inodes, which glibc truncates to 32 bits by default. This causes EOVERFLOW to be returned from readdir, causing not all files to be read from a directory.
The fix is to use the 64 bit versions of file system access functions, by defining _FILE_OFFSET_BITS=64 in 32 bit builds.
Because this issue does not affect 64 bit builds, it is only applied to 32 bit builds.

Define _FILE_OFFSET_BITS=64 for 32 bit linux builds

---

loader/loader.c
loader/loader.h
loader/loader_windows.c
loader/vk_loader_platform.h

Defer all other initialization of the loader internals to after the call to DllMain by using InitOnceExecuteOnce, mirroring the initialization needed for statically linked MacOS.
This required splitting up the mutex creation and other initialization into its own function, and having DllMain call that function, while on linux loader_initialize will call that function first thing.
This commit makes the loader follow Dynamic-Link Library Best Practices as defined by Microsoft from the following article:
https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices

Only initialize mutexes during DllMain

---

loader/loader.c
loader/loader_common.h
loader/wsi.c
tests/framework/icd/physical_device.h
tests/framework/icd/test_icd.cpp
tests/framework/test_util.h
tests/loader_wsi_tests.cpp

The VK_EXT_surface_maintance1 extension is an instance level extension, which means the loader will advertise support for it when at least one driver supports it. However, there is presently no way for an application to know which VkPhysicalDevice's will fill out the structs the extension defines and which VkPhysicalDevice's will ignore the structs.
Add support for testing the surface_maintenance1 implementation - making sure that a driver which supports the extension isn't affected and correctly filling out the structs for drivers which do and do not support vkGetPhysicalDeviceSurfaceCapabilities2KHR as well.

Emulate VK_EXT_surface_maintenance1 if not supported by a driver

---

loader/debug_utils.c
loader/loader.c
loader/loader_linux.c
loader/terminator.c
loader/wsi.c

Replaces dubious type punning to VkBaseIn/OutStructure into correct mempcy to a local VkBaseIn/OutStructure in order to access the sType safely.
This commit changes only the simple locations of the type punning. The more difficult situations aren't being tackled here, since those situations insert elements into the pNext chain, modifying it in the process.

Use memcpy to access sType in pNext chains

---

.github/workflows/build.yml

macos-12 runners are being deprecated.

Update github actions to macos-13

---

loader/CMakeLists.txt

This fixes this error message appearing when building on linux/armv7l or linux/armv8l:
```
CMake Warning at loader/CMakeLists.txt:368 (message):                                                                         
Could not find working armv8l GAS assembler                                                                                 
Support for unknown physical device and device functions is disabled due to missing the required assembly support code.
To support unknown functions, assembly must be added for the platform.
```
(Noticed this issue building 1.3.300 on linux Chromebrew/armv7l.)

Add armv7l/armv8l support to loader/CMakeLists.txt

---

loader/cJSON.c

This fixes an issue found by OSS-Fuzz: https://issues.oss-fuzz.com/issues/42529964
I noticed that there are no maintainer emails in the OSS-Fuzz `project.yaml`. https://github.com/google/oss-fuzz/blob/master/projects/vulkan-loader/project.yaml -- I'm happy to add any maintainer emails as that would give access to the bugs found/reported by OSS-Fuzz. Let me know if you'd like any emails in the `project.yaml` and I'll add them.

cjson: add NULL check prior to strcmp

---

loader/loader.c
loader/log.c
loader/settings.c
tests/framework/shim/shim.h
tests/framework/shim/unix_shim.cpp
tests/framework/shim/windows_shim.cpp
tests/framework/test_environment.cpp
tests/framework/test_util.h
tests/loader_settings_tests.cpp

* Fix VK_INSTANCE_LAYERS bug when using vk_loader_settings.json - stack allocated variable would be indexed past the end of the array if more than 1 layer was present in the settings file, causing garbage to be read as a string.
* Make vkEnumerateInstanceExtensionProperties return VK_INCOMPLETE correctly - When some layers are turned "off" in the settings file, the count of layers would be correct but VK_INCOMPLETE would be returned by mistake.
* Intercept loader_log in Test Framework - allows seeing the output of VK_LOADER_DEBUG & the loader settings file log settings output directly, rather than going through the Debug Utils Messenger.
* Re-enable readdir interception on MacOS which was disabled so address sanitizer could work, which no longer seems to be needed.

Loader settings bug fixes and expanded test coverage

---

loader/loader.c
loader/loader.h
loader/trampoline.c
tests/loader_settings_tests.cpp

The loader_scan_for_implicit_layers function was not removing inactive layers
from the list of layers gotten from the loader settings file. This caused
layers with pre-instance functions to loaded and executed.
For example, layers with an enable-environment field shouldn't be
loaded unless their respective env-var was set.
This lack of filtering didn't change the list of layers active during
vkCreateInstance, but does cause adverse side effects during pre-instance
API function calls.
Also: Reuse library loading code in pre-instance functions
The functions vkEnumerateInstanceExtensionProperties,
vkEnumerateInstanceVersion, and vkEnumerateInstanceLayerProperties have no
strong reason for duplicating the the logic to load and unload libraries.
This commit re-uses existing facilities to …

Fix layers with pre-inst funcs from being loaded erroneously

---

CMakeLists.txt
loader/CMakeLists.txt

A recent fix to CMake for ASM static libraries on Windows broke the existing build.
Easiest solution I found is to remove the usage of ASM static libraries from the loader.
This is already what the UNIX build does.
This required using generator expressions to NOT pass along compiler options that aren't needed for assembly files.

Fix CMake 3.31 builds for WIN32

---

loader/log.c
loader/log.h
loader/settings.c
tests/loader_settings_tests.cpp

* Log Settings file Stderr Log Filters
This commit also pulls out the logic that loader_log uses to create the
ERROR | WARNING | <etc> string so that it can be reused in the logging
of the settings file stderr filters. To accomplish this, the logic was
changed slightly to assume that all debug masks are possible. This also
means adding an assert to make sure loader_log isn't called with
multiple flags set, just as a heads up that it isn't desireable.
The logging only occurs if any filters are set.
The settings file also now includes the type of layer in the log, either
explicit or implicit (based solely on the loader settings file value of
treat_as_implicit_layer).
* Make Settings file "ON" take priority over disable env-var
The VK_LOADER_LAYERS_DISABLE env-var was disabling layers even …

Settings takes priority over layers disable env var

---

loader/settings.c

This prevents VK_LOADER_DEBUG from being ignored when the settings file lacks stderr_log.
Fixes #1601

Only set global debug level from settings if above 0

---

loader/loader_windows.c
loader/settings.c

While there was logic to check if the vk_loader_settings.json file existed, it was not being run at an appropriate time and with another expression that caused the check to never happen.
This commit also logs that the loader fails to find the loader settings file, and if it finds a registry entry, if the file doesn't exist.
Fixes #1600

Correctly check if settings file exists on windows

---

loader/loader.c
loader/loader_common.h
loader/loader_environment.c
loader/settings.c

Adds information about how each layer was enabled, useful for debugging when you are not sure *what* caused a layer to be enabled (in-application API, different environment variables, vkconfig, implicit layer, etc).

Log what caused each layer to be enabled

---

loader/settings.c
tests/loader_settings_tests.cpp

The logging to indicate that VK_LOADER_LAYERS_ENABLE and VK_LOADER_LAYERS_DISABLE turned on/off layers was not occuring when the settings file was active. This is due to layer enablement being done in `enable_correct_layers_from_settings()`, a newer function. which lacked the log functions.
This commit rectifies the lack of logging in the new function.

Log when Filter Env-Vars act when settings file is active

---

BUILD.gn
scripts/generate_loader_rc.py

This is a fix to issue #1571 , Vulkan-Loader/Loader/Loader.rc lists dll as dev build.
In this change, a new loader.rc file is created based on the checked in one and "Dev Build" suffixes are removed for official builds. This makes it so that all chromium based browsers don't ship a vulkan-1.dll with properties that show it to be dev builds.

In chromium official builds remove dev build marking from vulkan-1.dll

---

loader/cJSON.c

If the initial calloc failed then NULL was being returned but the out_of_memory flag was not being set, so callers did not understand the returned value correctly. Set the flag.

Fix out-of-memory case in cJSON

---

loader/wsi.c

These warnings would be printed when any struct not explicitely looked for appeared in the pNext chain of GetPhysicalDeviceSurfaceCapabilities2KHR's in the emulation of VK_EXT_surface_maintenance1, which only looked for a small subset of the possible structs that could be in the chain.

Remove false positive unknown chain member warnings

---

loader/wsi.c

The emulation function does not comply with specifications. The spec asks ```The implementation must include the present mode passed to VkSurfacePresentModeEXT in pPresentModes, unless presentModeCount is zero.``` But now the implementation here will always include the present mode regardless of whether presentModeCount is zero.
According to spec ```If the value of presentModeCount is less than the number of compatible present modes that are supported, at most presentModeCount values will be written to pPresentModes.``` When presentModeCount is 0, at most 0 values will be written to pPresentModes, in other words the implementation should do nothing in this situation.
This commit fixed the above issue.

Make emulate_VK_EXT_surface_maintenance1 more comply to vk spec

---

loader/extension_manual.c
loader/loader.rc
loader/wsi.c
scripts/loader_extension_generator.py
tests/framework/icd/test_icd.cpp
tests/framework/test_environment.cpp
tests/loader_wsi_tests.cpp

Requires bypassing the logic which dereferences VkSurfaceKHR in
vkGetPhysicalDeviceSurfaceFormatsKHR and
vkGetPhysicalDeviceSurfacePresentModesKHR. This should have been done
closer to the release of VK_GOOGLE_surfaceless_query, but because that
extension was meant for Android, which isn't supported by this loader,
it was not done. That said, SwiftShader can support the extension, so
support is now being added in this commit.

Support VK_GOOGLE_surfaceless_query 

---

loader/loader.c
tests/framework/test_environment.cpp
tests/loader_regression_tests.cpp

If the loader happens upon a layer/ICD manifest while searching for manifests of the opposite type, do not emit warnings. These are spurious and only cause users to think something is wrong with the installation when it is actually fine.

Silence warnings for wrong manifest type

---

.github/workflows/build.yml
.github/workflows/codeql.yml
BUILD.md
CMakeLists.txt
tests/CMakeLists.txt
tests/integration/CMakeLists.txt

Matches Vulkan Validation Layers and SPIRV-Tools.

cmake: Update minimum version to 3.22.1

---

loader/settings.c

Changes the logic of the loader settings file to allow settings files which just the stderr_log. This means settings that do not with to alter the layers can be achieved.

Allow settings with only debug logging to work

---

docs/LoaderDebugging.md
docs/LoaderDriverInterface.md
docs/LoaderLayerInterface.md
loader/log.c
loader/log.h
loader/settings.c
tests/loader_settings_tests.cpp

This makes it clear *who* is creating log messages, which wasn't as clear
before.
This branch refactors the logging code to be easier to understand.
Also, updates docs to reflect changes in log output.
Example output with changes:
```
[Vulkan Loader] INFO:           Vulkan Loader Version 1.4.307
[Vulkan Loader] INFO:           [Vulkan Loader Git - Tag: improve_debug_log_messages, Branch/Commit: v1.4.307-6-gd9c615ac8]
[Vulkan Loader] INFO:           No valid vk_loader_settings.json file found, no loader settings will be active
[Vulkan Loader] INFO:           Found manifest file /etc/vulkan/implicit_layer.d/renderdoc_capture.json (file version 1.1.2)
```

Prepend [Vulkan Loader] to stderr log output 

---

loader/loader.c
loader/loader_environment.c
loader/loader_environment.h

Function definitions / declarations without specifying the argument types are deprecated in all C versions and may trigger compiler warnings (-Wstrict-prototypes).
This change replaces all `function()` definitions and declarations with `function(void)`.
Test: Vulkan-Loader builds on Fuchsia with Wstrict-prototypes enabled.
Bug: https://fxbug.dev/378964821

loader: Explicitly specify argument types

---

BUILD.gn

`chromium_code` and `no_chromium_code` are GN config targets defined in the chromium repository. Non-Chromium GN builds don't have these targets and GN will fail parsing them.
This change modifies Chromium-specific configs so that they are only applied on Chromium builds.
Test: Vulkan-Loader builds on Fuchsia (also with other changes)
Bug: https://fxbug.dev/378964821

build: Fix Chromium-specific configs in BUILD.gn

---

loader/loader.c
loader/settings.c

Previously in the loader code, there were some function arguments and variables of `char *` type that stores string literals. This triggers compiler warnings when `-Wwrite-strings` is enabled (which is enabled by default if compiling C++).
This change replaces `char*` with `const char*` for such variables and arguments.
Bug: https://fxbug.dev/378964821

loader: Use "const char*" for string literals

---

BUILD.gn

On GN-based linux-x64 builds, with the _GNU_SOURCE definition, the compiler will now have readlink() and strtok_r() declared.
This is consistent with the build configurations defined in loader/CMakeLists.txt.

gn: Add _GNU_SOURCE definition to Linux builds

---

loader/allocation.h
loader/extension_manual.c
loader/generated/vk_loader_extensions.c
loader/wsi.c
loader/wsi.h
scripts/loader_extension_generator.py
tests/framework/test_environment.cpp

Fixes https://github.com/KhronosGroup/Vulkan-Loader/issues/1541.
This is marked as draft, because there are some open questions:
- Do we want to have code-gen for the surface create info structure chain copies? I had to do a separate copy, because the currently captured create parameters are not complete, and there's one NVIDIA extension struct for surface creation which requires chained copies. They don't get modified often, but code-gen would be a more future proof solution
- I had to modify the test framework, because the `sType` of surface create infos were not set before and now the new code expects correct input, not invalid (due to the create info copies). I hope that's okay.

loader: Lazily allocate ICD surface objects

---

tests/framework/icd/test_icd.h
tests/framework/layer/layer_util.h
tests/framework/layer/test_layer.h
tests/framework/test_environment.h
tests/framework/test_util.h

Changes BUILDER_VALUE & BUILDER_VECTOR to deduce the return type, so the class name doesn't need to be given.
Changes BUILDER_VALUE to default everything with {}, and adds BUILDER_VALUE_WITH_DEFAULT for the places that want a specific default value instead.

Cleanup BUILDER_VALUE macros in tests

---

.github/workflows/build.yml
BUILD.md

ci shouldn't have to use the 32 bit version of pkg-config.
I tracked it down the problem is in CMake. Specifically FindPkgConfig.cmake
I listed the issue in the yml and docs for reference to make it clear that it is a CMake bug.

ci: Use PKG_CONFIG_PATH instead of 32 bit pkg-config

---

BUILD.gn

KhronosGroup/Vulkan-Hpp#2020 added `vk::PFN_...` function pointer types as the preferred function pointers used in vulkan.hpp structs and functions.
These function pointer types use C++-styled types for the function arguments and return values, so the compiler treats them as types different from the C-styled "PFN_...` function pointers types. Vulkan-Hpp guarantees that they are binary identical during compile time, but UBsan's function sanitizer trigger a "function pointer type different" runtime error when these function pointers are invoked in the Vulkan-Loader (for example, debug_utils.c and allocation.c) -- see KhronosGroup/Vulkan-Hpp#2082 for example.
This change disables the function sanitizer from the Vulkan-Loader (where the function pointers are invoked) so that Vulkan …

gn: Disable function UBsan check to support new vulkan.hpp function pointers

---

loader/wsi.c
loader/wsi.h
tests/framework/icd/test_icd.cpp

The pAllocator passed into each surface creation function would be a
pointer to the instance's pAllocator callbacks, regardless of whether
they were valid.
This commit saves the VkAllocationCallbacks passed into the surface
create function so that it can be used when the surface handle is
actually created in the driver.

Fix pAllocator in lazily allocated ICD surfaces

---

scripts/dispatch_table_helper_generator.py
scripts/generate_source.py
tests/framework/CMakeLists.txt
tests/framework/layer/vk_dispatch_table_helper.h

During the downstreaming of Vulkan-Loader 1.4.310 into Vulkan SC, we've found that:
- some of the refactoring doesn't work as intended
- some parts are easier to maintain downstream if handled slightly differently
- some parts appreciate minor fixing
To be precise:
- Hardcoded references to the name of `generated/` folders irrespective of api type always require downstream workarounds. It's far cleaner to handle them when it's not part of a huge literal, but a variable we can override in a snippet.
- `genCombined: True` is a safe default, but in these cases some need modification to not be permanent conflicts downstream.
- `tests/framework/CMakeLists.txt` has no quotes around `CMAKE_SOURCE_DIR` et al. but this variable really wanted to be PROJECT_SOURCE_DIR. Current script works only as …

Vulkan SC downstream fixes

---

loader/generated/vk_object_types.h
scripts/helper_file_generator.py

This information was missing in the initial VulkanObject rewrite, but has since been added.

Use VulkanObject aliases in codegen

---

.github/workflows/build.yml
.github/workflows/codeql.yml

Ninja is now available by default on the runner images: https://github.com/actions/runner-images/issues/11391
Only utilize lukka/get-cmake for testing an older CMake version.

Utilize pre-installed Ninja

---

loader/debug_utils.c
loader/generated/vk_loader_extensions.c
loader/generated/vk_loader_extensions.h
loader/loader.c
loader/loader_common.h
loader/terminator.c
loader/trampoline.c
loader/wsi.c
loader/wsi.h
scripts/loader_extension_generator.py

Loader now generates a struct that contains of bools for each instance
extension and a function to set the bool to true if the extension is in
the list passed in. This consolidates that logic into one place rather
than having it spread out across the codebase. It also enable further
changes that will require each drivers list of supported instance
extensions.
&
Make sure that the surface extension is supported by a driver and
enabled before calling down on each surface creation function. This
fixes crashes where a driver on the system doesn't support a surface
extension that the application is using but still exposes the function
pointer.

Refactor instance extension checks into single function  & Only call surface creation functions on supported drivers 

---

scripts/dispatch_table_helper_generator.py
tests/framework/layer/vk_dispatch_table_helper.h

There is not much benefit in formatting the generated code, especially since different clang-format versions handle line breaks differently, causing lots of noise when generating source code.
This also makes developing without clang-format to be a bit easier, since the generated code is already properly formatted (for the most part).

Disable formatting in generated test code

---

.github/workflows/build.yml

Currently, this job fails due to:
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - broken CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:67 (message):
The C compiler  "C:/msys64/mingw64/bin/cc.exe"   is not able to compile a simple test program.
The root cause is still unknown so it was decided to disable the CI check in the meantime.

Disable mingw CI job

---

loader/wsi.c
tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/loader_wsi_tests.cpp

wsi_unwrap_icd_surface() returns VK_ERROR_EXTENSION_NOT_PRESENT when the
surface extension isn't supported by an ICD. Which is a problem for
vkGetPhysicalDeviceSurfaceSupportKHR because its suppose to set the out
parameter to false, not return an error code. The fix is to not propagate VK_ERROR_EXTENSION_NOT_PRESENT
up from vkGetPhysicalDeviceSurfaceSupportKHR, simply set pSupported to false and return VK_SUCCESS.
Also makes improvements to test_icd.cpp and adds a test for this case (only valid on linux, where multiple surface extensions are easily used at the same time).
@aqnuep Not looking for a heavy review, more making sure you agree that vkGetPhysicalDeviceSurfaceSupportKHR had a bug and this is the fix for it.

Fix vkGetPhysicalDeviceSurfaceSupportKHR returning an error code

---

tests/framework/icd/test_icd.cpp
tests/framework/icd/test_icd.h
tests/loader_alloc_callback_tests.cpp
tests/loader_debug_ext_tests.cpp
tests/loader_envvar_tests.cpp
tests/loader_get_proc_addr_tests.cpp
tests/loader_layer_tests.cpp
tests/loader_phys_dev_inst_ext_tests.cpp
tests/loader_regression_tests.cpp
tests/loader_threading_tests.cpp
tests/loader_unknown_ext_tests.cpp
tests/loader_version_tests.cpp
tests/loader_wsi_tests.cpp

Requires extensive modifications to the tests since previously many tests accessed the physical device array directly.
The CreateDevice.ConsecutiveCreate test on linux-arm was taking +180s, with this PR only takes ~20s. 6x isn't a bad uplift (even if it is because of some naive test framework code being the culprit).

Speedup tests by putting physical devices in a map

---

loader/loader.c

This fixes compiling against musl libc:
```
loader/loader.c: In function 'normalize_pat':
loader/loader.c:405:52: error: 'PATH_MAX' undeclared (first use in this function)
405 |     char *path = loader_instance_heap_calloc(inst, PATH_MAX, VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE);
|                                                    ^~~~~~~~
```

loader: Include limits.h for PATH_MAX
