BUILD.md, loader/LoaderAndLayerInterface.md, scripts/loader_genvk.py
Remove references to the old repo. Also, remove ninja build steps
since they are no longer valid.
Change-Id: I4a963ec7dc49af2d7d0d186079f0aee78d110d70
=> docs: Remove references to old repo

loader/gpa_helper.h, loader/vulkan-1.def
=> loader: Fix up missing 1.1 function exports

cmake/Copyright_cmake.txt
https://gitlab.kitware.com/cmake/cmake/blob/master/Copyright.txt @ d45d5e2
=> cmake: update Kitware copyright

BUILD.md
Change-Id: I34fded0bcc970fd09640993ed4dfd67fbc29dcbe
=> docs: Remove vk_layer_dispatch_table.h from BUILD.md

scripts/update_deps.py
Makes `update_deps.py` consistent between repos.
=> Unify `update_deps.py` between repos

scripts/update_deps.py
Syncing changes made to update_deps.py
in Vulkan-ValidationLayers PR 285.
=> build: Sync update_deps.py

.appveyor.yml, .travis.yml, BUILD.md
Use a known good version of gtest for CI
=> tests: Use specific version of gtest for CI

loader/loader.c
This fixes the logic that finds ICDs and layers from within a Mac bundle. This change only effects Apple systems.
=> Fix mac bundle logic

tests/run_extra_loader_tests.sh
Fix #121
Change-Id: I2e060a3ddda3bf919d6be8a3e0af7169ac0fee63
=> tests: Flock the implicit layer test

scripts/known_good.json
Passed all loader tests and internal CI.
=> build: Update known-good for 1.1.100 header

scripts/known_good.json
This change passes all loader and Gerrit testing.
=> build: Update known-good for 1.1.101 header

scripts/common_codegen.py, scripts/known_good.json
Additionally, updated copyright dates and added Metal to the platform list
Updated:
- `scripts/common_codegen.py`
- `scripts/known_good.json`
=> build: Update known-good for 1.1.102 header

loader/loader.c
This fixes several issues, mainly related the logging within the loader.
This fixes #176, fixes #177, fixes #178, fixes #179, and fixes #180.
=> loader: Fix mishandling of loader logging

CMakeLists.txt
Change-Id: Ie05eeb1d7b880c20bd8c283b7fcc7c120d6f97eb
=> build: Update cmake_minimum_required(VERSION 3.11.3)

loader/LoaderAndLayerInterface.md
A couple of fairly cosmetic fixes.
=> Linux WSI fixes for docs

scripts/known_good.json
=> build: Update known-good for 1.1.114 header

loader/loader.c
i.e. fixes missing output where it is prematurely cut after first wchar
=> loader: Fix incorrect log handling of win32 wstrings

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
Additionally, ran `generate_source.py`.
=> build: Update known-good for 1.1.119 header

scripts/known_good.json
Change-Id: I964c1f61e92d6a83676dc402448258927d1c1369
=> build: Update known-good for 1.1.120 header

loader/CMakeLists.txt
fixes https://github.com/KhronosGroup/Vulkan-Loader/issues/223
=> loader/CMakeList.txt: use proper path for asm_offset

loader/CMakeLists.txt, loader/dxgi_loader.c, loader/dxgi_loader.h, loader/loader.c
=>  loader: Dynamically load DXGI

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
Changes:
- Updated known good files
- Generated new files using `generate_source.py`
Updated:
- `loader/generated/vk_dispatch_table_helper.h`
- `loader/generated/vk_layer_dispatch_table.h`
- `loader/generated/vk_loader_extensions.c`
- `scripts/known_good.json`
=> build: Update known-good for 1.1.124 header

scripts/known_good.json
Changes:
- Updated known good files
Updated:
- `scripts/known_good.json`
Change-Id: I35d7d7f7b06e9163f276bacce1dc4109d3cee630
=> build: Update known-good for 1.1.125 header

scripts/known_good.json
Change-Id: I176f2b46099c8636972b6d9c281397fe18b096ac
=> build: Update known-good for 1.1.126 header

loader/loader.c
This fixes #270.
A previous change started matching drivers from the HKLM registry against a list of known drivers. This change modifiers the behavior so that unrecognized drivers are used, instead of being dropped.
=> Don't drop unknown drivers

scripts/known_good.json
Change-Id: I4abc51b448f786b3633b6cfcba0c18f873bb684d
=> build: Update known-good for 1.1.127 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/known_good.json
Change-Id: I05a369dd1fa9db2a53884193c5740f105c62b197
=> build: Update known-good for 1.1.128 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
Change-Id: I4a16e33c467a266f84aa38cc699c1e26d44f5b7c
=> build: Update known-good for 1.1.129 header

loader/loader.c
=> Fix a bug found by clang's -Wsizeof-array-div.

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/known_good.json
=> Update for 1.1.130 header version

scripts/known_good.json
Change-Id: I8607a9a279525391298eb2aceb0078faa8f32fce
=> build: Update known-good for 1.2.132 header

loader/loader.c
Whenever a call to loader_secure_getenv() fails and returns a
NULL, the loader will now issue a warning that the environment
variable requested will be ignored.
Change-Id: I2ebdfad2f842cf3dda69a359da31124e6f1eabc2
=> loader: Warn when loader_secure_getenv() fails

loader/gpa_helper.h
=> Add core 1.2 functions to gpa_helper

loader/LoaderAndLayerInterface.md
The current description about the version number negotiation between
loader and layer is easy to cause disagreement, and the description
about the version number negotiation between loader and ICD is much
more readable, so I think it is better to adopt the same way as the
vk_icdNegotiateLoaderICDInterfaceVersion description to describe the
vkNegotiateLoaderLayerInterfaceVersion.
Signed-off-by: Wang YanQing <udknight@gmail.com>
=> docs: Improve vkNegotiateLoaderLayerInterfaceVersion's description

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
Updated `known_good.json` and generated new source files
=> build: Update known-good for 1.2.137 header

scripts/known_good.json
Change-Id: Ib5f2fab581fb98fa1391c8fde1009bb8bd1c09c7
=> Update known-good files for 1.2.141 header

loader/loader.c
The loader now loads the first ICD in an app bundle if one exists.
This is to prevent multiple copies of MoltenVK being loaded.
Change-Id: I1e4b8e854e5d709c6e229c9591f4a8856e3b2b41
=> loader: Use MoltenVK in app bundle if found

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/common_codegen.py, scripts/known_good.json
Changes:
- Added directfb to platform dictionary in `common_codegen.py`
Currently running through internal CI
=> build: Update known-good files for 1.2.146 header

build-gn/DEPS
Sync standalone GN toolchain revisions with current ANGLE revisions.
=> build: Roll GN DEPS file

loader/vk_loader_platform.h
Address Sanitizer (ASAN) is broken by the inclusion of RTLD_DEEPBIND. This commit
removes that dlopen flag if ASAN is detected during compilation.
Fixes #430 
Change-Id: Ibc3cc329b2f6335a3d5982691b6491efc8c3bbe9
=> loader: Make RTLD_DEEPBIND conditional on ASAN

scripts/known_good.json
=> build: Update known-good files for 1.2.147 header

scripts/known_good.json
=> build: Update known-good files for 1.2.148 header

loader/loader.c
Change-Id: Ic1649d72e71fe0b6ff0a950e30e18feb387f5919
=> loader: fix override paths leaking in VerifyAllMetaLayers

loader/loader.c
See issue description.
fix #445
=> loader: fix memory leak of failed to load layers

scripts/known_good.json
Changes:
Internal testing still in-progress
=> build: Update known-good files for 1.2.150 header

scripts/known_good.json
Changes:
Currently running through internal CI
=> build: Update known-good files for 1.2.151 header

BUILD.gn, loader/loader.c
Fixes for errors detected downstream:
https://chromium-review.googlesource.com/c/angle/angle/+/2359758
=> loader: Fixes for gn build

tests/loader_validation_tests.cpp
This fixes #463. See that issue for the background on this.
=> Change license in loader_validation_tests.cpp to Apache 2.0

scripts/known_good.json
Changes:
Change-Id: Ia6090de3d029dd2bf96a8d745d3c95461fd31bd6
=> build: Update known-good files for 1.2.152 header

scripts/known_good.json
Changes:
Running through internal CI now.
=> build: Update known-good files for 1.2.153 header

loader/loader.c
When moving the driver over to using the new vk_icdEnumerateAdapterPhysicalDevices export and ICD version 6 I discovered several issues:
1. It wouldn't work with Windows 7/8/8.1, or other situations when IID_IDXGIFactory6 is not available or failed. When this happened ReadSortedPhysicalDevices() would return VK_SUCCESS and leave sorted_count=0. Later in setupLoaderTermPhysDevs() it would skip enumerating the physical devices in the legacy way with EnumeratePhysicalDevices(). The result was that the loader wouldn't find any physical devices (inst->total_gpu_count stays zero) and fail with VK_ERROR_INITIALIZATION_FAILED.
- The solution is to only skip the legacy path if sorted_count>0.
2. It would fail the "dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail" Vulkan CTS …
=> Fix issues with vk_icdEnumerateAdapterPhysicalDevices

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update known-good files for 1.2.154 header

BUILD.md
=> Remove outdated references to WDK

scripts/known_good.json
=> build: Update known-good files for 1.2.156 header

scripts/known_good.json
Changes:
Change-Id: I7705cbe942a67c7b915349a1c34c7615d1dc4691
=> build: Update known-good files for 1.2.157 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/known_good.json
Changes:
Change-Id: I5f06eec6afb61bac576cbad3e6e6982c0bd0440c
=> build: Update known-good files for 1.2.158 header

loader/CMakeLists.txt
This allows vulkan.pc to be enabled on MinGW
=> Configure vulkan.pc when pkg-config is available

scripts/known_good.json
=> build: Update known-good files for 1.2.159 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update known-good files for 1.2.160 header

scripts/known_good.json
Changes:
Running through internal CI currently.
=> build: Update known-good files for 1.2.161 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/known_good.json
Changes:
Running through internal CI
=> build: Update known-good files for 1.2.165 header

scripts/known_good.json
Changes:
Running through internal CI
=> build: Update known-good files for 1.2.166 header

loader/wsi.c, loader/wsi.h
- Add missing prototype
- Fix incorrect parameter handling
Signed-off-by: Kévin Petit <kevin.petit@arm.com>
=> Fix Android build

cmake/FindVulkanHeaders.cmake
Addresses issue:
https://github.com/KhronosGroup/Vulkan-Loader/issues/532
=> CMake tweak for macOS cross compilers, seems okay elsewhere too

scripts/known_good.json
Changes:
Change-Id: Iaf11b12afdcd11b06ebce4b66a0b56b2b097522f
=> build: Update known-good files for 1.2.169 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
Changes:
Change-Id: I98c582a8cad9ffbdda5a1b2ffa5517b866803047
=> build: Update known-good files for 1.2.170 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/common_codegen.py, scripts/known_good.json
Changes:
- Added `VK_USE_PLATFORM_SCREEN_QNX` to platform list in
`common_codegen.py`
Change-Id: I2ef49799434ff31ff81680413a8700caea46593c
=> build: Update known-good files for 1.2.171 header

scripts/known_good.json
Changes:
Running through internal CI
=> build: Update known-good files for 1.2.172 header

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
- Update known_good.json
- Generate source files
=> build: Update known-good files for 1.2.173 header

loader/LoaderAndLayerInterface.md
=> Update documentation note about vk_icdGetPhysicalDeviceProcAddr

scripts/known_good.json
- Generate source (no changes)
Change-Id: Ia2099a0d63692c19ce8444721d5eb25f94c809d9
=> build: Update to header 1.2.174

.github/workflows/build.yml, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h
The transition from travis to github CI dropped the check for verifying if the
source code generator was updated if it needed to for the changes.
Change-Id: I53fabfe14f42fe1c9899b2938f5e7b8073362954
=> ci: Add verification of generated source code

loader/loader.c
Currently the loader does not distinguish between 32 and 64 bit ELF
class files. This causes `dlopen` to fail but is expected because
the different ELF class libraries are located in the same directory.
We can safely ignore this error. If encountered, we will report it
with the INFO logging level.
Fixes #262 
Change-Id: Icb8e5351208f8a413a29ea9c457bc3fdac7de292
=> loader: Silence wrong ELF class errors

loader/loader.c
This fixes #575. If the json manifest file was too large, the loader would do a stack allocation that would fail, throwing an exception or creating undefined behavior. This changes to a heap allocation.
=> Fix stack overflow with large manifests

scripts/known_good.json
- Generate source (no changes)
=> build: Update to header 1.2.177

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_object_types.h, scripts/known_good.json
=> build: Update to header 1.2.178

scripts/known_good.json
=> build: Update to header 1.2.179

tests/framework/test_util.h
Change-Id: If2b6766521dd6bea5478b6316eadef8ce3e048cf
=> tests: Include <memory> in test_util.h

scripts/known_good.json
=> build: Update to header 1.2.180

scripts/known_good.json
`known_good.json` only, will merge as soon as CI runs.
=> build: Update to header 1.2.181

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/generate_source.py, scripts/known_good.json
- Disable codegen for VK_HUAWEI_subpass_shading KhronosGroup/Vulkan-Docs#1564
Change-Id: If59954254bdf433bd5171f2a63cad88e34069c89
=> build: Update to header 1.2.182

scripts/known_good.json
Change-Id: I059e6c2d8430228b4f20cadb83929b220efa5d0d
=> build: Update to header 1.2.183

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
Change-Id: Ib2cfed88095541a127c23cf7418e9a66d81bd35e
=> build: Update to header 1.2.184

.github/workflows/build.yml
Change-Id: I240f912daa03d001f2dbd2527d8374bbf394ac4a
=> ci: Re-add code and commit formatting verification

loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/generate_source.py, scripts/known_good.json
- Re-enable code generation for VK_HUAWEI_subpass_shading
Change-Id: I6607e1de097d1b8a2f631cd1f11b088204b8bb3a
=> build: Update to header 1.2.185

scripts/known_good.json
Change-Id: I7c0699f8613ecbfefe79981f34faa5e276703324
=> build: Update to header 1.2.186

scripts/known_good.json
=> build: Update to header 1.2.187

scripts/helper_file_generator.py, scripts/known_good.json
No source changes again, just a script tweak and a version bump.
=> 188 header

tests/framework/shim/shim.h
Adds FALLBACK_DATA_DIRS, FALLBACK_CONFIG_DIRS, SYSCONFDIR, and EXTRASYSCONFDIR
to the list of redirected paths. They were previously 'covered' by manual entries.
This commit makes them responsive to changes in the build system.
This commit also makes sure that the path used for redirection is one searched by
the loader by using the SYSCONFIG variable. Previously it would use /usr/local/etc/
which was only correct on systems where CMAKE_INSTALL_PREFIX was set to /usr/local.
=> test: Revamp which linux paths are redirected

tests/framework/layer/test_layer.cpp, tests/framework/layer/test_layer.h, tests/loader_regression_tests.cpp, tests/loader_validation_tests.cpp, tests/run_loader_tests.sh
Moves the old test over into the new test framework.
=> Test: update device layers match

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.2.189

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.2.190

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.2.191

tests/loader_regression_tests.cpp
=> test: Fix 32 bit test suite build error

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.2.192

.github/workflows/build.yml, CMakeLists.txt, loader/CMakeLists.txt
Add an UPDATE_DEPS cmake arg that can be used to automatically run
update_deps.py as needed.
FYI @charles-lunarg @christophe-lunarg. This is effectively just copy/pasted from the VVL repo; quite possible some additional tweaks are necessary.
=> build: Add UPDATE_DEPS cmake arg

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_object_types.h, scripts/known_good.json
=> build: Update to header 1.2.194

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.2.195

loader/extension_manual.c
Set the pToolCount as this function returns VK_SUCCESS.
=> Fix terminator for GetPhysicalDeviceToolPropertiesEXT

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.2.197

docs/LoaderApplicationInterface.md
=> Add missing review comment fields on bundling changes.

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
- Generate source (version bump only)
=> build: Update to header 1.2.198

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
- Generate source (version bump only)
=> build: Update to header 1.2.199

loader/extension_manual.c, tests/loader_regression_tests.cpp
The loader recently added support for calling into drivers in
vkGetPhysicalDeviceToolPropertieesEXT. However, it only used the value of
the function pointer to determine if it was safe. It was found that Mesa
drivers will return a non-null function pointer, even though they do not
support the extension, and so the loader called this function pointer which
would then segfault.
The loader prevents this by first checking if the extension is supported by
the physical device. This necessitates calling
vkEnumerateDeviceExtensionProperties and allocating some memory on each call
but since the number of times this function is called should be low, it is
not an undue performance burden. In the future, the loader should cache the
list of extensions when calling vkEnumeratePhysicalDevices so that …
=> Don't call ToolProps on drivers without support

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
- Generate source (version bump only)
=> build: Update to header 1.2.201

loader/trampoline.c, tests/loader_get_proc_addr_tests.cpp
Vulkan header updated 1.2.193 changed the behavior of vkGetInstanceProcAddr for
global entrypoints. They used to always be returned regardless of the value of
the instance paramtere. The spec was amended in this version to only allow
querying global level entrypoints with a NULL instance. However, as to not
break old applications, the new behavior is only applied if the instance passed
in is both valid and minor version is greater than 1.2, which was when this
change in behavior occurred. Only instances with a newer version will get the
new behavior.
=> Revert to old behavior in GIPA for old apps

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.2.203

BUILD.gn
This CL adds the ability to build for ChromeOS by using the same rules as the Linux ones.
=> Add support for building on ChromeOS

loader/loader.c
We were completely re-creating the physical device lists every time
EnumeratePhysicalDevices was triggered in the loader.  This could
cause applications to have out-dated physical device handles.
We need to copy existing handles that match devices whenever they're
found.
=> Fix Linux sort order crash

tests/loader_get_proc_addr_tests.cpp
Verify that the loader exported version matches the ones you
receive from vkGet****ProcAddr.
=> Add a few tests to verify the vkGet***ProcAddr commands

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.205

loader/CMakeLists.txt
We don't want Apple builds using the Linux sorting algorithm.
=> Fix Apple build

tests/live_verification/CMakeLists.txt, tests/live_verification/dynamic_loader_behavior/CMakeLists.txt, tests/live_verification/dynamic_loader_behavior/dynamic_library.cpp, tests/live_verification/dynamic_loader_behavior/dynamic_library.h, tests/live_verification/dynamic_loader_behavior/dynamic_loading_behavior.md, tests/live_verification/dynamic_loader_behavior/test_dynamic_linking.cpp, tests/live_verification/dynamic_loader_behavior/test_dynamic_loading.cpp, tests/live_verification/dynamic_loader_behavior/test_dynamic_loading_and_linking.cpp
Executes various combinations of loading and linking to libraries which
export the same symbols.
=> Add live tests for OS dynamic loader behavior

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.207

BUILD.gn
Fixes #878
@MarkY-LunarG @charles-lunarg PTAL
=> Disable unused-but-set warning in GN.

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.208

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.209

loader/generated/vk_loader_extensions.c, loader/loader.c, loader/loader_windows.c, loader/trampoline.c, scripts/loader_extension_generator.py, tests/framework/layer/test_layer.cpp, tests/framework/layer/test_layer.h, tests/framework/shim/windows_shim.cpp, tests/framework/test_environment.h
The VS Analyzer went through the codebase and pointed out a dozen warnings and
one possible crash.
=> Fixup several small issues found by Visual Studio

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.210

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.211

docs/LoaderDriverInterface.md, docs/LoaderLayerInterface.md, loader/cJSON.c, loader/cJSON.h, loader/loader.c, loader/wsi.c
Also fixed up the docs by adding language identifiers to code snippets and fixed spelling mistakes in the rest of the source.
=> Document VK_KHR_portability_enumeration support

.github/workflows/build.yml, loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.212

loader/loader.h
=> Correctly check for NULL in loader_get_dispatch

loader/loader.c, tests/framework/layer/test_layer.cpp, tests/framework/layer/test_layer.h, tests/loader_unknown_ext_tests.cpp
Reverts KhronosGroup/Vulkan-Loader#898
=> Revert "Implement unknown function intercept in layers"

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.214

docs/LoaderDriverInterface.md, docs/LoaderLayerInterface.md
Mention the supported versions that were missing.
=> Update supported versions in the docs

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.215

loader/allocation.c, loader/allocation.h, loader/cJSON.c, loader/cJSON.h, loader/debug_utils.c, loader/dirent_on_windows.c, loader/dirent_on_windows.h, loader/get_environment.c, loader/loader.c, loader/loader_linux.c, loader/loader_windows.c, loader/trampoline.c, loader/vk_loader_platform.h, loader/wsi.c
Revamped the allocation functionality.
Includes:
* Added calloc & use it where applicable
* Make cJSON use allocation callbacks directly
* Make dirent_on_windows use allocation callbacks directly
=> Refactor allocation logic

docs/LoaderDriverInterface.md, docs/LoaderLayerInterface.md
Better describe the function's purpose and behavior, moving the
reason for introducing vk_layer|icdGetPhysicalDeviceProcAddr to
a following section for clarity.
=> Update layer and driver vkGetPhysDevProcAddr docs

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.216

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.217

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json, tests/framework/test_util.h, tests/loader_regression_tests.cpp
=> build: Update to header 1.3.218

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.219

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.222

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.223

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.224

loader/loader.c
loader_make_Version previously would decode the major, minor, and patch info out of version data. This results in
erroneous version checks that took into account patch version when they shouldn't of. The loader_make_full_version
function is introduced for code that wishes to get the full major.minor.patch version and uses of
loader_make_version that need the full version have been replaced.
=> Separate Major.minor version checks from Full version checks

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.225

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.226

loader/loader_windows.c
https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/CALK-3mLynzo8%3D9tOoGjwUUWTCtG_MHb5L1Pzd_GCQ%2B8pR637MQ%40mail.gmail.com/#msg37677890
=> appmodel.h is not yet available on mingw stable

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.228

.github/workflows/build.yml, loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.229

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, loader/generated/vk_object_types.h, scripts/known_good.json
=> build: Update to header 1.3.230

loader/loader.c
Reverts KhronosGroup/Vulkan-Loader#1021
=> Revert "Don't load layer libraries in vkCreateDevice"

loader/loader.c
The change to stop loading layers assumed that the handle was always valid. There are cases where the layer fails to load but wasn't removed from the list. While fixing those cases is more desireable, this will resolve the issue.
The change of a continue to a break in the code is because the commit which removed it was erroneous in thinking it wasn't necessary. To preserve existing behavior, break was added because it performs the same behavior as 'if(done) continue;' did.
Fixes #1029
=> Skip layers in device creation with a NULL handle

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.231

docs/LoaderDriverInterface.md, loader/generated/vk_loader_extensions.c, scripts/loader_extension_generator.py
Reverts KhronosGroup/Vulkan-Loader#1028
=> Revert "Document that vk_icdGetInstanceProcAddr is the same as vkGetInstanceProcAddr"

docs/LoaderDriverInterface.md, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, loader/wsi.c, scripts/loader_extension_generator.py, tests/framework/icd/test_icd.cpp, tests/framework/test_util.cpp, tests/framework/test_util.h, tests/loader_regression_tests.cpp
Reverts #1042 by adding back the functionality with a fix for swapchain creation as well as a bespoke test for it.
Fixes #5 without introducing critical defects...
=> Correctly load icd vk create swapchain khr with gdpa

docs/LoaderDriverInterface.md, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, loader/wsi.c, scripts/loader_extension_generator.py, tests/framework/icd/test_icd.cpp, tests/framework/test_util.cpp, tests/framework/test_util.h, tests/loader_regression_tests.cpp
Reverts KhronosGroup/Vulkan-Loader#1043
=> Revert "Correctly load icd vk create swapchain khr with gdpa"

loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.232

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.233

loader/loader_common.h
Nothing in this file was being used.
=> Do not include vk_sdk_platform.h

loader/cJSON.c
This makes it possible to build Vulkan-Loader without warnings using the macOS 13 SDK. Calls to `sprintf` are replaced with `snprintf`, passing appropriate buffer sizes.
It doesn’t appear that any of the changed uses of `sprintf` were actually unsafe, so no behavior change is expected aside from SDK compatibility.
The macOS 13 SDK deprecates `sprintf` as it’s difficult to use safely. The deprecation warning message is visible when building C++, but it is not normally visible when building plain C code due to a quirk in how `sprintf` is declared in the SDK. However, the deprecation message is visible when building plain C under Address Sanitizer (`-fsanitize=address`). This discrepancy was discovered at https://crbug.com/1381706 and reported to Apple with a copy at …
=> loader/cJSON: replace sprintf calls with snprintf

CMakeLists.txt, loader/generated/loader_generated_header_version.cmake, scripts/known_good.json
=> build: Update to header 1.3.234

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_object_types.h, scripts/known_good.json
=> build: Update to header 1.3.235

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.236

loader/generated/loader_generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, scripts/known_good.json
=> build: Update to header 1.3.238

.github/workflows/build.yml
Prevent problems like this:
https://github.com/KhronosGroup/Vulkan-Loader/issues/1095
=> ci: Test CMake minimum

cmake/generated_header_version.cmake, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, scripts/known_good.json
=> build: Update to header 1.3.239

.github/workflows/build.yml, BUILD.md, CONTRIBUTING.md, README.md, docs/LoaderApplicationInterface.md, docs/LoaderDriverInterface.md, docs/LoaderInterfaceArchitecture.md, docs/LoaderLayerInterface.md, scripts/check_code_format.sh, scripts/update_deps.py
=> github: Use main instead of master

.gn, build-gn/DEPS, cmake/generated_header_version.cmake, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.240

.github/workflows/build.yml, BUILD.md, CMakeLists.txt
Matches what VVL currently uses
=> cmake: Update minimum to 3.17.2

.github/workflows/build.yml
- Fix CI warnings about setup-python@v2
=> Fix CI warnings

CMakeLists.txt, cmake/generated_header_version.cmake, loader/CMakeLists.txt, loader/vulkan.pc.in, scripts/generate_source.py
Update the CMake project version instead of updating a generated file.
=> cmake: Add VULKAN_LOADER_VERSION

CMakeLists.txt, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json, scripts/loader_extension_generator.py
=> build: Update to header 1.3.241

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.242

CMakeLists.txt, loader/loader.rc, scripts/known_good.json, tests/framework/test_util.h
- Add new return code to test_util.h
=> build: Update to header 1.3.243

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.245

CMakeLists.txt, loader/generated/vk_dispatch_table_helper.h, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_object_types.h, loader/loader.rc, scripts/known_good.json, tests/framework/test_util.h
=> build: Update to header 1.3.246

.github/workflows/build.yml
Ubuntu 18 has been removed thus we are updating to Ubuntu 22
=> Use Ubuntu 22 in github actions

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.247

loader/loader_environment.c, tests/loader_layer_tests.cpp
It is unhelpful to have zero diagnostics emitted when the layers listed in VK_INSTANCE_LAYERS are not found.
Partially addresses #1173
=> Log ERROR when layers in VK_INSTANCE_LAYERS are missing

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.248

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.249

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.250

.github/workflows/build.yml, CMakeLists.txt
=> ci: Test pkg-config and installation

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.251

.github/workflows/build.yml
=> Add clang-cl run to github actions CI

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.253

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.254

BUILD.md, CMakeLists.txt, tests/framework/icd/physical_device.h, tests/framework/icd/test_icd.cpp, tests/framework/icd/test_icd.h, tests/framework/layer/layer_util.h, tests/framework/layer/test_layer.cpp, tests/framework/layer/wrap_objects.cpp, tests/framework/shim/shim.h, tests/framework/shim/shim_common.cpp, tests/framework/shim/windows_shim.cpp, tests/framework/test_environment.cpp, tests/framework/test_environment.h, tests/framework/test_util.cpp, tests/framework/test_util.h, tests/loader_alloc_callback_tests.cpp, tests/loader_debug_ext_tests.cpp, tests/loader_envvar_tests.cpp, tests/loader_get_proc_addr_tests.cpp, tests/loader_handle_validation_tests.cpp, tests/loader_layer_tests.cpp, tests/loader_phys_dev_inst_ext_tests.cpp, tests/loader_regression_tests.cpp, tests/loader_settings_tests.cpp, tests/loader_threading_tests.cpp, tests/loader_unknown_ext_tests.cpp, tests/loader_version_tests.cpp, tests/loader_wsi_tests.cpp
Big set of changes that clean up the test code in addition to raising the C++ minimum to 17.
=> Use cpp 17 & refactor tests

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.255

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.256

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.257

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.258

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.259

tests/loader_layer_tests.cpp
Makes sure that any explicit layers with pre_instance_functions are ignored, even if they would be enabled by an override layer or the settings file.
=> Add tests for explicit layers with pre_instance_functions

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json, scripts/loader_extension_generator.py
=> build: Update to header 1.3.260

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.261

scripts/known_good.json
https://github.com/google/googletest/pull/4288
=> cmake: Fix gtest CMake warning

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.262

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.263

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.264

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.265

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.266

CMakeLists.txt, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.267

loader/CMakeLists.txt, loader/vulkan.pc.in
closes #1318, #1319
@jbeich double check this fixes your issues. I believe I've reverted the logic appropriately.
=> cmake: Fix vulkan.pc regressions

CMakeLists.txt, loader/CMakeLists.txt
A lot easier to read than `UNIX NOT APPLE`
=> cmake: Check system name for Linux|BSD

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.268

.github/dependabot.yml, .github/workflows/build.yml
Update actions via automated PRs.
I've done this for headers and utility libraries already.
=> Add dependabot

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_object_types.h, loader/loader.rc, scripts/helper_file_generator.py, scripts/known_good.json
- Fix hard-coded tag index for getting extension names from vk.xml
- Relax regex for correlating kVulkanObjectType* with VK_DEBUG_REPORT_OBJECT_TYPE_* by making the trailing _EXT optional
=> build: Update to header 1.3.269

scripts/qnx/README.md
=> docs: Document QNX build

loader/CMakeLists.txt
=> cmake: Document why BUILD_STATIC_LOADER doesn't install

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.270

BUILD.gn, CMakeLists.txt, loader/vk_loader_platform.h
Don't see any reason for this to exist.
=> Remove API_NAME

.github/workflows/build.yml, tests/CMakeLists.txt, tests/framework/test_util.h
Needed for iOS / simulator testing
=> Test Xcode generator

CMakeLists.txt, loader/generated/vk_loader_extensions.c, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.272

.github/workflows/build.yml, CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.273

CMakeLists.txt, loader/generated/vk_layer_dispatch_table.h, loader/generated/vk_loader_extensions.c, loader/generated/vk_loader_extensions.h, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.274

.github/workflows/build.yml
Test both GNU clang and clang-cl
Use Ninja for performance
=> Improve clang on Windows testing

loader/CMakeLists.txt
Provides versioning information for the CMake package
=> Add VulkanLoaderConfigVersion.cmake

CMakeLists.txt, loader/CMakeLists.txt
Simplifies the code
Idiomatic way of setting visibility via CMake
=> Set CMake properties consistently

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.275

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.277

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.278

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.279

CMakeLists.txt, loader/loader.rc, scripts/known_good.json
=> build: Update to header 1.3.280

loader/cJSON.c
Split out the JSON file opening and reading logic into a Windows and Posix function to allow only reading the contents of a file once.
This is the same code as #1499 but because I am a doofus and messed up the git commands, I need to remake the PR (as because I force pushed to the branc116 branch the contents of main, github auto-closed the PR denying me the chance of fixing it without reopening a new PR).
=> Stop reading json files twice

tests/loader_regression_tests.cpp
Exercises the situation where there are enough adapters per physical gpu to cause resizing of the buffer which stores them.
Is the test for #1562
=> Add tests fo windows read sorted adapters buffer overrun

.github/workflows/build.yml
Prevent bad builds from blowing through Github Action Minutes
=> ci: Build dependency for Github Actions

loader/settings.c
Logs cases which cause the vk_loader_settings.json to fail to parse.
=> Add more logging when the settings file has invalid members

.github/workflows/build.yml
Ubuntu 20 is being removed from actions, so we need to update
=> Update Github Actions to use Ubuntu 24 & 22

scripts/loader_extension_generator.py
Codegen is currently broken on main...
=> scripts: Fix f-strings

scripts/generate_source.py, scripts/loader_extension_generator.py, scripts/loader_genvk.py
closes https://github.com/KhronosGroup/Vulkan-Loader/issues/1679
=> scripts: Have legacy genvk point to new script
